### ISSUE TITLE
Toppmeddelande för Strukturer under start

### ISSUE THREAD

**Issue by legander** [malmostad/sitevision_assets#173]
Fundera ut funktion för att skapa toppmeddelande på delstrukturer. ( Samma design som "vanliga" toppmeddelande). Bara HR ska ha rättigheter för att skapa.

**Comment by Svempan** [comment]
Hittar inte sektionstoppsmedellandemallen. Alltså mallen för sektionstoppsmeddelande :-)
Var sig i Test eller Prod. Har den försvunnit eller aldrig funnits?

**Comment by hryd** [comment]
För både start- och sektionstoppmeddelande används mallen toppmeddelande. Se exempel här http://www.test.malmo.se/4.3101c0911206abdf073800036271.html

**Comment by olajoh1** [comment]
ok
