### ISSUE TITLE
Kontaktinfo visas inte på www.test

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#211]
Jmf kontakt på dessa två sidor. 

http://www.test.malmo.se/Kultur--fritid/Kultur--noje/Arkiv--historia/Stadsarkivet/Om-oss/Besoksinformation.html

http://malmo.se/Kultur--fritid/Kultur--noje/Arkiv--historia/Stadsarkivet/Om-oss/Besoksinformation.html

@martent @hryd

**Comment by martent** [comment]
Utfört i prod.
