### ISSUE TITLE
Markup-validering för nyheter

### ISSUE THREAD

**Issue by martent** [malmostad/sitevision_assets#217]
Fick in några noteringar kring markupvalideringsfel som upprepas på sidorna. 

1. I nyhetstickern, saknas citat-tecken runt `href`-attributen, även för more. T.ex. på startsidan.
2. `&` är inte escapade i nyhetsurlerna på t.ex. http://malmo.se/Bo-bygga--miljo/Gora-hallbara-val.html

Inget funktionellt problem. Ta det när det passar.

@hryd

**Comment by Esset** [comment]
Se prod

**Comment by martent** [comment]
Toppen!
