### ISSUE TITLE
Brödsmula på nyhetsarkivsidan

### ISSUE THREAD

**Issue by Esset** [malmostad/sitevision_assets#222]
Brödsmulan visar bara __start__ oberoende av hur långt ner i strukturen man kommer in på nyhetssidan infrån.

__Scenario 1 (korrekt):__
    Klickar på _flera artiklar_ på startsidan -> brödsmulan på nyhetssidan visar __start__ (Som den ska)

__Scenario 2 (fel):__
    Klickar på _flera artiklar_ på _Start /Förskola & utbildning/Grundskola_ -> brödsmulan på nyhetssidan visar __start__ (Den ska visa _Start /Förskola & utbildning/Grundskola_)

**Comment by Svempan** [comment]
Ok, nu verkar det funka. Deploya vid nästa tillfälle.

**Comment by Esset** [comment]
Se prod

**Comment by Svempan** [comment]
Ser ut att funka. Stänger.
