### ISSUE TITLE
Fullbreddsmall

### ISSUE THREAD

**Issue by Svempan** [malmostad/sitevision_assets#224]
Vi behöver en fullbreddsmall, dvs mall med bara huvud och sidfot.
Ingen begränsning av bredd. Endast HR ska ha behörighet.
@martent @olajoh1

**Comment by Esset** [comment]
Finns nu på test

**Comment by Svempan** [comment]
Mårten testar

**Comment by martent** [comment]
Lägg ut i prod!

**Comment by Esset** [comment]
Ute i prod nu.

**Comment by martent** [comment]
Tack.
