### ISSUE TITLE
Mappnamn syns i högernavigering

### ISSUE THREAD

**Issue by Svempan** [malmostad/sitevision_assets#227]
Namnet på de gula mapparna syns i högernavigeringen om sidan under inne har några barn.
Förmodligen kom felet med den senaste deployen i samband med #158 . Ex:
http://www.malmo.se/Fot/Roller/Anstalld.html
@martent @olajoh1

**Comment by Esset** [comment]
Uppdaterat på test. Nu står närmsta föräldersida som rubrik om föräldern är en mapp och nuvarande sida inte har några barn.

**Comment by olajoh1** [comment]
Ytterligare en menybugg:

![meny](https://cloud.githubusercontent.com/assets/6176181/5664882/132c8e42-9754-11e4-8a09-5b0d0daf8b0c.jpg)

**Comment by Esset** [comment]
Drog iväg en ticket till SiteVisions support. @olajoh1

**Comment by Svempan** [comment]
Tycker inte det verkar funka på inloggningesidan t ex (i test). Där visas" Mer i detta ämne".

**Comment by Esset** [comment]
Jag lägger till uppdaterat menyskript i test.

**Comment by Esset** [comment]
Har lagt upp menyskriptet på test nu, vi slipper även velocitybuggen då den är omskriven i JS istället.

**Comment by Svempan** [comment]
Funkar vad jag kan se. Kör ut i prod vid tillfälle.

**Comment by Esset** [comment]
Ute i prod nu.
