### ISSUE TITLE
Funktionskontakt

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#228]
1.
Ledtexter ska skrivas konsekvent enligt följande mönster:

Telefontider: <telefontider>

Ledtexten för telefontider följer inte det mönstret.

2.
Besökstider visas inte.

@martent

**Comment by rbolton479** [comment]
har du något exempel kontakt med besökstider?

**Comment by olajoh1** [comment]
Testa med funktionskontakten "testola"

**Comment by Esset** [comment]
Här visas besökstider
http://malmo.se/Kommun--politik/Organisation/Stadsomradesforvaltningar.html

**Comment by olajoh1** [comment]
![kontaktrutan](https://cloud.githubusercontent.com/assets/6176181/6021847/06b341aa-abb9-11e4-9c12-9c8032457e33.jpg)

se ledtexten för telefontider

**Comment by olajoh1** [comment]
Besökstider visas ej. 

![besokstider__1](https://cloud.githubusercontent.com/assets/6176181/6021992/0e898ba4-abba-11e4-9258-bd3296741893.jpg)
![besokstider_2](https://cloud.githubusercontent.com/assets/6176181/6021991/0e890756-abba-11e4-9f5e-9b8d0a6ea204.jpg)

**Comment by rbolton479** [comment]
kan du lägga samma kontakt på test så att jag kan undersöka, tack

**Comment by olajoh1** [comment]
Finns en funktionskontakt nedan med samtliga uppgifter ifyllda:

"test tidernamn"

**Comment by rbolton479** [comment]
tack ola

**Comment by rbolton479** [comment]
Fixad. Testa på http://www.test.malmo.se/Teststruktur/Kontakt-test-2.html

**Comment by olajoh1** [comment]
Fungerar inte att testa på www.test.malmo.se. Verkar inte finnas koppling mot kontaktboken.

@martent

**Comment by martent** [comment]
Det beror på att jag tog en kopia på prod-databasen av dashboarden inför att du skulle verifiera den innan den går i produktion. Kontaktrutan använder test-nyckel, men det ligger prod i test, typ.

Jag ger @rbolton479 en ny nyckel till test.

**Comment by rbolton479** [comment]
nu har jag installerat nya version my en ny nyckel

**Comment by rbolton479** [comment]
jag testade några sidor i olika delar av sajten och det funkar

**Comment by olajoh1** [comment]
Detta ärende handlar om en ledtext och att besökstider inte visas. Vi har ett annat allvarligt och akut ärende som handlar om att kontaktinfo inte visas.#236

**Comment by olajoh1** [comment]
Får in felrapporter på att besökstider inte visas. Viktigt att åtgärda.

**Comment by rbolton479** [comment]
This is fixed of course #236 but I think we have all forgotten about it and it just needs to be deployed to prod. Not possible today I dont think, as i'm heading to prague in about an hour.

**Comment by olajoh1** [comment]
Ok, vi deployar någon gång under nästa vecka. När tror du det passar?

**Comment by rbolton479** [comment]
I get back monday afternoon so we could do it then, and I guess we could even deploy to komin aswell, would make sense I guess.

**Comment by olajoh1** [comment]
Kan vi deploya på tisdag?

**Comment by rbolton479** [comment]
I can build the jars and leave them in the svdeploy home directory if you wish but I start at skatteverket tomorrow and it's a full time assignment so I will not be able to deploy anything tomorrow.

**Comment by martent** [comment]
A handover to @hryd and @Esset is better so that they can deploy, check the expected outcome and take action if somethings fails.
