### ISSUE TITLE
Menyn

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#229]
![menyfel](https://cloud.githubusercontent.com/assets/6176181/5797402/6fe3112a-9fb9-11e4-8365-86f0b396ff47.jpg)

**Comment by Esset** [comment]
>Hej Simon,
>
>Jag har tittat in där nu men det är inte mycket vi kan göra så vitt jag kan se.
>
>Jag lyckades inte återskapa felet och har det bara hänt en gång får vi nog lägga det i en låda med tillfälligheter. Finns inte mycket att gå på för att felsöka vad som gick fel i macrot vid just den körningen. 

>Med vänliga hälsningar,
>Klas Hedström
>SiteVision support

**Comment by olajoh1** [comment]
Vi har två case men det är väl bara att avvakta fler så ett mönster uppstår.
