### ISSUE TITLE
Dekorationen "Fokusyta - Agera" är inte responsiv

### ISSUE THREAD

**Issue by Svempan** [malmostad/sitevision_assets#230]
Se exempel:
http://www.malmo.se/Teststruktur/Ar-agera-dekorationen-responsiv.html

**Comment by Esset** [comment]
Ska vi köra ellipsis eller vad säger du? @martent

**Comment by martent** [comment]
Ja, kör ellipsis. Radbrytning i knappar blir det inte tal om.

**Comment by martent** [comment]
Ta bort underline vid hover också. Inte så vanligt på knappar.

http://malmostad.github.io/prototypes/external/body-copy-11/

**Comment by Esset** [comment]
Se http://www.test.malmo.se/4.4d0298e114b26310ffe899.html

**Comment by martent** [comment]
Utmärkt. Över till @Svempan

**Comment by Svempan** [comment]
Jag kommer inte åt sidan. Kommer bara till inloggningssidan. Var finns den? @Esset

**Comment by Esset** [comment]
/Teststruktur/simon/Startsidatest/Test-Agera @Svempan

**Comment by Svempan** [comment]
Jag har inte behörighet till den sidan. Den är låst (nyckel). @Esset

**Comment by Esset** [comment]
test.malmo.se/Teststruktur/Startsida/Navigationssida/Test-agera
Så nu har jag lagt till din användare på sidan

**Comment by Svempan** [comment]
Ok. Ser bra ut. Deploya vid tillfälle.

**Comment by Esset** [comment]
Ligger i prod, se http://malmo.se/Forskola--utbildning/Grundskola/Stod-och-service/Skolmat.html

**Comment by Svempan** [comment]
OK Stänger
