### ISSUE TITLE
Brödsmulan försvinner på arkiv

### ISSUE THREAD

**Issue by Svempan** [malmostad/sitevision_assets#231]
Om man är på denna sidan:
http://malmo.se/Kultur--fritid/Kultur--noje/Barn--familj.html
Och klickar på "Fler artiklar" så försvinner brödsmulorna:
http://malmo.se/Nyheter.html?date=20150131&origin=4.76105f1c125780a6228800096842&source=3.12e2278a148980ba13a88055
Vad kan ha gått fel?

**Comment by Esset** [comment]
Det var en bugg i skriptet, jag har fixat det på test nu. Håller på att testa det också.
Se: www.test.malmo.se/Kultur--fritid/Kultur--noje/Barn--familj.html

**Comment by Svempan** [comment]
Hm... Det står "null null null Barn & familj" i brödsmulorna

**Comment by olajoh1** [comment]
Sven, vill du testa igen

**Comment by Esset** [comment]
Lägger ut i prod.

**Comment by Esset** [comment]
Ute i prod nu.

**Comment by Svempan** [comment]
OK. Stänger.
