### ISSUE TITLE
Döpa om modulen Kontaktrutan Stadsområden

### ISSUE THREAD

**Issue by Svempan** [malmostad/sitevision_assets#233]
Kan vi döpa om modulen i Sitevision. Den heter idag "Kontaktruta Stadsområden" vilket är missvisande då den även används där vi inte behöver områdesväljare. Föreslår att den bara heter "Kontaktruta".
Kan man ändra detta utan att allt kraschar? :-)

**Comment by rbolton479** [comment]
jag tror det är portlet som måste ändras här, namnet kommer från portlet.xml. Det heter 'Kontaktruta stadsområden' eftersom tidigare har det funnits tre olika config i samma portlet. Kan testa ändra på test och ser vad som händer

**Comment by rbolton479** [comment]
Looks like you will have to re-add each portlet if you change the name. Unless simon has a solution, Simon????

**Comment by Svempan** [comment]
OK. Vi tar inga risker nu. Så vi struntar i det nu.
