### ISSUE TITLE
Fix för framåtkompatibilitet för banner

### ISSUE THREAD

**Issue by martent** [malmostad/sitevision_assets#234]
När vi inför v4 för intranätet har vi en class-namnskonflikt som vi måste ändra. `.banner` finns redan i SV-intranätet för mängder av små vinjettrubriker som vi inte får bort. När sitevision_assets v4 kommer in så blåses dessa upp till jättebanners (malmo.se-banners). 

Vid tillfälle, ändra `.banner` till `.big-banner`. Detta får nog göras i tre steg om vi inte ska få ett glapp mellan css-deploy och malländring misstänker jag:

1. Dubbla selectorn `.banner` (+ inverted etc.) med `.big-banner` i Sassen och deploya den.
2. Ändra från `.banner` till `.big-banner` SV-templaten.
3. Ta bort `.banner` från Sassen och deploya.

**Comment by martent** [comment]
@olajoh1

**Comment by Esset** [comment]
Yes, ändrat på prod.

**Comment by martent** [comment]
:cake:
