### ISSUE TITLE
Fix för framåtkompatibilitet för movies

### ISSUE THREAD

**Issue by martent** [malmostad/sitevision_assets#235]
När vi inför v4 för intranätet kommer vi att att stilsättning av en film-portletten med fyra bilder mot nuvarande sex på malmo.se. För att kunna köra samma assets parallellt gör vi en ändring i html-koden för film-modulen, lägg till classen `n6` till ul i section.movies. typ:

```html
<section class="movies">
  <h1>Webbvideo</h1>
  <ul class="n6">
```

CSS som kommer senare innehåller alltså olika flödning för `ul.n6 li` och `ul.n4 li`. Ändringen i film-portletten på malmo.se kan göras när som helst men måste göras innan CSS-koden börjar delas mellan extern och intern lösning.

@olajoh1

**Comment by hryd** [comment]
Deployed på produktion för externwebb och test för komin.

**Comment by martent** [comment]
:accept:
