### ISSUE TITLE
Default i kontaktruta borta?

### ISSUE THREAD

**Issue by Svempan** [malmostad/sitevision_assets#236]
Det ser ut som att man inte får några kontaktuppgifter alls (ska vara Malmö stads växel) vid nya sidor och att det sidor som kör default har "kontakten har tagits bort".
@olajoh1

**Comment by olajoh1** [comment]
Kontaktinfo tycks inte visas på några sidor. Data finns i meta v44, men syns inte i kontaktrutan eller på sidan.
@Esset @rbolton479

**Comment by rbolton479** [comment]
can you give some examples please

**Comment by olajoh1** [comment]
Du kan titta på vilken sida som helst

**Comment by rbolton479** [comment]
I already did that this morning but i'll check again and see what's going on

**Comment by rbolton479** [comment]
http://www.test.malmo.se/Forskola--utbildning/Grundskola/Stod-och-service/Skolmat.html

http://www.test.malmo.se/Bo-bygga--miljo/Bygga-nytt---bygga-till.html

http://www.test.malmo.se/Kultur--fritid/Besoka-Malmo.html

some of the pages I looked at.

**Comment by olajoh1** [comment]
http://malmo.se/Kultur--fritid/Biblioteken/Vara-bibliotek.html

http://malmo.se/Kultur--fritid/Idrott--fritid/Ung-fritid/Fritidsgardar--motesplatser.html

![bibliop_kontakt](https://cloud.githubusercontent.com/assets/6176181/6164613/0757e810-b2a1-11e4-8940-4f277cdb5832.jpg)

**Comment by rbolton479** [comment]
This must be to do with the new keys mårten created because the same Id exists on test and test works, which means we will have to do a release to prod in order to fix it

**Comment by martent** [comment]
Correct me if I'm wrong @olajoh1 but this is a problem in production, not in test?

The new keys is for test, **not** production, see https://github.com/malmostad/sitevision_assets/issues/228#issuecomment-73905637

**Comment by olajoh1** [comment]
Production, see example above

**Comment by martent** [comment]
Wild guess: @rbolton479 mixed up test and production and put the new test keys in production.

**Comment by martent** [comment]
Ser ut som om det funkar nu i prod.

**Comment by rbolton479** [comment]
No wild guesses please :-)  The only release  done in the last 24 hours was to test, you cant mix them up, and I would never do it without your authority.

**Comment by martent** [comment]
Sorry @rbolton479. It's working now in prod?

I tested the new test keys against the test env, and they work too.

**Comment by rbolton479** [comment]
It's seems to be working now in prod but I can't take the credit for that because I haven't been near it since the last release. :-)

**Comment by martent** [comment]
@olajoh1 & @Svempan, can you verify?

**Comment by olajoh1** [comment]
Fungerar. Jag skulle dock vilja vet orsaken till problemet.

**Comment by rbolton479** [comment]
Me too
