### ISSUE TITLE
Metadata för läs mer och faktaruta

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#237]
Återgå till dekorationer för dessa innehållselemnet.

**Comment by Esset** [comment]
1 Skript som listar förekomsterna av läs mer och faktaruta.
2 Ersätt med dekorationsmallar.

**Comment by Esset** [comment]
Vad sa vi om nyheter? I dagsläget så visas varken fakta eller läs mer på nyheter men metadatat finns på mallen. Är det så att vi hade dessa funktioner på nyheter en gång i tiden men beslutade om att strypa den tillgången? @olajoh1 @martent

**Comment by olajoh1** [comment]
läggs till i nyheter

**Comment by legander** [comment]
Skickade ett excelblad med lista på förekomsten av dessa metadatan. Nyheter som har metadatat fakta kommer att vara med i excelen men syns inte utåt då vi exkluderat just den funktionen vid något tidigare tillfälle. Någon som minns varför vi gjorde det? @hryd @martent

**Comment by olajoh1** [comment]
Simon och Henrik lämnar förslag på lösning, hur vi ska hantera en övergångsperiod med dubbla lösningar, tisdagen den 5 maj.

**Comment by olajoh1** [comment]
Klar för implementering. så fort boxen är klar för Komin.

**Comment by Svempan** [comment]
Vad är status här?
@olajoh1

**Comment by hryd** [comment]
Lade upp samma implementering på test.malmo.se som komin har. Stäm av och säg till när det ska ut i produktion. @olajoh1 @Svempan

**Comment by olajoh1** [comment]
ok? @Svempan

**Comment by olajoh1** [comment]
Om det är ok skriv det här @Svempan

**Comment by Svempan** [comment]
Hjälp mig här. Jag lägger på dekoration "Läs mer" eller "Fakta" men inget händer. Vad gör jag för fel?

**Comment by hryd** [comment]
Det fungerar likadant som på komin. Lägg till en layout med dekorationsmall och i den placera en rubrik med format h2 samt brödtext. Jag ringde nyss, ring upp vid tillfälle om du inte får till det.

**Comment by olajoh1** [comment]
@Svempan uppdaterar du wikin så att vi kan lansera förändringen?

**Comment by Svempan** [comment]
Ok. Kör ut i prod vid tillfälle.

**Comment by Svempan** [comment]
Ok. Kör ut i prod vid tillfälle.

**Comment by hryd** [comment]
Deployed i prod. Tänk på att rensa cache eller uppdatera sidan med Ctrl + F5 om boxarna inte visas korrekt.

**Comment by Svempan** [comment]
Topp
