### ISSUE TITLE
Videospelarens filtrering fungerar inte

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#239]
Videospelaren har ett "custom fields" som heter "target Group" som ska användas för filtrering. TG kan ha tre värden, blankt, komin eller malmo.se. 

Filmer som ska visas på malmo.se är de som har värdet blankt" eller "malmo.se". Motsv för KOmin.

Denna filtrering fungerar på startsidan för malmo.se men inte om videospelaren används på andra sidor.

**Comment by hryd** [comment]
Jag har hittat felet till buggen, däremot verkar felet vara konsekvent även på startsidan. Syns om ni t.ex. väljer "Aktuellt komin". 

Jag borde kunna fixa detta till på fredag eller måndag.

**Comment by hryd** [comment]
Fixat, deployar imorgon förmiddag.

**Comment by olajoh1** [comment]
ok
