### ISSUE TITLE
Kontaktruta funkar inte i gren

### ISSUE THREAD

**Issue by Svempan** [malmostad/sitevision_assets#241]
Vad kan ha hänt här? Ingen kontaktruta och modulen går inte att öppna.

![skarmklipp_kontaktruta](https://cloud.githubusercontent.com/assets/7701048/6482402/cd886a9a-c265-11e4-9f70-e6936921b1d3.JPG)

@olajoh1

**Comment by martent** [comment]
Stokastisk. Vi stänger.
