### ISSUE TITLE
Tillfällig 404 för releasefönster

### ISSUE THREAD

**Issue by martent** [malmostad/sitevision_assets#242]
Utgå från denna och kompletter med länkar @olajoh1 

https://webapps06.malmo.se/maintenance.html

Jag uppdaterar länkfärg först :snail:

**Comment by martent** [comment]
Jag har uppdaterat designen.

Länken Vår kommun ska bort när sidan läggs i SV. [Min sida](https://webapps06.malmo.se/dashboard/) bör ligga överst.

**Comment by olajoh1** [comment]
Kan du i sidan infoga en bruttolista med länkar från Verktyg & system samt Jag vill..?

**Comment by martent** [comment]
Kom ihåg att diskutera med @legander på möte om hur vi tänkt med det tillfälliga huset i SV som ska studsa till webapps04.

**Comment by martent** [comment]
Allt förberett. @legander tar sidan och lägger som 404 och 500-sida i SV på ett tillfälligt hus under releasen. Lägger också en JS-redirect till Min sida som motsvarar den som ligger i prod.

**Comment by olajoh1** [comment]
Kan jag komma åt att uppdatera sidan nedan?

https://webapps06.malmo.se/maintenance.html

**Comment by martent** [comment]
Nej, den ligger inte i ett CMS.

**Comment by olajoh1** [comment]
Mårten & Sven
Förslag på tillfällig sida. Granska gärna text och att länkarna verkligen är rätt. Saknas någon tjänst?

https://komin.test.malmo.se/editor/index.jsp?objectId=4.6a5e68e412a855c411180009945

@martent @Svempan

**Comment by martent** [comment]
Är länken korrekt?

**Comment by olajoh1** [comment]
http://komin.test.malmo.se/ola/Tillfallig-404.html
