### ISSUE TITLE
Rubrik för kontaktrutan

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#243]
![kontaktaoss](https://cloud.githubusercontent.com/assets/6176181/6615299/134e03e4-c8a3-11e4-9a3f-8e4d35a24159.jpg)

Kan du ändra rubriken på intranätet från "Kontakta oss" till "Kontakt"

**Comment by Esset** [comment]
Det ligger i portleten skickar över denna till Henrik.

**Comment by hryd** [comment]
Styrs via properties-filerna nu. Jag har deployat på test för externwebben och komin.

**Comment by olajoh1** [comment]
Kontakt på komin och Kontakta oss på malmo.se. ok. Kan deployas
