### ISSUE TITLE
Primary-news

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#244]
Bilder visas inte.

Dag i datum felar.

Länk till "Fler nyheter" saknas.

Lägg till... för redaktörerna saknas i redigeringsläge.

@martent

**Comment by hryd** [comment]
Dag i datum felar, åtgärdat.

**Comment by legander** [comment]
Timme i datum fela åtgärdat, _Fler nyheter_ och _lägg till_ länkar tillagda.

**Comment by legander** [comment]
Se över alternativet att använda Sitevisions standardmarkup. #246

**Comment by legander** [comment]
Har gjort en hybridlösning där vi blandar SV och prototypen. @martent 
http://komin.test.malmo.se/simon/Tester/SV-hybridnyheter.html
http://komin.test.malmo.se/simon/Tester/SV-hybridnyheter/Tester-med-rss.html

**Comment by olajoh1** [comment]
Bra, funkar bra i alla webbläsare.

**Comment by olajoh1** [comment]
När bild saknas läggs inte grå ruta ut längre

**Comment by legander** [comment]
Testa nu

**Comment by olajoh1** [comment]
Nu funkar inte bilderna alls, i alla fall inte på modulsidan

**Comment by legander** [comment]
Du måste rensa din cache

**Comment by legander** [comment]
Däremot så visas en liten grå kant om bilden inte är 102x102 som är bakgrundsbild på .img.
Tänkte att jag kunde flytta bakgrunden till bilden istället om img[src$=placeholder.png] eller vad säger du @martent ?

**Comment by olajoh1** [comment]
ok

**Comment by martent** [comment]
> Tänkte att jag kunde flytta bakgrunden till bilden istället om img[src$=placeholder.png]

Det borde funka. Då blir vi av med den grå bakgrunden i bilder med transparens också?

OT: placeholder.png är lite fult i sig måste jag erkänna, som att använda 1x1.gif, jag tror jag introducerade det för att det inte skulle falla ihop på höjden.

**Comment by legander** [comment]
Yes då slipper vi bakgrund på transparenta bilder.
Jo, det är lite halvfult.. Det var därför jag gjorde så att texten blev fullbredd istället för placeholderbild.

**Comment by legander** [comment]
Har lagt in cssändringen på test nu.

**Comment by martent** [comment]
:ok_hand:

**Comment by olajoh1** [comment]
ok
