### ISSUE TITLE
Secondary-news

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#245]
Modulen ska kunna hantera både arkiv/rss och vanlig text med länkar.

@martent

**Comment by legander** [comment]
Stöd för arkiv är tillagt.

**Comment by olajoh1** [comment]
Formateringarna slår inte igenom. (Gäller även fokusyta agera) Vad jag kan se har jag bytt mall.

https://komin.test.malmo.se/4.5530296c13e1773ee9e4b28.html

**Comment by legander** [comment]
Fokusyta - info fungerar bara för normalsida, vad det gäller nyheter så ska man kopiera in en layout från modulsidan.

**Comment by olajoh1** [comment]
Fokusyta agera menar du? Den borde fungera även på startsidor
