### ISSUE TITLE
Employee-news

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#246]
BIlder visas inte.

Datum och klockslag ska inte visas.

Länk till "Fler nyheter" saknas.

Lägg till... för redaktörerna saknas i redigeringsläge.

@martent

**Comment by martent** [comment]
> Länk till "Fler nyheter" saknas.
> Lägg till... för redaktörerna saknas i redigeringsläge.

Läggs till manuellt av redakörer.

**Comment by hryd** [comment]
Datum och klockslag är åtgärdad.

**Comment by legander** [comment]
Hur gör vi med Lägg till egen nyhet? Lägger redaktörerna själv dit en textmodul så kommer den att visas utanför cmsläget också.

**Comment by martent** [comment]
Jag ser inte någon anledning till att ha en sådan länk. SV är bara en visare av nyheter som även visas på Mina sidor, i RSS-läsare i Outlook etc. De som skriver nyheter och blogginlägg internt har koll på var man gör det.

**Comment by legander** [comment]
Se över alternativet att använda Sitevisions standardmarkup. #244

**Comment by legander** [comment]
Har gjort en hybridlösning där vi blandar SV och prototypen.
http://komin.test.malmo.se/simon/Tester/SV-hybridnyheter.html
http://komin.test.malmo.se/simon/Tester/SV-hybridnyheter/Tester-med-rss.html

**Comment by martent** [comment]
Ser prydligt ut! :clap: 

Vad händer när det inte finns någon bild till en nyhet?

**Comment by olajoh1** [comment]
ok
