### ISSUE TITLE
Dropdowns i sidhuvudet kapas

### ISSUE THREAD

**Issue by martent** [malmostad/sitevision_assets#247]
Valet "Mer" i sidhuvudet ska fälla ned en dropdown (se prototypen) men det gör den inte i åtminstone Chrome och FF. Menyn är Bootstrap 3.3 som JS-binds baserat på `data-`-attribut. Jag har misslyckats med att hitta felet. Kan det vara en konflikt med någon annan version av BS-kod som Sitevision servar?

@hryd @olajoh1

**Comment by martent** [comment]
Mårten kollar diff mellan miljöer

**Comment by martent** [comment]
Det är jQuery Timepicker Addon som ligger på rad 47 i `sitevision_plugins-min.js` som tar över click bindingen som bootstrap lägger på för sin dropdown. Jag har inte fördjupat mig i varför vi inte får konflikten på malmo.se. 

Det enklaste är nog att använda bootstraps JS API för att göra en re-bind genom att lägga till `$('.dropdown-toggle').dropdown()`. Förslagsvis i det inline-block som vi redan har i head som sätter `$('body').addClass('mf-v4 internal')`. 

Nackdelen skulle kunna vara att SV:s datapicker störs ut om den inte trivs med Bootstrap 3.

**Comment by legander** [comment]
Oklart vart timepickern används av SiteVision.. Lägger in om initieringen så får vi hålla ögonen öppna.

**Comment by martent** [comment]
Timepickern är på 7000 rader JS-kod så man hoppas att den används väl.

Funkar bra nu.
