### ISSUE TITLE
Link-list

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#248]
Bullets saknas.

Modulen ska kunna hantera både arkiv/rss och text med länkar

@martent

**Comment by legander** [comment]
Vanlig content punktlista läggs till såhär:
![dotlist](https://cloud.githubusercontent.com/assets/1597337/6825408/a7e6635a-d2fa-11e4-8e2c-3fe90199ecea.png)

Nyhetspunktlistan kan stödja text i listan men länkar följer ej med, se modulsidan.
