### ISSUE TITLE
kantlinje i top-meny

### ISSUE THREAD

**Issue by martent** [malmostad/sitevision_assets#249]
Minor issue. I smalare läge när top-menyn under hamburgare fälls ned saknas linje mellan Min sida och Min förvaltning. Jfr med prototypen. Antagligen konflikt med CSS i SV. Kollar ni?

@hryd @olajoh1

**Comment by legander** [comment]
Problemet är att `.malmo-masthead-our-organization #nav-our-organization>a`  är mer specifikt än `#malmo-masthead>nav ul li a` därför slår den selectorn igenom oavsett att den ligger längre upp i cssen. Vad man skulle kunna göra är att lägga till ex: `.masthead-main` på naven så att den blir `#malmo-masthead>nav.masthead-main ul li a` och då blir den mer specifik och vi blir av med transparenta bordern.

[Vår kommun](https://komin.test.malmo.se/Var-kommun)
```
 // rad 3920
.malmo-masthead-our-organization #nav-our-organization>a
.malmo-masthead-hrutan #nav-hrutan>a {
    border-color: transparent #fff;
}

// rad 3997
#malmo-masthead>nav ul li a{
    border-top-color: #b5b5b5;
}
```
[Min sida](https://webapps06.malmo.se/dashboard-test/login)
```
rad 3614
#malmo-masthead #nav-search-trigger>a,
#malmo-masthead #nav-menu-trigger>a,
#malmo-masthead>nav>ul>li>a {
    border: transparent solid;
}

// rad 4076
#malmo-masthead #nav-more ul.dropdown-menu>li>a {
  border-top-color: #b5b5b5;
}
```

**Comment by martent** [comment]
Tack @legander, funkade utmärkt.

Egentligen kanske du ska kolla och stänga :octocat: ...
