### ISSUE TITLE
Featured box

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#250]
Jag ska stämma av med Sven, men jag är hyggligt säker på att tillvägagångsättet är alltför komplicerat för våra redaktörer.

Fundera på om det finns en enklare lösning.

@martent

**Comment by martent** [comment]
I'm no expert, men jag tror det är den enklaste och stabilaste lösningen som gjorts här SV-mässigt. Det är oundvilkligt att man måste applicera en dekoration och att använda specifika stilmallar för text krävs alltid oavsett om det är webb, Word eller inDesign.

@legander och @hryd kan korrigera mig om.
