### ISSUE TITLE
Fix för snake menu

### ISSUE THREAD

**Issue by martent** [malmostad/sitevision_assets#251]
Kolumn-css är fortfarande buggig i flera webbläsare. Såg att `margin-bottom` flyttas över och lägger sig överst i nästa kolumn och förflyttar hela kolumnerna i IE. Verkar fixa sig om man ändrar följande rad till `padding-bottom`:

https://github.com/malmostad/sitevision_assets/blob/master/src/stylesheets/nav_page_overview.scss#L31

@hryd @olajoh1

**Comment by legander** [comment]
SHA: e430c61e2f36beb2e99eaf50fa464311b79c3be2

**Comment by martent** [comment]
Schysst.
