### ISSUE TITLE
dekorationer från malmo.se

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#252]
Följande ska vara med:
Huvudbild
Sekundärbild
Fokusyta - info 
Fokusyta - agera (knapp)
Tabell

**Comment by hryd** [comment]
Det är nu åtgärdat.

**Comment by olajoh1** [comment]
Jag får ingen av de fyra första att funka. 

https://komin.test.malmo.se/4.996cd3614c229e4d43d48da.html

**Comment by olajoh1** [comment]
Jag får ingen av de fyra första att funka. 

https://komin.test.malmo.se/4.996cd3614c229e4d43d48da.html

**Comment by olajoh1** [comment]
Testade precis på den modulsida ni har lagt upp då funkar samtliga utom Fokusyta - agera. Lägger till symbol men skapar aldrig grön knapp.

**Comment by hryd** [comment]
Den sida du länkade till är baserad på en gammal mall och därav funkar inte dekorationerna som de ska. Fokusyta - agera fungerar nu, en css-klass saknades.

**Comment by olajoh1** [comment]
Sven, vill du testa tabeller

**Comment by Svempan** [comment]
Jag vet inte vilket som är rätt men stilsättningen i tabell för "Rad/kolumnrubrik" är halvfet på malmo.se men inte på komin.test.malmo.se.
Se exempel:
http://www.malmo.se/4.4bef0e6a14c5b4a1bc92be68.html
http://komin.test.malmo.se/Sven-Test/Tabelltest.html

**Comment by legander** [comment]
Saknades lite svhacks, testa igen: http://komin.test.malmo.se/simon/Tester/Tabell
