### ISSUE TITLE
Snake-meny i IE11

### ISSUE THREAD

**Issue by martent** [malmostad/sitevision_assets#253]
I IE11 så blir snake-menyn knasig här:
https://komin.test.malmo.se/stadskontoret

Första kolumnen blir utan innehåll och sen bryts ett block mitt i. Lite dåligt balanserat innehåll men ändå dumt. Det verkar vara något annat som stör, jag la in koden SV renderar ut i prototypen och då renderar det som det ska i IE11:
http://malmostad.github.io/prototypes/internal/clean-banner/

En tom `<ul></ul>` kommer ut i sista blocket men det är inte det som stör här.

@olajoh1 @hryd

**Comment by legander** [comment]
0802685a9177b093441c08b6a25f5b078b44fbf9 gjorde susen. Se _/stadskontoret_

**Comment by martent** [comment]
Grymt!  :trophy:
