### ISSUE TITLE
Change: länktext i länken under menyn

### ISSUE THREAD

**Issue by martent** [malmostad/sitevision_assets#254]
Efter remiss med expertgranskning: Länken som går till snake-menyn, "Översikt – Stadskontoret" ska ändras till "Innehållsöversikt: Stadskontoret" med medveten radbrytning, se:

http://malmostad.github.io/prototypes/internal/clean/

@olajoh1 @legander

**Comment by hryd** [comment]
Åtgärdat, se exempel: https://komin.test.malmo.se/4.607666e14ba8b50b7ab308.html

**Comment by martent** [comment]
:sunny:
