### ISSUE TITLE
Postadress visas ej i kontaktrutan

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#256]
Exempel, funktionskontakten "Stadsarkivet"

https://malmo.se/editor/index.jsp?objectId=4.77b107c212e1f5a356a80001456

![stadsarkivet funktionskontakt](https://cloud.githubusercontent.com/assets/6176181/6898401/57d1fd4e-d6fa-11e4-8a76-8f869c6fff90.png)

**Comment by olajoh1** [comment]
Det verkar som att problemet uppstår då gatuadress saknas.

**Comment by hryd** [comment]
Jag uppdaterade kontaktrutan och deployade på test. Kan ni testa och återkoppla? @olajoh1 @Svempan

**Comment by olajoh1** [comment]
ok
