### ISSUE TITLE
Flytta layouterna till mallarna

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#258]
Diskussion

**Comment by olajoh1** [comment]
flytta till mall

**Comment by legander** [comment]
_Add content from template_ verkar inte riktigt fungera som vi trott. För att inte behöva skapa en helt ny sida så får man gå igenom stegen beskrivet i det första alternativet nedan.

Följande är tre olika sätt att skapa en startsida enligt den nya designen.
## Add content from template ##
1. Markera det befintliga innehåll man vill spara och klistra in det i innehållsytan __kontaktruta__.
2. Ta bort innehållsytan __mittenspalt__.
3. Högerklicka på innehållsytan kontaktruta och klicka sedan _Add content from template_ så får man en ny instans av mittenspalt.

## Modulsida ##
1. Gå till modulsidan och kopiera önskad nyhetslistning.
2. Klistra in på önskad sida.
3. Byt källa på nyhetsmodulen.

## Skapa ny sida ##
1. Skapa en helt ny sida på mallen startsida.
2. Kopiera över moduler från den gamla sidan.

**Comment by olajoh1** [comment]
Gäller allt ovan för befintliga sidor när man lägger layouterna i mallen startsida?

**Comment by legander** [comment]
Yes

**Comment by olajoh1** [comment]
bra
