### ISSUE TITLE
formatering av secondary.news

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#260]
Var går jag fel?

Jmf formateringen av de två secondary.news layouterna. Nedersta stämmer (kopia från modulsidan). Vad behöver jag göra för att få den översta att funka?

https://komin.test.malmo.se/editor/index.jsp?objectId=4.5530296c13e1773ee9e4b28

**Comment by legander** [comment]
Den övre nyhetsmodulen är tillagd via _add portlet_ dvs Sitevisions standardkonfigurerade nyhetsmodul. Modulerna som vi skapat och ligger på modulsidan innehåller ett skript och inte standardkonfigen därför ser de inte lika ut.

**Comment by olajoh1** [comment]
Vi  har en bugg. Om man tar bort samtliga RSS-flöden och sedan lägger till ett nytt försvinner skriptet.

**Comment by legander** [comment]
Det är så nyhetsmodulen fungerar. Man måste se till att lägga till önska källa innan man plockar bort den befintliga.
