### ISSUE TITLE
JS-bugg i Kontaktruta

### ISSUE THREAD

**Issue by martent** [malmostad/sitevision_assets#261]
Såg precis att vi har en bugg i Javascriptet för Kontaktrutan som visar sig när något annat formulärfält  ändras på en sida.

På raden:
https://github.com/malmostad/sitevision_assets/blob/master/src/javascripts/contact_us.coffee#L27
sätts en change-lyssnare på `$(document.body)` som sedan tillämpas på `$chooseDistrict.find("select")`. Det buggar ur när man ändrar värdet i ett annat formulärfält på en sida, `val()` på `$chooseDistrict.find("select")` hämtas men det senare är `undefined`.

Går att se på te.x. login-sidan på malmo.se prod när login-fälten ändras (vid blur).

Funkar det att ändra till `$(document.body)` till något mer avgränsat som ändå finns i DOM:en vid sidladdning? Eller att lägga på en check om objekten finns innan man kollar properties på dem (kan vara på fler ställen i samma skript)

cc: @legander

**Comment by legander** [comment]
Har deployat en fix på test 553d93eb80868ab42682c908ae472286b62d6390. Jag har testat och vad jag kan se så fungerar det ok, testa ni också.

**Comment by martent** [comment]
Funkar bra på www-test. Propagera ut i miljöerna.

**Comment by martent** [comment]
Funkar fint!
