### ISSUE TITLE
Stilsättning av moduler

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#262]
Nedanstående moduler i malmo.se ska även stilsättas på samma vis för Komin.

 
 Stilsättning av modul: webbananmälan  #161   

 Stilsättning av modul: e-postformulär  #162   

 Stilsättning av modul: fildelning  #163   

 Stilsättning av modul: enkätmodul  #164   

 Stilsättning av modul: Evenemangskalendern  #165 

@Svempan @martent

**Comment by legander** [comment]
Stilsättningen för externwebben matchar inte lika bra för komin. Säkra upp för komin också.

**Comment by legander** [comment]
http://komin.test.malmo.se/simon/Tester.html

**Comment by olajoh1** [comment]
Kalendern - kolla med Nina

**Comment by Svempan** [comment]
Jag kan inte testa med mobilen men annars verkar det funka.

**Comment by olajoh1** [comment]
Funkar det med mobil för dig Mårten?

**Comment by martent** [comment]
Jag kommer inte åt den.

**Comment by olajoh1** [comment]
Kan du testa på mobil Sven.

**Comment by olajoh1** [comment]
Sven skapar en testsida

**Comment by Svempan** [comment]
Finns redan: http://komin.test.malmo.se/simon/Tester.html

**Comment by olajoh1** [comment]
ingen av sidorna är responsiva

**Comment by olajoh1** [comment]
ok
