### ISSUE TITLE
Stilsättning agera-knapp i box

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#263]
Är lite stor, jmf malmo.se? Saknar också space till vänster om knappen.

https://komin.test.malmo.se/Arbetsfalt-verksamheter/IT.html

Kontrollera också bilden som är en sekundärbild. Den flödar inte höger i boxen, i desktop.

@hryd  @martent

**Comment by legander** [comment]
Den övre boxen är skapad på fel sätt, se den jag skapade precis under. https://komin.test.malmo.se/Arbetsfalt-verksamheter/IT.html

Fokusyta-agera är lika stor som på prototypen.

**Comment by olajoh1** [comment]
Mårten?

**Comment by martent** [comment]
Det är korrekt. Det är du som har så låg upplösning på din stora skärm så allt ser jättestort ut.

**Comment by olajoh1** [comment]
Felet gäller malmo.se :-)

http://malmo.se/Kultur--fritid/Besoka-Malmo.html

**Comment by martent** [comment]
Felet på malmo.se består alltså i att serifen slår igenom. Det har varit sans-serif tidigare.

**Comment by olajoh1** [comment]
Simon, på vilket sätt var boxen skapad på fel sätt?
