### ISSUE TITLE
Ny widget: Snabbval

### ISSUE THREAD

**Issue by martent** [malmostad/sitevision_assets#264]
Jag har gjort en design på Snabbvals-widgeten:
http://malmostad.github.io/prototypes/internal/clean-banner/

@olajoh1: Kolla

@hryd, @legander:  Koden är idealiserad så ni får göra en re-implementation i SV. Här är css:en som används i prototypen:
https://github.com/malmostad/prototypes/blob/gh-pages/_sass/internal-start.scss#L157-L196
Vänta dock tills @olajoh1 har okeyat.

**Comment by olajoh1** [comment]
ok, kör

**Comment by legander** [comment]
http://komin.test.malmo.se/simon/Tester/Snabbval

**Comment by olajoh1** [comment]
ok, hur bygger jag?

**Comment by legander** [comment]
![snabbval](https://cloud.githubusercontent.com/assets/1597337/7082916/65c687f8-df5b-11e4-9229-bd1b7fdfe658.jpg)

**Comment by martent** [comment]
:school:

**Comment by olajoh1** [comment]
Sven, ok?

**Comment by martent** [comment]
Sven säger ok
