### ISSUE TITLE
Scriptningen

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#266]
I den scriptning som har gjorts har innehållet i högerspalterna (ej banners) flyttats till innehållsytan Mittenspalt. Visas under tidigare innehåll i Mittenspalt.

Är det möjligt att:
* lägga innehållet från högerspalt i en egen innehållsyta under Mittenspalt (för senare bortscriptning)? 
* Göra en röd ram kring de moduler som kommer från högerspalten (oavsett om de ligger i mittenspalt eller i egen innehållsyta)?

Vilka är konsekvensera för resp. alternativ ovan avseende ekonomi, tid och risk? Måste SV blandas in?

@legander @martent @Svempan

**Comment by martent** [comment]
Kanske en dum fråga, men är det inte enklare och ger samma resultat om man inte alls scriptar innehållet i ytan i högerspalten men lägga en röd ram kring det och css-placerar det i botten?

**Comment by legander** [comment]
På dev snurrar vi ingång en backup från komin och kör skriptningen utan högerspaltdelen.

**Comment by martent** [comment]
Beställer du det Sven samtidigt som du avbeställer SV 4.0?

**Comment by Svempan** [comment]
Ola, sätter denna på dig. Skriptningen är väl inte gjord än?

**Comment by olajoh1** [comment]
I dev ligger banners kvar och info som ligger i kabinhaken för högerspalt är inte inramade med röd ram och text.

**Comment by hryd** [comment]
Scriptet är bara kört på en delgren som är under följande URL: https://www.dev.malmo.se/4.28e0421914cfbd9da273403d.html
