### ISSUE TITLE
White-space mellan layouter

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#267]
White-space mellan olika layouter varierar, exempel

https://komin.test.malmo.se/4.5530296c13e1773ee9e4b28.html

@martent

**Comment by martent** [comment]
Listan "Har du frågor?" avslutas med en hård radbrytning följt av en tom paragraf. Det är en SV-grej och skapar whitespace efter sig var SV:S textmodul än ligger. Ta bort tomma element sist i textmodulen @olajoh1.

Följande låter jag låter jag @legander och @hryd titta på först:

* Boxen "Nytt & viktigt" har 2em under sig som inte ger avtryck. Ev. är det "more" som behöver eller huvudboxen som behöver en clearfix eller borttagen float eller liknande.
* Dekorationen "more" behöver ev. nån 
* Boxen "Tycker du det är svårt med HRutan?" buggar ur lite. Rubrikarden är inte 100%.
* Det stora avståndet innan snakemenyn i desktop beror på att det är flera nested `sections` i SV vilket dubblerar whitespace.

Ni är fria att rocka loss som ni vill för att få en jämn whitespace under varje dekorationsblock. Jag blev tvungen att sätta en negativ margin-top på nått element i prototypen, det kan behöv nollas i SV-koden som ger en lite annan markup.

**Comment by olajoh1** [comment]
Kika även på nedan. Notera "Fler.." och White space.

https://komin.test.malmo.se/Var-kommun

**Comment by martent** [comment]
Detta justeras i sitevisionkoden som skiljer sig helt från den vi slutligen gjorde i prototypen för denna sidtyp. Jag började med dumpad kod från SV även i prototypen, men du ville att vi i prototypen skulle skap en målbild som sen lösningen i SV skulle efterlikna så bra som möjligt med hjälp av SV-tweaks och manuella handgrepp. 

@legander och @hryd håller på att jobba med SV-tweaks.

**Comment by legander** [comment]
https://komin.test.malmo.se/4.5530296c13e1773ee9e4b28.html 
Här ligger det en tom p-tagg under listan. 

https://komin.test.malmo.se/Var-kommun
Här är den första "Fler.."-länken korrekt skapad men den har manuellt tilldagd float-right, därför blir det problem.
Resterande "Fler.."-länkar på denna sida är fel tillagda därför saknar de rätt typografi. De har också manuellt tillagda floats.

Det är bäst om man kopierar in layouten "Fler nyheter" från modulsidan alternativt skapa en layout applicera dekorationsmallen "Fler nyheter" och lägg till en länk.

**Comment by martent** [comment]
Det faller med andra ord under "manuella handgrepp" som nämns ovan, och inte SV-tweaks.

:school:

**Comment by olajoh1** [comment]
ok
