### ISSUE TITLE
Byte av RSS-flöde för evenemang i sidfoten

### ISSUE THREAD

**Issue by Svempan** [malmostad/sitevision_assets#269]
Vi har ett flöde i sidfoten på malmo.se under "Händer idag i Malmö" på malmo.se. Är osäker på om det är RSS. Tror att det var VIsit som tog fram detta tillsammans med er. Nu har vi bytt kalender till:
http://evenemang.malmo.se/sv/evenemang/start
Alltså vill vi gärna att flödet hämtas därifrån och att länkarna går dit.
Hur gör vi för att åstadkomma detta?
@legander @olajoh1 @martent

**Comment by martent** [comment]
@Svempan Vi kollade på den med CGI men det är lite oklart vilket RSS-flödet det är. Kan du ta fram den exakta adressen till RSS-flödet så att inte @legander och @hryd gör en implementation mot ett flödet som har en annan XML-struktur.

**Comment by Svempan** [comment]
Har skrivit till Visit. Inväntar svar.

**Comment by Svempan** [comment]
Visit har skickat en ny adress nu:
http://evenemang.malmo.se/sv/evenemanget/rss

**Comment by Svempan** [comment]
Visit har fimpat det gamla RSS-flödet så nu funkar inte sidfoten längre. Kan vi ersätta med det nya ganska snabbt?

**Comment by martent** [comment]
moget gjort :boom:

**Comment by hryd** [comment]
Nu är flödet uppdaterat!

**Comment by Svempan** [comment]
Ser ut att funka. :-)
