### ISSUE TITLE
Läs mer/fakta ruta

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#271]
Saknar dekoration

@legander

**Comment by olajoh1** [comment]
Kan jag uppmana redaktörerna att använda samma dekoration i dagens mallar och att denna sedan följer med vid mallbytet?

Svara gärna på denna fråga så snabbt som möjligt

**Comment by hryd** [comment]
Nej, den gamla dekorationens styling finns inte kvar i nya local assets. Även så tas dekorationer bort i mallbytesscriptet.

**Comment by olajoh1** [comment]
ok
