### ISSUE TITLE
Synpunktshantering

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#272]
Diskutera uppdatering enligt Stockholm.se

**Comment by magnivar** [comment]
@martent Status på detta?

**Comment by martent** [comment]
Jag har inte varit med i diskussionerna kring detta.

Är det konceptdiskussion som är fokus just nu eller ett genomförande. I senare fallet är det ett uppdrag som får specas till Bouvet.

**Comment by magnivar** [comment]
@martent Mårten tar denna enligt olajoh1s instruktioner.

**Comment by olajoh1** [comment]
Mårten återkommer kommer med förslag.

**Comment by martent** [comment]
Modifierad lösning baserad på stockholm.se finns nu längst ned på prototyp-sidorna för malmo.se, t.ex.:
http://malmostad.github.io/prototypes/external/body-copy-18/

**Comment by martent** [comment]
## Implementationsinstruktioner

Browserkoden behöver antagligen tweakas när funktionen förändras i SV. Här är diffen mot föregående lösning i prototypen där man eventuellt kan använda valda delar av HTML/CSS/JS:
https://github.com/malmostad/prototypes/commit/7c8c1ce162748c969f2267fc129a24ae304a7249

**Comment by olajoh1** [comment]
ok. Vill du komplettera texten nedan med ett "Tack".

Du har nu hjälpt oss att förbättra malmo.se

**Comment by martent** [comment]
Tog bort "Tack" för att Stockholm inte hade det :) TIllagt igen.

@magnivar, ställer denna på sig så att du kan planera när ändringen ska införas i SV.

**Comment by olajoh1** [comment]
Magnus denna är viktig att få ut snabbt. Jag har därför ändrat milstone 4.7. 

Observera att den ska finnas på både Komin och malmo.se. Komin har högst prioritet.

**Comment by magnivar** [comment]
Lägger den i 4.8 för att 4.7 redan är avropat

**Comment by tomasrobertsson** [comment]
Sorry, klickade på fel knapp, Återställde.

**Comment by EllinorHallett** [comment]
@magnivar 
Vilka delar är färdiga med detta ärende? Prototypen som Mårtan byggde, är det denna som ska in på externwebben eller ska vi titta på en ny lösning? 
Jag har mailat SiteVision om de har någon färdig modul för detta med fick svar att de inte hade detta men fick ett förslag på att man eventuellt kan lösa det med en vanlig Frågeformulärsmodul: 

[https://help.sitevision.se/SiteVision_4_0/dbformHelp.html](https://help.sitevision.se/SiteVision_4_0/dbformHelp.html)

Jag ska kolla vidare på detta me vill ha svar angående om vi ska använda det Mårten har gjort innan jag lägger mer tid på detta.

**Comment by magnivar** [comment]
Vi ska titta på ny egen SV-lösning lösning.

**Comment by EllinorHallett** [comment]
Okej, det finns inte SiteVision standardlösning för just frågan "Hjälpte denna sida dig?" det finns enbart en kommentarsmodul.
Eventuellt kan vi som sagt använde frågeformulärsmodulen men tyvärr tror jag att man enbart kan fylla i epostadresser manuellt och inte via metadata. Jag har ställt frågan till SiteVision så får vi se om de har någon bra lösning på problemet.

**Comment by olajoh1** [comment]
När det gäller krav på funktionen ux-mässigt så ska den fungera exakt som på http://malmostad.github.io/prototypes/external/body-copy-18/

Övrigt
* ska bara visas på sidor som använder normalsidesmallen
* ska kunna aktiveras på enskilda sidor
* ska kunna ärvas
* mottagande epostadress ska kunna vara flera. Vi vill få en kopia på varje svar till en central epostadress men samtidigt ska inkomna synpunkter postas direkt till den redaktör de berör

**Comment by EllinorHallett** [comment]
Enligt ovannämnda krav finns det tyvärr ingen SiteVision standardfunktion för detta.
Det går inte heller att anpassa formulärsmodulen då denna måste ha statiska e-postadresser = man kan inte byta  på olika sidor utan det blir samma överallt. VIll man kunna ha olika epostadresser på olika sidor måste vi bygga något eget, så mån fråga är då varför vi inte kan använda den som finns  här: [http://malmostad.github.io/prototypes/external/body-copy-18/](http://malmostad.github.io/prototypes/external/body-copy-18/)

**Comment by badwiz** [comment]
Vi har kikat på detta och har en lösning som involverar modulen "Betyg" och ett e-postformulär för inskickande av synpunkt. Vi har snabbt sett att detta kan göras inom 16 timmar.

**Comment by olajoh1** [comment]
Bra. Har ni byggt en sådan lösning tidigare och som vi kan ta del av?

**Comment by badwiz** [comment]
Förtydligande: Glöm inte att få med URL från sidan som synpunkten handlar om!!

**Comment by badwiz** [comment]
Bonus: Kika på att skicka in detta som ett event i Google Analytics på Malmö stad.

**Comment by badwiz** [comment]
Länk till funktion som gjorts åt Hässleholms kommun, endast dold ännu. De har ej valt att använda denna än

http://www.hassleholm.se/4.2295e6d915ee5a5496dd529.html

**Comment by magnivar** [comment]
@olajoh1 kolla på detta och kommentera.

**Comment by henrikekelof** [comment]
@olajoh1 @magnivar Det finns inga inställningar för epost på serverobjektet. Vi kommer inte att kunna skicka epost till någon utan det. Har ni en SMTP-server som ni vill använda där?

![screen shot 2018-01-17 at 14 20 58](https://user-images.githubusercontent.com/186166/35044737-c6d0888c-fb91-11e7-87c0-17c7b1463146.png)

**Comment by henrikekelof** [comment]
@olajoh1 @magnivar 
Ett första utkast finns för påseende här:
https://www.test.malmo.se/Teststruktur/Henrik/Synpunktshantering.html

+ Sparar Ja/Nej som betyg på sidan med standardfunktionalitet
+ Metadata för att visa / dölja formuläret
- Kan ej skicka mail

Det finns möjlighet att göra en särskild adminsida där man kan lista alla sidor som har fått svar och visa hur bra betyg de fått.

Vilka metadatafält ska användas för mail? Det finns många existerande för kontakt o.s.v. på sidor. Vilket eller vilka vill ni att mail ska gå till?

**Comment by olajoh1** [comment]
Vad betyder "Kan ej skicka mail"?

**Comment by henrikekelof** [comment]
@olajoh1 Se min kommentar ovanför. Det finns inte email inställt i SiteVision, så det går inte att skicka mail därifrån. Mitt första utkast gör därför det den ska utom att skicka ett mail till någon.

**Comment by magnivar** [comment]
Alla SV-servrar ska skicka via relay.malmo.se, de har inga egna mailkonton.

**Comment by henrikekelof** [comment]
@magnivar Ser att du eller någon fixat SMTP-inställningarna, och jag har testat att det funkar. Det var bara det som saknades. Tackar!

**Comment by henrikekelof** [comment]
@olajoh1 @magnivar Det jag behöver veta nu är hur ni vill styra vem som ska få email. Vilket/vilka metadatafält med adresser/användare vill ni att mail ska gå till?

**Comment by henrikekelof** [comment]
@olajoh1 @magnivar Så här kommer ett skickat mail se ut när man får det. Kommentera gärna på om det är något ni vill justera. Efter uppgradering till SiteVision 4.3 så kommer det vara möjligt att skicka mail som HTML, men så länge ni ligger på 4.2.x så är det bara plain text som är tillgängligt. 

![screen shot 2018-01-18 at 09 22 00](https://user-images.githubusercontent.com/186166/35087600-14353466-fc31-11e7-9355-2554c4fff539.png)

**Comment by olajoh1** [comment]
*Mail ska gå till minst två mailadresser, alltid till en central utpekad adress samt till en eller flera redaktörer. Uppgifter i befintliga metadata kan inte användas utan nya meta måste sättas upp.
*Adresserna ska vara möjliga att ärva tillsammans med aktiveringen av modulen.
* Admingränssnitt, ja.

**Comment by henrikekelof** [comment]
@olajoh1 Jättebra. Den centrala adressen - vill ni ha den som ett metadata med arv, eller ska jag sätta den direkt i scriptmodulen? Det förstnämnda är bra om ni vill kunna ändra den och kanske bryta arvet. Sätter vi den i scriptmodulen så blir den mer dold och går inte att ändra om man inte ändrar i mallen.

**Comment by olajoh1** [comment]
Vi sätter den som ett metadata med arv.

**Comment by henrikekelof** [comment]
Nu finns detta klart för test på alla sidor med mallen Normalsida.

- Metadata sätts på huset för globala adressen
- Metadata för att visa eller inte visa synpunktsformuläret
- Metadata för att lägga till fler mottagare på specifika sidor

Alla metadata ärvs.

**Comment by henrikekelof** [comment]
Jag ser att någon redan har gjort ungefär samma sak, för det finns befintlig metadata och ett befintligt formulär. Därför blir det lite kladdigt och möjligen förvirrande med många metadata i sidorna som heter Synpunkt-någonting men som fungerar för olika formulär. Ska det gamla formuläret och dess metadata tas bort ur mallarna? Används det? Det finns även i produktion (se bilder)

![screen shot 2018-01-19 at 13 22 51](https://user-images.githubusercontent.com/186166/35151236-e04569da-fd1d-11e7-98bb-da34f797da1a.png)

![screen shot 2018-01-19 at 13 20 01](https://user-images.githubusercontent.com/186166/35151235-e0267bce-fd1d-11e7-87e5-6e58687c11c3.png)

![screen shot 2018-01-19 at 13 28 29](https://user-images.githubusercontent.com/186166/35151237-e0607d4c-fd1d-11e7-9c02-a2b6b6c97999.png)

**Comment by henrikekelof** [comment]
Här finns en sida som listar alla sidor som har fått minst ett svar (ja eller nej):
https://www.test.malmo.se/edit/4.719e72ae160e0f98c259a942

**Comment by henrikekelof** [comment]
@olajoh1 @magnivar Bollar över denna till er nu för testning. Läs gärna mina tre kommentarer innan först.

**Comment by olajoh1** [comment]
Du kan ta bort gamla metadata

**Comment by henrikekelof** [comment]
👍
En sak till: Jag är inte helt bekant med hur ni har satt upp era behörigheter, så just nu visas all "min" metadata för alla. Vill ni ha det annorlunda så får ni gärna ange vem som ska se vad.

**Comment by olajoh1** [comment]
Exempelsida:
https://www.test.malmo.se/Social---familjefragor/Hemloshet.html

Om jag kryssa i ärv värde ändras Ja till Nej. 
Om jag lägger till mottagare och kryssa i arv så tas mottagaren bort.
Om jag publicerar med Ja men utan arv visas ändå modulen på underliggande sida.

**Comment by henrikekelof** [comment]
> Om jag kryssa i ärv värde ändras Ja till Nej.

Jag har satt defaultvärdet till Nej för om den ska visas eller ej. Vill ni hellre ha Ja?

> Om jag lägger till mottagare och kryssa i arv så tas mottagaren bort.

Mottagare (sidspecifik) har inget inkommande värde om den inte ligger under en sida som har värdet. Man får sätta det på en sida och så ärvs det ner till dess undersidor.

> Om jag publicerar med Ja men utan arv visas ändå modulen på underliggande sida.

På huset finns Mottagare (global) som alltid får meddelanden från alla sidor.

Vid metadataarv kan du inte i nya gränssnittet förhindra att värdet ärvs nedåt som man kunde i gamla. Vill du inte ha på underliggande måste du gå in på varje och ta bort "Ärv värde". Alternativt kan vi sätta metadatat till "Ärv inte värde automatiskt" så får man gå in på undersidor och välja om man vill ärva eller inte.

**Comment by olajoh1** [comment]
Vill du ersätta andra meningen under synpunktsformuläret med följande text, som länkas till länken nedan.

"Om du vill ha svar på en fråga hittar du kontaktuppgifter här."

http://malmo.se/Kontakta-Malmo-stad.html

**Comment by olajoh1** [comment]
Är det möjlig att skriva ner samtliga svar i en excelfil som läggs på lämpligt ställe?

**Comment by henrikekelof** [comment]
Text + länk fixat:
![screen shot 2018-01-25 at 11 09 55](https://user-images.githubusercontent.com/186166/35382699-518bb8fa-01c0-11e8-857f-9aea55d2b573.png)

**Comment by olajoh1** [comment]
Första meningen skulle vara kvar. Nu ersattes både första och andra meningen.

**Comment by henrikekelof** [comment]
Att skriva till en fil går _troligen_ att lösa. Det finns utmaningar kring behörighet att skriva i filarkivet, men det borde gå att få till. Jag har svårt att säga någon exakt tidsåtgång, men gissar 4-8 timmar eller i värsta fall något mer. Vill du att jag gör ett försök att få till en lösning? Ingen garanti alltså att det lyckas, men jag tror att det ska gå :)

**Comment by henrikekelof** [comment]
Jag fattade fel på textändringen. Bättre så här?
![screen shot 2018-01-25 at 11 19 47](https://user-images.githubusercontent.com/186166/35383137-b4f6ab06-01c1-11e8-8ca8-4dcfea27a779.png)

**Comment by olajoh1** [comment]
Mycket bättre :-)

**Comment by henrikekelof** [comment]
@olajoh1 Vill du att jag försöker göra ett försök att skriva meddelanden till en fil? Eller ska vi produktionssätta som den är nu?

**Comment by olajoh1** [comment]
Det är okej att du lägger 4-8 timmar på att skapa en excelfil enligt ovan

**Comment by henrikekelof** [comment]
@olajoh1 

Jag har lagt ett par timmar nu och det ser lovande ut. Måste skriva koden lite bättre och få in det i meddelandehanteringen, men jag kommer absolut att kunna hålla mig inom 8 timmar. 

Det jag måste göra är att skapa en användare i SiteVision som får skrivbehörighet på en specifik fil i filarkivet (CSV). Jag kommer sen att anropa en särskild modul som med hjälp av den användaren skriver meddelandet i filen. Anv.namn och lösen kommer aldrig att synas ut i sidan utan skickas bara på serversidan.

Ni kommer sen att kunna gå till filarkivet och hämta upp filen, alternativ gör vi en adminsida som läser filen och presenterar alla meddelanden i SiteVision.

**Comment by olajoh1** [comment]
Bra. Osäker på vad du menar med "presenterar alla meddelanden i SiteVision"  Vad jag behöver är att kunna arbeta vidare med datan i excel.

**Comment by henrikekelof** [comment]
Ja, du kommer få en CSV i filarkivet som du kan öppna i Excel. Jag kan ganska enkelt göra en snygg sida i SiteVision också som visar innehållet från filen och ger dig en nedladdningslänk, om du bara vill kunna surfa in och kolla ibland.

**Comment by olajoh1** [comment]
Kan du göra det utan att addera alltför mycket tid så absolut ja.

**Comment by henrikekelof** [comment]
Det är den enklaste biten, så absolut :)

**Comment by henrikekelof** [comment]
@olajoh1 
Jag har en fungerande version i test nu:
http://www.test.malmo.se/4.719e72ae160e0f98c2575cc8.html

CSV-filen ligger här:
https://www.test.malmo.se/edit/2.33aee30d103b8f1591680000/file/19.df5bd2416127d1353a220dc

Sida som listar alla kommentarer finns här:
https://www.test.malmo.se/edit/4.df5bd2416127d1353a221b2

Jag fick problem på test då certifikatet inte är giltigt där, så jag var tvungen att ställa om så att den accepterar http för att kunna testa. Det ska inte vara ett problem i prod-miljö, men just nu på test måste man skicka kommentaren från en http-sida för att den ska sparas.

Värt att notera:
- Jag skapar en användare med skrivrättighet på filen i filarkivet och använder den användaren i bakgrunden för att göra skrivningen till fil. Det här är väldigt säkert då inget användarnamn/lösenord exponeras för besökaren, men krävs för att ha rätt att skriva i filen.
- Filen i filarkivet är inställd på att inte visas i sökningar, men den måste vara publik för att det ska fungera. En extern besökare kan alltså teoretiskt gissa adressen till filen och läsa dess innehåll. Det här kan jag inte komma runt. Det man får förlita sig på här är snarast security through obscurity, då den som gissar filnamnet måste gissa rätt på SiteVisions ID (18.df5bd2416127d1353a220de).

Tankar kring detta @magnivar ?

**Comment by olajoh1** [comment]
Vill du lägga till två fält/kolumner:

datum (då synpunkten lämnats)
ja/nej


URL:en får gärna tvättas så att den blir enklare att läsa:

http://www.malmo.se - kan tas bort
%2 - ersätta med / etc

**Comment by henrikekelof** [comment]
@olajoh1 Har fixat datum och snyggare adress. Ja/Nej är överflödigt då det endast är på Nej som man får möjlighet att skriva kommentar, så alla kommer vara Nej :)

**Comment by henrikekelof** [comment]
Sen har du en ladda-ner-knapp också på sammanställningssidan nu.

**Comment by olajoh1** [comment]
Nej, ja/nej är inte överflödigt. Vi vill veta både hur mycket tjänsten används och få statistik på hur inställningen förändras över tid till sidor/grupper av sidor.

**Comment by henrikekelof** [comment]
OK. Jag har lagt till Ja/Nej i en separat tabell. Kommentarerna lämnas bara på Nej, och listan över Ja/Nej är istället en sammanställning med summering. Det är två olika typer av hämtningar.

https://www.test.malmo.se/4.df5bd2416127d1353a221b2.html

**Comment by olajoh1** [comment]
Behöver ja/nej i csv-filen också

**Comment by henrikekelof** [comment]
CSV-filen skrivs alltså bara för kommentarer, d.v.s då man redan har svarat nej och sen skickar in en kommentar. Har du kikat på de två tabellerna idag så att du ser hur datat ser ut? Jag kan fixa så att du kan ladda ner tabellen med ja-nej-statistik som CSV. Det kommer att bli en separat fil som genereras från tabellen, och den kommer inte att ligga i filarkivet.

**Comment by olajoh1** [comment]
Om du fixar så ja/nej-statistiken inkl rubrik och url så är vi nog i mål.

**Comment by henrikekelof** [comment]
@olajoh1 Jag har lagt till en nedladdningsknapp nu även på Ja/Nej, kika på den:
https://www.test.malmo.se/4.df5bd2416127d1353a221b2.html

**Comment by olajoh1** [comment]
ok, redo för lansering

**Comment by henrikekelof** [comment]
👍

Jag fixar idag eller i morgon och kommenterar här när det är gjort.

**Comment by henrikekelof** [comment]
Nu finns synpunktshanteringen i produktion. För er att göra:
- Lägg till epostadress för "Mottagare av synpunkt på sidan (global)" på huset 
- Lägg till önskade kontakter för "Mottagare av synpunkt på sidan (sidspecifik)" på undersidor
- Aktivera synpunktsformuläret med "Visa synpunktsformulär" på sidor där ni vill visa det

Sammanställningar kommer ni kunna se här:
http://malmo.se/4.5e3289201615f98bc3b2831b.html

Filen med kommentarer kan laddas ner direkt därifrån eller från filarkivet http://malmo.se/download/18.5e3289201615f98bc3b284b9/1517911903812/alla-synpunkter.csv

**Comment by olajoh1** [comment]
Tack!
