### ISSUE TITLE
Varna användarna för kakor

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#273]
Föreslå lösning
@Svempan

**Comment by martent** [comment]
Ligger i test nu för alla externa tjänster, det är alltså ingen SV-grej utan ligger i Global Assets.

Samtycke sparas i fem år och gäller per webbläsare+användare. Tar användaren bort sina kakor informeras hen igen.

Inforutan sätter av det utrymme den behöver under sidfoten även om den är själv är sticky. Om en ändrar bredden på sin webbläsare kan den dock lägga sig lite ovanför den undre sidfoten eller ge ett litet glapp. Jag har valt att inte justera den estetiska defekt eftersom det skulle dra lite extra kraft av webbläsaren att lyssna av dessa ändringar.

Detta ligger i samma release som Universal Analytics.

**Comment by olajoh1** [comment]
OK, även fem år. Vi kan lägga ut detta så fort vi har en uppdaterad text på http://malmo.se/om-cookies. För att den ska uppfylla PTS krav måste varje cookie och hur länge den sätts beskrivas. Vill du hjälpa oss med det? 

PTS krav:
Den information du lämnar dina besökare om användningen av kakor bör innehålla uppgifter om vad de olika kakorna heter, till vilket domännamn de hör, vilka data som lagras i kakorna och hur länge de sparas i besökarens webbläsare. Det bör också tydligt framgå vilket syfte kakorna fyller på din webbplats liksom om informationen kommer från eller lämnas ut till tredje part.

Exempel på tillämpning:
https://www.uppsala.se/lankar-i-sidfoten/om-webbplatsen/#kakor
http://www.regeringen.se/sb/d/15003/a/18581
http://www.skatteverket.se/omoss/omskatteverket/omwebbplatsen/omkakorcookies.4.14c8822103addae55580003.html

@Svempan

**Comment by martent** [comment]
Mail med info skickad till @olajoh1

**Comment by olajoh1** [comment]
Sven avvaktar info från SV

**Comment by Svempan** [comment]
Inväntar svar ifrån SV AB vilka kakor SV genererar. De gör en inventering nu.

**Comment by Svempan** [comment]
@martent Lägger du till detta i WAG:n sedan?

**Comment by martent** [comment]
Om du skriver ihop något så lägger jag in det. Jag vet inte vilka av PTS punkter ni valde ut att följa. Sätt över på mig sen så lägger jag in det.

**Comment by Svempan** [comment]
Text färdig, sida klar. För min del går det bra att produktionssätta kakvarningen.
http://www.malmo.se/kakor

**Comment by martent** [comment]
Ute i produktion.

**Comment by olajoh1** [comment]
Fick du till en eventtracking på knappen också?

**Comment by martent** [comment]
Eventet loggas som CookieConsent i de fall användaren explicit accepterar.

**Comment by martent** [comment]
Denna release innebär också att ni nu har Universal Analytics externt.

**Comment by olajoh1** [comment]
ok
