### ISSUE TITLE
Påverkansytan i smala enheter

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#275]
Text istället för bild.

**Comment by martent** [comment]
Lösningen blir att alltid visa bilden men att trunkera texten i h1:a med ellipsis. Här är diffen @hryd: 
https://github.com/malmostad/prototypes/commit/3b765804bf0823761bd51cd0f738ed2a87c7c14f

Så här ska det se ut
http://malmostad.github.io/prototypes/external/nav-page-4/

**Comment by hryd** [comment]
Uppdaterad. e22e2c273501dece73abc6f8ee7455b026ad5836

**Comment by hryd** [comment]
Har gått ut i produktion.

**Comment by martent** [comment]
På startsidan lägger sig bannern under sidhuvudet under 576px. Gäller inte på andra sidor där brödsmulorna finns. Detta har vi tyvärr missat under testning.

**Comment by hryd** [comment]
Det är på grund av dessa rader. https://github.com/malmostad/sitevision_assets/blob/master/src/stylesheets/nav_page_with_direct_links.scss#L6-8 
Jag tar bort det och deployar igen imorgon.

**Comment by martent** [comment]
Bra spottat. Det var antagligen till för att rycka upp sidan när bannern doldes tidigare.

**Comment by hryd** [comment]
Deployed.

**Comment by martent** [comment]
Funkar bra.

**Comment by olajoh1** [comment]
Får inte upp någon banner i min iphone 6

**Comment by martent** [comment]
Jag får, både i senaste Chrome och Safari i iOS 8.3.

Cachade SV-CSS:er?

**Comment by olajoh1** [comment]
ok
