### ISSUE TITLE
Dubbelexonering av bildnyheter

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#278]
Vilka möjligheter finns det att få bildnyheter att automatiskt försvinna ur ticketen där de visas om inga inställningar görs.

**Comment by legander** [comment]
Har kapat .img lådan helt nu @martent.

se http://komin.test.malmo.se/simon/Tester/SV-hybridnyheter.html @olajoh1

**Comment by legander** [comment]
Är inte riktigt med på vad du menar, är inga inställningar gjorda så visas inga bildnyheter.

**Comment by olajoh1** [comment]
Alltför tidskrävande att åtgärda.
