### ISSUE TITLE
Personbild i kontakt

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#283]
Skapa möjlighet att publicera personbild i kontaktrutorna på komin och malmo.se.

Mårten designar lösning.

@hryd

**Comment by martent** [comment]
@hryd, den REST-retur du får från Kontaktboken i test har nu profilbilds-data:

```json
{
  "catalog_id": "olajoh1",
  "id": 113,
  "first_name": "Ola",
  "last_name": "Johansson",
  "title": "Informationssekreterare",
  "email": "Ola.Johansson@malmo.se",
  "phone": "040-341149",
  "cell_phone": "0733-525310",
  "company": "102 Stadskontoret",
  "department": null,
  "room": "6094",
  "address": "August Palms plats 1",
  "zip_code": "211 52",
  "postal_town": "Malmö",
  "geo_position_x": 118943,
  "geo_position_y": 6163918,
  "created_at": "2012-05-04T13:26:01.000+02:00",
  "updated_at": "2015-04-22T09:37:00.000+02:00",
  "roles": ["Stadskontoret", "Kommunikationsarbete"],
  "skills": ["webbutveckling", "sökmotorer", "webbanalys", "siteseeker", "Google analytics", "e-utveckling", "malmo.se", "Komin"],
  "languages": ["engelska"],
  "avatars": {
    "xlarge": "//webapps06.malmo.se/avatars/olajoh1/xlarge.jpg",
    "large": "//webapps06.malmo.se/avatars/olajoh1/large.jpg",
    "large_quadrat": "//webapps06.malmo.se/avatars/olajoh1/large_quadrat.jpg",
    "medium": "//webapps06.malmo.se/avatars/olajoh1/medium.jpg",
    "medium_quadrat": "//webapps06.malmo.se/avatars/olajoh1/medium_quadrat.jpg",
    "small": "//webapps06.malmo.se/avatars/olajoh1/small.jpg",
    "small_quadrat": "//webapps06.malmo.se/avatars/olajoh1/small_quadrat.jpg",
    "thumb_quadrat": "//webapps06.malmo.se/avatars/olajoh1/thumb_quadrat.jpg",
    "tiny_quadrat": "//webapps06.malmo.se/avatars/olajoh1/tiny_quadrat.jpg",
    "mini_quadrat": "//webapps06.malmo.se/avatars/olajoh1/mini_quadrat.jpg"
  }
}
```
Vilken av storlekarna vi använder får designen som jag återkommer med avgöra.

**Comment by martent** [comment]
@ola, ser för övrigt i din data ovan att Mina sida fyller tre år om ett par dagar. :cake:

**Comment by martent** [comment]
Ska detta fungera på malmo.se krävs en brandväggsöppning till Kontaktbokens server, denna gången inte från maskin-till-maskin som när SV hämar kontaktboksdata utan för att användarens webbläsare ska komma åt Kontaktboken där bildern ligger. Det är en rätt stor sak.

Alternativt kan givetvis SV-portleten hämta ned bilder och cacha i SV så att webbläsaren får dem därifrån, men det blir en hel del data att spara. Överlåter till @hryd att kommentera lämpligheten i detta alternativ.

**Comment by martent** [comment]
Finns nu i prototypen på:
http://malmostad.github.io/prototypes/internal/clean/

Lösningen är gjord med responsiva bilder vilket innebär att en webbläsaren som stöder detta väljer bildstorlek beroende på skärmdensitet, den satta layouten som påverkar bildbredden på sidan, bandbredd, användarpreferenser eller vad webbläsaren valt att stödja. Fallback är 180px-bredd-bilden.

@hryd Du får url:erna till de olika bildformaten i API-responsen, se ovan. Markupen finns på sidan.

**Comment by olajoh1** [comment]
Tveksam till storleken på bilden. Det vanliga på komin är att användaren visar namn, ev titel, tele och mailadress. Hur ser det ut med endast dessa uppgifter och hur ser det ut om man har två kontaktpersoner på en sida?

**Comment by martent** [comment]
Ola vill ha mindre bild.

**Comment by martent** [comment]
Nu är den liten i alla bredder. 

Jag vet inte om du har börjat implementera @hryd men det är en liten diff:
https://github.com/malmostad/prototypes/commit/37dfaf24e3ae745a1321b9253fc5affe1efc18b1

Över till @hryd för implementation.

**Comment by martent** [comment]
Jag ger nycklar till @hryd

**Comment by martent** [comment]
skickat till @hryd

**Comment by hryd** [comment]
Deployed i testmiljöerna. @Svempan @martent

**Comment by Svempan** [comment]
1. Jag kan tyvärr inte testa i mobilen. Min VPN funkar inte där. Men borde inte allt innehåll i kontaktrutan ligga under bilden i mobilt läge så det blir uppdelat över och under?
2. Bilden blir jättelik i Explorer 11.

**Comment by hryd** [comment]
1. Lösningen följer prototypen, förutom att personnamnet ligger precis ovanför bilden och inte i samma nivå som personbilden. Den nuvarande lösningen för kontaktrutan låter mig inte lösa detta på ett smidigt sätt, jag kan förklara vidare imorgon på ett möte. Här är prototypen: http://malmostad.github.io/prototypes/internal/clean/
2. Fixat nu!

**Comment by Svempan** [comment]
1. Men kolla vad som händer här i mobilt läge:
http://komin.test.malmo.se/Arbetsfalt-verksamheter/Inget-arbetsfalt.html
Min långa titel gör nog att det blir väldigt mycket luft till vänster om bilden.

**Comment by hryd** [comment]
Ja, det blir lite märkligt. Jag uppdaterade CSS:en med ett förslag på att bilden läggs under rubriken vid en viss bredd på webbläsaren, hur ser det ut? @Svempan

**Comment by Svempan** [comment]
Men det blev ju jättebra!

**Comment by hryd** [comment]
Kan du även testa för olika personer, med eventuellt ännu längre titlar? @Svempan

**Comment by Svempan** [comment]
Jag letar förtvivlat efter längre än "informationssekreterare". Återkommer.

**Comment by hryd** [comment]
Det uppstår egentligen bara problem om personers titlar är ett och samma ord och längre än t.ex. "Informationssekreterareloremips". Om titeln består av fler ord sker det ju en radbrytning. Det kanske är rimligt att anta att det är extremfall och att lösningen fungerar? @Svempan

**Comment by Svempan** [comment]
Överförmyndarhandläggare! Har lagt in det under mig på samma sida. Hon har dock ingen bild inlagd.

**Comment by Svempan** [comment]
I produktion i augusti.

**Comment by hryd** [comment]
Deployed. @Svempan
