### ISSUE TITLE
Inline webbvideo för startsidor

### ISSUE THREAD

**Issue by martent** [malmostad/sitevision_assets#284]
Bryter ut fallet för visning av video i portleten på SV:s startsidor från #274. Delar dock mycket av frågorna i nämnda ticket.

**Comment by martent** [comment]
## UI
Jag har lagt in design och kod i prototypen för malmo.se respektive Komin.

**Comment by martent** [comment]
## Kod
@hryd, här är en diff med kod som är ändrad eller tillagd där du kan hämta valda delar till portleten respektive sitevision assets. Det är tre filer som är intressanta för dig och beskrivs nedan.

https://github.com/malmostad/prototypes/compare/191dc71cf1791cc8500df3bca653c9264f1a7b6e...43d3da3976e92ee892ca2235448be2a2a52965cb

`video.coffee` är ny. Den hämtar hem BC-assets när användaren klickar på en tumnagel och initierar videon. Vi har en utestående fråga till @carlhaman här om man kan ge BC:s API videons ID för den film som ska spelas malmostad/sitevision_assets/issues/274#issuecomment-97117776

Jag har lagt in den variant som finns dokumenterad hos BC och VideoJS som initierar videon med ett en array med ett objekt för varje mediaformat och fulla url:er. Om det är så att du får ut alla mediaformat med url:er till filmerna i den request du gör för spellistan så kan du använda denna lösning och bara fylla på med de andra medaformaten (flash etc.).

Lite längre ned i diffen hittar du `_includes/movies.html` som visar ändringar från den markup som kommer ut nu. `<video>`-taggen med omslutande block är ny. I listan med videor är `<a>` borttaget förutom för KF. Istället ligger ett attribut och en class i `<li class="show-inline" data-video-id="4116313334001">` som lyssnaren i javascriptet ovan använder för att initiera videon. Använder du lösningen med att skicka in alla mediaformat kan du lägga in hela objektet som sträng:

```
data-video-id='[{"type":"video/mp4","src": "http://brightcove.vo.llnwd.net/v1/uds/pd/745456160001/201503/1629/745456160001_4144200317001_4144112584001.mp4"}]'
```
eller hålla det i en JS-variabel och associera med nått du lägger i attributet om det känns för magstarkt.

Längre ned finns `_sass/movies.scss` där du har de ändringar jag gjort i CSS:en för startside-spelningen. Generell stilsättning för videon för att få den i 16:9 responsivt ligger i Global Assets (i test för malmo.se och Komin) och stilsättning av element inuti videon kommer @carlhaman att lägga in i BC-admin.

**Comment by olajoh1** [comment]
Snyggt, bett Mikael kika också.

**Comment by olajoh1** [comment]
Micke nöjd också.

**Comment by martent** [comment]
@hryd: Det räckte att skicka in video-id för videon som ska visas så du behöver bara lägga till det i `data-video-id`-attributet. 

JS i prototypen är uppdaterad:
https://github.com/malmostad/prototypes/commit/52bb84a126859d044001bcc1ac78d14cfe9f03ea

**Comment by hryd** [comment]
Lade upp en första version på testmiljöerna. http://www.test.malmo.se/4.2697584314d2ed3fa91114cd.html
http://komin.test.malmo.se/4.682697fa14cba931c6e2a08e.html
@martent

**Comment by hryd** [comment]
Jag har inte rättigheter att skapa ett nytt repository för webbvideo-inline till malmöstad. @martent fixar du?

**Comment by martent** [comment]
Nu har CGI tillgång till malmostad/sv-webbvideo-inline

Kopiera licens-fil från ett av de andra repona och fixa readme-efterhand.

**Comment by hryd** [comment]
Nu är webbvideo för startsidor uppdaterad. f5c181d817b2ef3131c0b222049a7c2624089d87 

http://www.test.malmo.se/4.4aa5d54114db4999a9f43.html
http://komin.test.malmo.se/4.6aa4ad9d14d52d40f238f807.html

**Comment by martent** [comment]
Du har tagit höjd för att KF-videor ska bete sig annorlunda, dvs vara länkade som tidigare?

**Comment by hryd** [comment]
Ja, se här: http://www.test.malmo.se/2.33aee30d103b8f1591680000.html

Detta beteende sker enbart på huvudstartsidan.

**Comment by martent** [comment]
:+1:

**Comment by olajoh1** [comment]
Snyggt!

**Comment by olajoh1** [comment]
Mikael påpekar:

Jag tycker dock att videofilmerna ser lite lågupplösta ut, fast det ligger versioner i 1280x720? Finns det några begränsningar i spelaren eller hämtar den in versionerna som ligger hos Brightcove (som innan)?

**Comment by martent** [comment]
Mediaströmmen och förhandsbilden kommer direkt från BC. Sitevision och Wordpress gör ingenting med mediamaterialet annat än att placera in det på sidan.

**Comment by olajoh1** [comment]
ok

**Comment by olajoh1** [comment]
klar för deploy. Henrik kontakta Christian

**Comment by martent** [comment]
Stilsättning för player deployad i prod för Komin och malmo.se https://github.com/malmostad/global_assets/releases/tag/v4.1.5

**Comment by hryd** [comment]
Deployed i produktion. @Svempan @martent

**Comment by olajoh1** [comment]
"Fler filmer" har falltit bort

**Comment by olajoh1** [comment]
Problem med Firefox?

**Comment by martent** [comment]
CSS:er som cachas hårt i SV. Kommer att se bra ut efterhand.

Stänger här. Skapa nya tickets om ni hittar buggar,
