### ISSUE TITLE
Olika avstånd ovanför text

### ISSUE THREAD

**Issue by Svempan** [malmostad/sitevision_assets#285]
Varför är det skillnad i avstånd för rubrik 1,2,3 (och brödtext) och två moduler till texten ovanför? 
Kan man få bilden att linjera med rubriken som i fallen med Rubrik 1 och brödtext? Rubrik 2 och 3 får andra avstånd ovanför. Eller ska det vara så?

Exempel:
http://malmo.se/Kultur--fritid/Idrott--fritid/Natur--friluftsliv/Natur--och-rekreationsomraden/Torup/Torups-slott-och-slottspark/Ehrenstrahlsmalningarna.html

**Comment by hryd** [comment]
Om jag förstår frågan rätt så är avståndet mellan rubriker, ingress och brödtext en del av typografin som ligger i global assets, dvs. det är tänkt att vara så. @martent kan utöka svar på denna fråga om det behövs. 

Anledningen till att bilden och rubriken inte linjeras är just på grund av att rubrikerna har `margin-top`, vilket sekundärbilder inte har. Du kan göra så att bilden linjerar med brödtexten genom att lägga H2:an i en egen textmodul. Se exempel: http://www.test.malmo.se/4.47ae63bf14a71afe0c0a609a.html

**Comment by martent** [comment]
Ja, det var ju jag som gjort detta :) Anledningen, ser jag nu, är att det blir för tight mellan ett textstycke och underrubriken om man bara har avståndet efter stycket så därför har jag lagt på avstånd innan underrubrikerna också. Det är svårt att använda selektorer i SV som tar hänsyn till vad som kommer efter.

@hryd's lösning är utmärkt och den ger samma linjering som den övre bilden gör med sitt textstycke. @Svempan är positiv och säljer in det till sidägarna.

**Comment by Svempan** [comment]
Insålt och accepterat
