### ISSUE TITLE
Kontaktrutan på Komin

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#286]
För diskussion. Fick två önskemål om förändringar av kontaktrutan för Komin då jag presenterade nya Komin för Komcheferna i torsdags.

1) länka personnamn till kontaktkorten
2) länka emailadressen till Outlook

@Svempan

**Comment by martent** [comment]
1. Bra idé. Redan idag kan @hryd enkelt bygga adressen eftersom man får ut katalognamnet, `olajoh1`, via API:et:
https://webapps06.malmo.se/dashboard/users/olajoh1
https://github.com/malmostad/sitevision_assets/issues/283#issuecomment-96972493

Jag lägger till adressen i API:et också så blir det en mer agnostisk lösning sett från Kontaktrutan.

2. Länka e-postadresser gör vi inte, men den policyn kan man givetvis se över. Anledningen är att en länkad e-postadress kan öppna upp en mailklient som användaren inte använder på en enhet. De som då inte vet att man kan högerklicka på en länkad e-postadress och välja *Kopiera länk* har ett helvete med att försöka markera och kopiera texten eftersom det oftast leder till ett ofrivilligt klick på det som då är en länk. Sitter de med sin platta eller mobil vill de kanske inte skicka det via Apple Mail eller Samsung Mail utan via webbmailen och då får användarna detta problem. Regeln är idag är därför att hålla det enkelt för användaren och låta det bli enkelt för dem att kopiera texten som utgör e-postadressen och klistra in den i den mail-klient eller webbmail de tänker använda.

**Comment by martent** [comment]
Personnamn och personbild länkat till personens kontaktkort i prototypen, se:
http://malmostad.github.io/prototypes/internal/clean/

**Comment by martent** [comment]
Se även #283.

**Comment by martent** [comment]
@hryd Jag har uppdaterat kontaktbokens API i test med adress till kontaktkortet, wikin uppdaterad:

https://github.com/malmostad/intranet-dashboard/wiki/Contacts-API-v1#get-a-single-employee

**Comment by olajoh1** [comment]
Går det att säga något om hur sannolikt är det att en länkad emailadress öppnar upp en mailklient som användaren inte använder på en enhet?

Ett alternativ till att göra emailadressen länkad är att göra det obligatoriskt med att fylla i email.

**Comment by martent** [comment]
Är inte er webbmail väl använd?

**Comment by hryd** [comment]
Som vi sade på mötet imorse så levereras enbart länkade e-mailadresser innan semestern. Den är nu deployed på komin.test. @Svempan har fått sms tidigare idag.

**Comment by Svempan** [comment]
Verkar funka fint

**Comment by Svempan** [comment]
I produktion i augusti

**Comment by olajoh1** [comment]
I det svarsmeddelande som går till avsändaren så står det kontakta malmostad@malmo.se. Borde vara intern adress? 

Vad säger @Svempan

**Comment by olajoh1** [comment]
Epost ska göras obligatoriskt för Komin

**Comment by hryd** [comment]
Deployed. Obligatorisk epost kvarstår.

**Comment by hryd** [comment]
Länka personnamn till kontaktkorten är implementerad och deployed på test-miljöerna.

**Comment by olajoh1** [comment]
Lyckas inte verifiera

**Comment by hryd** [comment]
På komin är både personnamn och e-post länkade, på externwebben är ingen av dem länkade. 

Se exempel på komin här, http://komin.test.malmo.se/4.30d893e114c60b4e65f4d72f.html @olajoh1.

**Comment by olajoh1** [comment]
ok

**Comment by hryd** [comment]
Ute i produktion. @olajoh1

**Comment by olajoh1** [comment]
ok
