### ISSUE TITLE
Menyvalet "Allt om..."

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#288]
Designen av den autogenerade ankarlänken i högermenyn som leder till översikten i foten ska ändras.

Lägg den direkt i anslutning till övriga menyval så att den blir en del av menyn istället för ett separat val.

@martent

**Comment by hryd** [comment]
Ändrat på dev, se här för exempel: https://www.dev.malmo.se/4.28e0421914cfbd9da273403d.html

**Comment by olajoh1** [comment]
ok, obs gamla ligger kvar parallellt.

**Comment by olajoh1** [comment]
ok
