### ISSUE TITLE
Malmödagar 

### ISSUE THREAD

**Issue by legander** [malmostad/sitevision_assets#289]
|                  |    v20    |     v21   | v22      | v23    | v24     | v25      | v26       | v27        |
|--------------|-----------|-----------|----------|--------|----------|----------|-----------|------------|
|__Simon__| Tis 12  |  Tis 19  |             |          |            |             |              |               |
|                  |             | Ons 20 |             |          |            |             |              |               |
|                  |             | Tors 21 |            |          |            |             |              |               |
|__Henrik__| Mån 11| Ons 20 |Mån 25|Mån 1 |Mån 8  | Mån 15| Mån 22 | Mån 29 |
|                  | Tis 12  | Tors 21 | Tis 26 | Tis 2  | Tis 9   | Tis 16   | Tis 23   | Tis 30   |
|                  |             | Fre 22  | Fre 29 | Fre 5 | Fre 12 | Fre 19 | Fre 26  |               |

**Comment by hryd** [comment]
Uppdaterade.
