### ISSUE TITLE
Hantering av alias under servicefönstret 20-22/5

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#290]
Går det att få vara alias (de som pekar på andra sidor än SV-sidor) att funka under servicefönstret?

**Comment by olajoh1** [comment]
Henrik kikar på en lösning

**Comment by Svempan** [comment]
Kanske användbart?:
![komin_alias](https://cloud.githubusercontent.com/assets/7701048/7582504/7d88cac6-f88e-11e4-97b8-9f799a5f60d2.JPG)
