### ISSUE TITLE
Kontaktformulärets fält går fyller ej på bredden

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#291]
Jmf malmo.se

https://komin.malmo.se/Var-kommun/Malmo-stads-organisation/Kommunstyrelsen.html

**Comment by hryd** [comment]
Kontaktrutan ligger inte i innehållsytan "Kontaktruta", därav fyller den inte upp på bredden.

**Comment by olajoh1** [comment]
Ok
