### ISSUE TITLE
Dekorationen Box fungerar inte

### ISSUE THREAD

**Issue by Svempan** [malmostad/sitevision_assets#292]
Dekorationen Box fungerar inte på Komin. Blir inte som tänkt.

**Comment by hryd** [comment]
Kan du ge URL till var du provat den? Ser ut att fungera bra på denna sida https://komin.malmo.se/4.723c71e514d5c3af02b7005b.html

**Comment by Svempan** [comment]
Nybörjar-otur här. :-) 
Stänger.
