### ISSUE TITLE
Valet "Ingen" saknas under Dekoration på Komin.

### ISSUE THREAD

**Issue by Svempan** [malmostad/sitevision_assets#293]
Det ska väl finnas ett val - "Ingen" - under menyn dekoration? Helst överst. Detta ska väl också vara default. Nu är det "Huvudbild".
Gäller även malmo.se BTW.

**Comment by hryd** [comment]
Ja, det är SiteVision som styr valet av ingen dekoration och den hamnar alltid längst ned. Valet ingen dekoration dyker bara upp om en dekoration är redan vald.

**Comment by Svempan** [comment]
OK
