### ISSUE TITLE
Normalsidemallen

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#295]
Sidan innehåller högerspalt och kontaktruta. Dessa ska bort

**Comment by hryd** [comment]
Kontaktruta är kvar som vi pratade om, högerspalt är borttagen.

**Comment by olajoh1** [comment]
ok

**Comment by hryd** [comment]
Jag kan dock ta bort kontaktrutaportleten från innehållsytan, så att redaktörerna själva lägger till den om den behövs? Innehållsytan kontaktruta är dock kvar.

**Comment by olajoh1** [comment]
Ta bort
