### ISSUE TITLE
Hur ska dekorationer och stilsättning funka på startsidemallen?

### ISSUE THREAD

**Issue by Svempan** [malmostad/sitevision_assets#298]
Det känns ev som vi har ett redaktörshål på startsidemallen? Funkar verkligen stilsättningen och dekorationer på den mallen?
@hryd @martent

**Comment by olajoh1** [comment]
Startsidemallen: Stöd ska läggas till för huvudbild, fokusytan-info och fokusyta-agera. 

Sekundärbilden ska ha ett "anti-stöd". Den röda ramen.

**Comment by hryd** [comment]
Förslag att ta bort `.body-copy` i global assets och eventuellt lägga till `.mf-v4`. @martent kollar.

**Comment by martent** [comment]
`act-now` ligger globalt tillgänglig och behöver inte kontexten body copy:

https://github.com/malmostad/global_assets/blob/ua/app/assets/stylesheets/body_copy.scss#L173-L189

`in-focus` ligger däremot i kontexten body copy:

https://github.com/malmostad/global_assets/blob/ua/app/assets/stylesheets/body_copy.scss#L102-L136

Det blir lätt instabilt att dra ut den i en global kontext. Textstorlekar och SVG-symbolen halkar lätt snett om det finns omgivande font-size och line-height eller positioning som avviker från de som finns i body copy.

Idé: testa att lägga `.body-copy` i yttersta diven i dekorationen i SV och se om det funkar både för start-page body-copy och body-copy body-copy...

**Comment by hryd** [comment]
Att lägga body-copy-div i dekorationsmallen verkar fungera bra för `in-focus`. http://komin.test.malmo.se/4.6aa4ad9d14d52d40f23f52f.html

Däremot har ikonen försvunnit från `act-now`. @martent 

Huvudbild har samma problem, går det att smidigt ta bort `.body-copy` från den? Annars lägger jag in samma lösning som för `in-focus`.

**Comment by martent** [comment]
> Däremot har ikonen försvunnit från act-now

Checklist-ikonen? Den syns i Chrome och FF. Är den borta i IE, funkar den på vanliga sidor?

> Huvudbild har samma problem, går det att smidigt ta bort .body-copy från den? 

Det är lätt men det kan ställa till problem i andra applikationer som använder Global Assets. I och med att  användningen i `start-page-main` är väldigt SV-specifik är det nog stabilast om du gör en faksimil av den för SV. Alltid 100%, och sen bildtext-formateringen och avstånden under objekten.

**Comment by martent** [comment]
Checklist-ikonen på `act-now` funkar när jag testar i IE11/Win8.1.

**Comment by hryd** [comment]
Ja, checklist-ikonen. Jag syftade på komin.test, borde skrivit det, den har funnits där tidigare vill jag minnas. Såg dock att `//assets.malmo.se/internal/v4/icons.data.svg.css` saknas i head, 

Jag lade nu även till så att `huvudbild` fungerar på startsida samt att `sekundärbild` får no-content-styling. Var god testa @Svempan, @olajoh1.

**Comment by martent** [comment]
`icons.data.svg.css` dras in av ett javascript i global assets. Finns inte stöd för svg i browsern drar den in en css med png-bilder istället, men då är vi rätt långt tillbaka i IE-världen.

Vilken browser kör du i? För mig funkar det altså med FF, Chrome och IE11 på din test-länk:
http://komin.test.malmo.se/4.6aa4ad9d14d52d40f23f52f.html

Får du nått JS-fel i konsollen?

**Comment by hryd** [comment]
Jag kör med Chrome Version 43.0.2357.81 m och FF 38.0.5. Visas inte i någon av dem. Fallback med css funkar. Detta js-fel skrivs ut i Chrome: `Uncaught SyntaxError: Unexpected token o  4.6aa4ad9d14d52d40f23f52f.html:1`.

**Comment by martent** [comment]
Det är ett JS-fel som ser ut att komma från SV? Rad 1 i en html-fil? Du får inte samma i prod?

Hursomhelst blockar det antagligen resten av JS-exekveringen, som ajax-hämtning av css-filen. Så felet ligger nog inte i att hämta och visa SVG-data.

**Comment by martent** [comment]
Testa att i en (men inte båda, bra att ha kvar en med felet i...) ta bort kakorna för domänen, både sessions och tranistenta och ladda om sidan.

**Comment by martent** [comment]
OK, jag har hittat det. Det har med ändring av Komin-övergripande användarprofiler att göra och den kaka som hanterar det. Jag fixar. #306

**Comment by hryd** [comment]
Nej, precis, huvudmenyn laddades inte heller. 

Toppen! :v:

**Comment by martent** [comment]
Har gjort nya deployments i test för Komin och malmo.se. Testa och se om det funkar bättre @hryd och sätt över till @ola om det funkar.

**Comment by hryd** [comment]
Funkar bra!

**Comment by olajoh1** [comment]
SNyggt, stöd resp anti-stöd där det ska vara. Klart att deploya.

**Comment by hryd** [comment]
Huvudbild, fokusytan-info, fokusyta-agera samt anti-stöd för sekundärbild på startsida är deployade.
