### ISSUE TITLE
Finns sidor som inte fått ny mall

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#299]
Exempel:

http://komin.malmo.se/Forvaltningar/Serviceforvaltningen/Stod--service/Ekonomi/Raindance/Vanliga-fragor.html

@legander

**Comment by hryd** [comment]
Det är den nya mallen, underrubrikerna är brödtext med fetstil. Högermenyn går sönder för att det är två länkar som är trasiga "Raindance" och "Kodplan". Jag uppdaterar menyscriptet.

**Comment by olajoh1** [comment]
Kan jag testa det på något begåvat sätt eller du har stemkoll?
