### ISSUE TITLE
Klockslag i sidfoten

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#301]
Datum och klockslag har ett "T" mittemellan. Datumformat ska vara svenskt. sekunder ska inte visas.

**Comment by hryd** [comment]
Den ska vara fixad, kan du stämma av igen?

**Comment by olajoh1** [comment]
Ta gärna bortklockslaget också. Annars ok

**Comment by hryd** [comment]
Åtgärdat.

**Comment by olajoh1** [comment]
ok
