### ISSUE TITLE
Fel Innehållsansvarig och Senast ändrad av

### ISSUE THREAD

**Issue by Svempan** [malmostad/sitevision_assets#302]
Fel personer visas

**Comment by hryd** [comment]
Åtgärdat.

**Comment by olajoh1** [comment]
Senast publicerad stämmer numera, däremot inte innehållsansvarig. Förmodligen är det den som ursprungligen skapat sidan som visas.

Vi har en arkivkopia som är någon vecka gammal som referens. Du hittar den på 

http://komin.malmo.arkivbyran.se

Användarnamn: Malmö stad
Lösenord: Arkiv

**Comment by hryd** [comment]
Det finns flera metadata för ungefär samma syfte, vilket har gjort det förvirrande. Jag har jämfört några sidor på nuvarande komin och den arkiverade versionen vilket metadata som bör gälla. Ser det korrekt ut nu?

**Comment by olajoh1** [comment]
Nu verkar det vara rätt. Dock skiljer formen, på ena raden visas epostadressen, på den andra namnet i klartext. Ändra till epostadress på båda raderna.

**Comment by hryd** [comment]
Uppdaterad!

**Comment by olajoh1** [comment]
löst
