### ISSUE TITLE
Felaktigt flöde i webbvideo på komin

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#303]
Flödet på videospelaren visar endast de filmer som är taggade för komin. De filmer vi har som ska visas på både malmo.se och komin syns inte.

**Comment by olajoh1** [comment]
Henrik k0ontaktar Carl

**Comment by hryd** [comment]
Targetgroup kan bara vara ett värde, om ingen av checkboxarna väljs i gränssnittet så blir customfields null. Det hade blivit en snyggare lösning om targetgroup alltid var satt till komin, malmo-se eller båda två beroende på var de ska visas. 

Jag deployade en ny variant av webbvideo för komin på komin.test med logiken att filmer visas om targetgroup är komin, malmo-se eller om customfields är null. Är det korrekt beteende?

**Comment by hryd** [comment]
Uppdaterat igen efter mailkonversation.

**Comment by olajoh1** [comment]
Det är bara mikael här som kan sluttesta logiken och han får vi inte tag i.

Deploya men ha koll på att det inte krascha och att inte Kominfilmer visas externt.

**Comment by olajoh1** [comment]
Har du deployat?

**Comment by hryd** [comment]
Deployade igår vid 17. @olajoh1

**Comment by olajoh1** [comment]
ok
