### ISSUE TITLE
Google analytics

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#304]
Trafik registreras numera, för Komin, på både url:er och kortlänkar, t.ex. både på komin.mlamo.se/gatukontoret och komin.malmo.se/forvaltningar/gatukontoret.html

**Comment by martent** [comment]
SV skickade ut värdet som en javascript-variable på sidan innan. Har för mig att den genererades i en scriptmodul i en mall-del: Såg ut så här:  `var currentURI = "/Var-kommun/Grona-Komin.html";` Denna saknas nu. Kan du kolla om du kan hitta den och lägga in i nya mallarna @hryd?

**Comment by martent** [comment]
Ser att den ligger i script-modulen `script-vars` i gamla malldelen: 

http://komin.malmo.se/templatesforvarkommun/gamlamallaranvandej/30/elements/header.91.67dd4c081286e53af0580009316.html

Ska alltså skickas ut på varje SV-sida på samma sätt som på malmo.se.

**Comment by hryd** [comment]
Nu är den ditlagd igen!

**Comment by olajoh1** [comment]
ok
