### ISSUE TITLE
Kakvarning i WAG funkar inte

### ISSUE THREAD

**Issue by Svempan** [malmostad/sitevision_assets#305]
Kakvarningen på malmo.se/wag går inte att ta bort :-)

**Comment by martent** [comment]
Observant!

Jag gör en fix.

**Comment by martent** [comment]
Rekommenderar i övrigt att ni pekar ett cname till WAG på https://malmostad.github.io. Jag fixar delen på Github om ni fixar ett cname i DNS:en:
https://help.github.com/articles/tips-for-configuring-a-cname-record-with-your-dns-provider/

Typ wag.malmo.se eller s25.malmo.se beroende på vilken väg ni går.

**Comment by martent** [comment]
Jag har lagt på en fix som endast visar kakvarningen på domänen malmo.se. Det är den vi sätter kakor på och där vi kan spara kavarningingskakan...

**Comment by Svempan** [comment]
Toppen!
