### ISSUE TITLE
Universal Analytics på Komin

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#306]
Dags att fundera över hur vi kan använda UA för att identifiera och följa unika användare (anonymt).

**Comment by martent** [comment]
Tänker vi oss [global assets](https://github.com/malmostad/global_assets/issues/) eller bara för användarna i SV?

**Comment by olajoh1** [comment]
GA i GA

**Comment by martent** [comment]
Ligger i test nu. Gå till:
https://webapps06.malmo.se/dashboard-test/logout

Logga in igen och surfa runt i de olika test-webbarna med desktop och mobil.

**Comment by martent** [comment]
@olajoh1 kollar hur man läser ut i statistiken. Finns dokumentation på en massa olika ställen, denna länkas inne från rapportverktyget:

https://support.google.com/analytics/answer/3123669

**Comment by martent** [comment]
Jag har gjort om genereringen av uaid, vilket innebär att du och jag kommer att se ut som nya användare i test-statistiken. Den verkar ta över ett dygn att komma in.

**Comment by martent** [comment]
Jag har dessutom gjort en deploy av Global Assets i test för externa tjänster så att du kolla att den nya loggningsupplägget inte påverkar externa tjänsters UA-loggning.

**Comment by martent** [comment]
Jag har gjort mer datapopulering som inkluderar tablet med och det kommer in i förväntade proportioner.

**Comment by olajoh1** [comment]
Det jag kan syna ser bra ut. Får fortsätta i drift med mer data. Deploya.

**Comment by martent** [comment]
Ny Dashboard deployad i prod. Global Assets deployad i prod för Komin och malmo.se. 

Interna användare trackas med samma UA ID även när de surfar på malmo.se.

**Comment by martent** [comment]
UA var inte aktiverat i GA för prod. Jag gjorde det för Komin och malmo.se. Se ovan https://github.com/malmostad/sitevision_assets/issues/306#issuecomment-111066662

**Comment by olajoh1** [comment]
När jag jmf Komin med och utan UAID för gårdagen får jag märkliga resultat. 

Antal unika användare minska från 12´ till 7´ vilket verkar rimligt. 

Jag hade dock förväntat mig att t.ex. antal sessioner och sidvisningar skulle vara samma, men även dessa minskar.

**Comment by martent** [comment]
Kan vara så att 5T inte passerat Min sida och loggat in.

**Comment by olajoh1** [comment]
5T?

**Comment by martent** [comment]
`T = 1000`

**Comment by martent** [comment]
diff mellan 12T och 7T
