### ISSUE TITLE
Dekorationen Box i normalsidemallen

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#309]
Den ska dupliceras, följande versioner ska finnas:

Läs mer
Fakta

@Svempan @martent

**Comment by hryd** [comment]
Åtgärdat. @Svempan @martent

**Comment by olajoh1** [comment]
Jag har testat på sidan nedan men får inte dekorationen att slå igenom.

http://komin.test.malmo.se/Var-kommun/Socialt-hallbart-Malmo/Kommission-for-ett-socialt-hallbart-Malmo.html

**Comment by hryd** [comment]
Kopiera in Fakta och Läs mer från modulsidan. Jag lade en faktaruta där för att testa och det verkar se bra ut?

**Comment by olajoh1** [comment]
Här har jag valt dekorationerna Fakta resp Läs mer för två olika textmoduler. Dessa får en ram men de ska stilsättas som boxen nedan.

http://komin.test.malmo.se/4.6fae280a14db498df1e13cf7.html

**Comment by hryd** [comment]
Kopiera från modulsidan eller sätt upp dem som boxen är på samma sida. Det krävs en layout och två textmoduler för att skapa detta. Se även manualen i sektion 2.4 Box.

**Comment by olajoh1** [comment]
ok
