### ISSUE TITLE
Exempel på sida med felaktig mall

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#310]
Sidan nedan har felaktig mall. Vad jag kan se då jag granskar tidigare versioner har den haft felaktig mall även i tidigare version.

http://komin.malmo.se/Arbetsfalt-verksamheter/Chef/Chef-i-Malmo-stad/Utveckling-for-dig-som-chef/Frukostseminarier/Att-vara-chef.html

**Comment by hryd** [comment]
Som vi pratade om, den ska bytas till normalsida. :thumbsup:
