### ISSUE TITLE
Alias/direktadresser klassas som kategorien övrigt av Siteseeker

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#312]
Är det relaterat till siteseeker eller något vi själva kan åtgärda? Exempel:

http://s1.malmo.se/search?utf8=%E2%9C%93&q=lediga+l%C3%A4genheter

**Comment by martent** [comment]
Beror inte det på hur du har mappat URL:er i Siteseeker admin?

Se även frågan i https://github.com/malmostad/sitevision_assets/issues/277#issuecomment-100184206

**Comment by olajoh1** [comment]
ok, jag tar det med siteseeker
