### ISSUE TITLE
Stilsättning av sökresultat

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#313]
Ordningen av informationsobjekten för sökresultat borde ändras så att beskrivningen kommer före brödsmulan. Brödsmulan behöver dessutom stilsättas så att det framgår att det är en brödsmula

**Comment by martent** [comment]
Det som är under beskrivningen är inte brödsmulorna utan de katagorier du mappat upp. I de fall vi får ut brödsmuleraden från SV så läggs den mellan rubrik och beskrivning medan katagorierna ligger under. Detta för att de båda informationsobjekten som är så lika i sin art ska blandas ihop.

**Comment by martent** [comment]
... kanske minns jag fel, det är så länge sen vi fick ut brödsmulorna från Siteseeker.

**Comment by olajoh1** [comment]
Det stämmer att det är kategorierna som visas under beskrivningen men det var brödsmulan jag tog upp. Menar du att den stilsätts i siteseeker?

**Comment by martent** [comment]
Har du nått exempel med ett resultat med brödsmulor i sig? Ett tag kom det med från Siteseeker på vissa resultat men nu hittar jag inget.

**Comment by martent** [comment]
OK, den är är tvådelad:

1. Siteseeker indexerar breadcrumbs `<nav>` som om det vore content. @hryd kan du lägga in `<!--eri-no-index-->` och `<!--/eri-no-index-->` runt elementet där `eri-desc`-kommentarer redan ligger. Gör det direkt i prod på malmo.se och Komin. (testinstanserna indexeras inte).

2. Breadcrumbs som returneras från Siteseeker har fått en ny datastruktur så vi fångar inte upp dem. Jag tittar på detta.

**Comment by hryd** [comment]
Lade in `<!--eri-no-index--><!--/eri-no-index-->` på malmo.se. Avvaktar med komin, som vi sade på mötet.

**Comment by martent** [comment]
Ser ut att ha slagit igenom på malmo.se, kollar du också @olajoh1?

Jag ska göra en deploy för punkt (2) ovan under dagen.

**Comment by olajoh1** [comment]
Sr bra ut

**Comment by martent** [comment]
Sök för malmo.se och Komin uppdaterad så att brödsmulorna är med.

@hryd Lägger du in `<!--eri-no-index--><!--/eri-no-index-->` på Komin också och sätt sen till @olajoh1 så får han verifiera dagen efter.

**Comment by hryd** [comment]
Även gjort nu på komin. Däremot saknades `<!--eri-desc-->`, jag lade till den också, korrekt? @martent

**Comment by martent** [comment]
Jepp, det var #315 :)

@olajoh1, du får verifiera på måndag när det slagit igenom.

Ser att SV:s smulor för Komin har "Start" som förstaled medan WAG:n och bl.a. Nyheter och Blogg har "Komin" som förstaled. Jag tror att tanken med "Komin" var att göra tydlig skillnad mot malmo.se som har "Start".

**Comment by olajoh1** [comment]
Ok malmo.se, kan inte kolla komin. 

Vi ändrar från Start till Komin

**Comment by hryd** [comment]
Ändrat.

**Comment by martent** [comment]
Ser bra ut. 

@olajoh1, då stänger du här?
