### ISSUE TITLE
Play-knappen not found

### ISSUE THREAD

**Issue by martent** [malmostad/sitevision_assets#314]
På testsidan vi testar annat på (#298):
http://komin.test.malmo.se/4.6aa4ad9d14d52d40f23f52f.html

Laddar inte playknappen vid hover in. Konsollen säger:

http://komin.test.malmo.se/images/18.760b3241144f4d60d3b9040/play.png Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by hryd** [comment]
Länken är statisk till externwebbens produktionsmiljö. Jag lägger in en bättre sökväg som baserar på mappstrukturen i SiteVision där bilden ligger, som måste stämma överens i alla miljöer. Används bilden på andra webbplatser? @martent

**Comment by martent** [comment]
Det är bara i SV vi har tumnaglarna som visar video ovanför och koden till den ytan ligger väl helt i sitevision assets? Inlinespelaren i artiklar finns i Blogg och Nyheter också men där är det Brightcoves egen playknapp som visas.

**Comment by hryd** [comment]
Okey, ja, då får bilden ligga kvar i SiteVision.

**Comment by hryd** [comment]
Deployed på komin. Malmo.se kvarstår, deployscriptet kördes inte korrekt. Jag har meddelat driften. @olajoh1 @martent

**Comment by hryd** [comment]
Deployed på malmo.se också.

**Comment by martent** [comment]
`OK 200`
