### ISSUE TITLE
eri-desc på nyheter

### ISSUE THREAD

**Issue by martent** [malmostad/sitevision_assets#315]
@olajoh1 upptäckte att `eri-desc`- och `eri-desc`-kommentarerna saknas på nyhetssidorna runt brödsmulorna. Kan du lägga in den i prod malmo.se vid tillfälle så som den ligger i på andra sidor, se https://github.com/malmostad/sitevision_assets/issues/313#issuecomment-110344952

cc @olajoh1

**Comment by hryd** [comment]
Åtgärdat.

**Comment by martent** [comment]
Koden ser bra ut. Jag kollar sökresultatet imorgon när indexering skett.
