### ISSUE TITLE
Kommunövergripande nyheter i fel typsnitt

### ISSUE THREAD

**Issue by martent** [malmostad/sitevision_assets#316]
"Kommunövergripande nyheter" på https://komin.malmo.se/Var-kommun är satt i Trebuchet. Lite synd när det är överst på Komins startsida. 

Är det inte bättre att ersätta texten Nytt och viktigt med Kommunövergripande nyheter för att inte få tre rubriker på varandra och för att det senare tydligare säger vad det är för nyheter?

@Svempan

**Comment by olajoh1** [comment]
Det är redaktören (Jörgen) som har lagt in en extra rubbe "Kommunövergripande". "Nytt & viktigt" är Komin-standard.

**Comment by martent** [comment]
Ni använder inte Trebuchet i typografin längre.

**Comment by olajoh1** [comment]
Helt rätt, och det gör vi inte på den aktuella sidan heller numera :-)
