### ISSUE TITLE
Videospelaren i admin

### ISSUE THREAD

**Issue by Svempan** [malmostad/sitevision_assets#318]
Det är en bugg i någonstans i admin i Sitevision:
![skarmklipp](https://cloud.githubusercontent.com/assets/7701048/8156354/6898e7c6-134c-11e5-9d11-4b260aa09722.JPG)

**Comment by hryd** [comment]
Den deployades väldigt nyligen, det kan ha hänt att du kikade precis under deploy, kan du verifiera nu igen att buggen kvarstår?

**Comment by Svempan** [comment]
Verkar bara gälla Firefox vad jag kan se

**Comment by hryd** [comment]
Kan du utveckla, ser det konstigt ut när du försöker spela upp en video i redigeringsgränssnittet? @Svempan

**Comment by Svempan** [comment]
Nu funkar det!!!

**Comment by hryd** [comment]
:+1:

**Comment by martent** [comment]
Nu funkar det i min FF också. Stänger.
