### ISSUE TITLE
Sida eller det alias som heter /webbvideo kan ha konkurrerats ut av den nya portleten 

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#319]
Det verkar vara så att "/webbvideo/" i  länken här under inte uppfattas av vårt system längre? Så man får en 404?

http://malmo.se/webbvideo/?bctid=1970174661001

Mårtens kommentar:
Sida eller det alias som heter /webbvideo kan ha konkurrerats ut av den nya portleten som kanske också heter "webbvideo" som tar träffen innan den når Sitevision.

@martent

**Comment by hryd** [comment]
Åtgärdat nu! @martent

**Comment by olajoh1** [comment]
ok
