### ISSUE TITLE
Synpunkter

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#321]
I IE postas inte synpunkten

**Comment by olajoh1** [comment]
Innehållet i ärendemeningen har ändrats. Datum och svar har fallit bort och ersatts med "feedback"

![synpunkter](https://cloud.githubusercontent.com/assets/6176181/8328841/906e784a-1a74-11e5-82a6-a911f2bd8281.PNG)

**Comment by hryd** [comment]
Jag har uppdaterat rubriken i mailet. @olajoh1

**Comment by hryd** [comment]
Det funkar nu i IE8 för mig. Kan du testa i IE du också @olajoh1 ?

**Comment by olajoh1** [comment]
Funkar inte i IE11 hos mig

**Comment by olajoh1** [comment]
Saknar också möjlighet att lägga arvet på sida med annan mall än normalmallen

**Comment by hryd** [comment]
Lade till att metadatat även finns på mallarna för startsida och navigationssida. Fel i IE11 kvarstår.

**Comment by olajoh1** [comment]
Metadata funkar.

**Comment by nikjon76** [comment]
Finns det någon mer djupgående förklaring till synpunkter ärendemening?
Som jag ser det är det bara en fix för IE 11 som kvarstår. stämmer det?

**Comment by olajoh1** [comment]
Precis, Synpunkterna skickas aldrig i IE då användaren klickar på sändknappen.

**Comment by olajoh1** [comment]
Fungerar fortfarande inte i IE på www.test.malmo.se

**Comment by olajoh1** [comment]
Fungerar fortfarande inte i IE på www.test.malmo.se

**Comment by nikjon76** [comment]
Ola, kan du se om det kommit in några synpunkter från 25/02 'Test IE 11.0.9'
Fann ytterligare några saker som satte käppar i hjulet för IE

**Comment by olajoh1** [comment]
[cid:image001.png@01D16FDB.F961EB40]

Från: Niklas Jönsson [mailto:notifications@github.com]
Skickat: den 25 februari 2016 14:36
Till: malmostad/sitevision_assets
Kopia: Ola Johansson
Ämne: Re: [sitevision_assets] Synpunkter (#321)


Ola, kan du se om det kommit in några synpunkter från 25/02 'Test IE 11.0.9'
Fann ytterligare några saker som satte käppar i hjulet för IE

**Comment by olajoh1** [comment]
Funkar i IE, FFoch Chrome

**Comment by nikjon76** [comment]
Synpunkter är nu driftsatt i produktion malmo.se

**Comment by olajoh1** [comment]
Gott, vill du lägga på ändringen på vårt intranät också. Vi börjar med komin.test.malmo.se

**Comment by olajoh1** [comment]
Ska finnas två metadata som kopplas till synpunkter, Mottagare (synpunkter på sidan) saknas.

**Comment by nikjon76** [comment]
Synpunkter är nu driftsatt i komin.se
