### ISSUE TITLE
GA - antal sessioner ökar medan antal sidor/session minskar i samma utsträckning

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#322]
Mönstret ovan kopplar jag till att reglerna för timeout i GA. Har default ersatts? (Gäller enbart Komin.)

_setSessionCookieTimeout() 

_setSessionCookieTimeout(cookieTimeoutMillis) 
Sets the new session cookie timeout in milliseconds. By default, session timeout is set to 30 minutes. Session timeout is used to compute visits, since a visit ends after 30 minutes of browser inactivity or upon browser exit. If you want to change the definition of a "session" for your particular needs, you can pass in the number of milliseconds to define a new value. This will impact the Visits reports in every section where the number of visits are calculated, and where visits are used in computing other values. For example, the number of visits will increase if you shorten the session timeout, and will decrease if you increase the session timeout. You can change the expiration timeout to 0 to indicate that this cookie should be deleted when the browser is closed. 

Async Snippet (recommended) 
_gaq.push(['_setSessionCookieTimeout', 1800000]);
_setSessionCookieTimeout() 

_setSessionCookieTimeout(cookieTimeoutMillis) 
Sets the new session cookie timeout in milliseconds. By default, session timeout is set to 30 minutes. Session timeout is used to compute visits, since a visit ends after 30 minutes of browser inactivity or upon browser exit. If you want to change the definition of a "session" for your particular needs, you can pass in the number of milliseconds to define a new value. This will impact the Visits reports in every section where the number of visits are calculated, and where visits are used in computing other values. For example, the number of visits will increase if you shorten the session timeout, and will decrease if you increase the session timeout. You can change the expiration timeout to 0 to indicate that this cookie should be deleted when the browser is closed. 

Async Snippet (recommended) 
_gaq.push(['_setSessionCookieTimeout', 1800000]);

**Comment by olajoh1** [comment]
Felmeddelande. Kanske ett spår?

En stor del av hänvisningstrafiken till egendomen http://komin.malmo.se kommer från följande värdnamn, som kan vara självlänkar:
komin.malmo.se
Självlänkar är länkar från sidor på dina egna domäner. Självlänkar kan dölja de faktiska trafikkällor som ska tillskrivas konverteringar och andra interaktioner på din webbplats. Det kan få till följd att länkstatistiken blir missvisande. Självlänkar kan också vara ett tecken på felaktigt konfigurerad spårning över flera domäner. Användarna kanske genererar en session per domän, vilket ökar antalet sessioner på konstgjord väg.

Det finns flera exempel på felaktiga Analytics-konfigurationer som kan resultera i självlänkar: Användare som navigerar från en otaggad sida på din webbplats till en taggad sida, kan visas som självlänkar. Användare som navigerar från en underdomän på din webbplats till en annan underdomän som använder en annan cookiedomän, kan visas som självlänkar. Om du spårar flera domäner i en webbegendom, kan användare som navigerar över flera domäner på din webbplats utan länkningsparametrar som överför cookieinformation korrekt, visas som självlänkar.

Undvik självlänkar genom att kontrollera att alla sidor på webbplatsen är korrekt taggade med Analytics-spårningskoden. Kontrollera att spårning över flera domäner är korrekt konfigurerad på alla sidor. Kontrollera inställningarna för cookiedomänen i spårningskoden, så att alla underdomäner i en domän använder samma cookiedomän.

**Comment by martent** [comment]
Sessionstiden sätter man nog bara med kodning om man vill ha avvikelser på vissa resurser, det generella värdet sätts i GA:s kontrollpanel. Jag kommer inte åt de inställningarna för Malmö stad, bifogar vyn från ett annat konto så ser du hur det ser ut:

<img width="851" alt="screen shot 2015-08-18 at 11 45 02" src="https://cloud.githubusercontent.com/assets/603695/9327127/df2706a0-459e-11e5-8c12-2a057e2eee1e.png">

**Comment by martent** [comment]
Vi la ut UA för intranätet 2/4 och för externa resurser 25/5. Stämmer det med trendskiftet i rapporterna?

**Comment by martent** [comment]
Jag har den mest troliga fixen av de Google föreslår (förutom sessionstiden som du kan ändra i kontrollpanelen, se ovan). Deployat i test för interna och externa resurser. Är test tillräcklig för att se om det fixat felet?

När den nya koden går ut kommer alla besökare att räknas som nya, de får nya kakor från google, så det blir avvikelser i statistiken under den första tiden.

**Comment by olajoh1** [comment]
Märkligt, jag får inte ens upp möjligheten att sätta t.ex. sessionstiden (har full behörighet). Har aldrig gjort det heller. Använder dock svensk version, har tidigare stött på att det är olika menyval mellan svensk och engelsk version. Ska ändra. (Har uppdaterat din behörighet.)

**Comment by olajoh1** [comment]
Exakt datum då det händer är den 14 april.

**Comment by olajoh1** [comment]
Om du lämnar komintest till mig imorgon testar jag då

**Comment by martent** [comment]
Hands off här.

**Comment by martent** [comment]
Sessionstiden står på 30 minuter både för komin och malmo.se. Det är default så det är nog inte ändrat.

**Comment by martent** [comment]
Deploy med unikt användar-ID borttaget gjort 2015-08-24 16:00. malmo.se och Komin.

**Comment by olajoh1** [comment]
Testdata från början av veckan ser korrekt ut.

**Comment by martent** [comment]
Ska jag lägga ut i produktion?

**Comment by olajoh1** [comment]
ja det tycker jag

**Comment by olajoh1** [comment]
Verkar som external och download tappas bort

**Comment by martent** [comment]
Jag har inte deployat än. När hände detta?

**Comment by olajoh1** [comment]
21 maj

**Comment by martent** [comment]
Uppdaterat ExternalLinks och FileDownloads för UA.

**Comment by martent** [comment]
Deploy gjord i prod för interna och externa tjänster.
