### ISSUE TITLE
Uppgradering till SV 4.x

### ISSUE THREAD

**Issue by martent** [malmostad/sitevision_assets#323]
@martent börjar med att lista aktiviteter så att @olajoh1 sen kan kalendersätta och boka upp folk.

**Comment by martent** [comment]
Vi pratade om att plocka in och anteckna input och frågor kring detta i våras. Gjordes det efter diskussionerna med @hryd, SVAB och om Christian och @Svempan och redaktörer kommit upp med något? Annars får vi börja om får början.

Insamling av frågor och synpunkter är steg ett. Sen kanske en diskussion med SVAB och därefter en utvärdering av när en uppdatering är lämplig och en planering av resurser och aktivitet för det. Det vi kan plocka in input kring är:

1. Utvecklarperspektivet och erfarenheter från andra projekt. @hryd är den som kan bidra.
2. Driftsperspektiv och erfarenheter kring uppdatering i test. Christian kan bidra. Här kanske man ska boka in en aktivitet också, att under en dag gå igenom test-installationen, loggar och annnat ur ett driftsperspektiv och anteckna.
3. Redaktörsperspektivet. Sven och en handfull redaktörer provocerar sina sidor och gör de handgrepp de brukar göra och antecknar.

En fråga kring (3) som jag minns kom upp var att det krävdes en roll som fortfarande använder Java appleten för att göra vissa handgrepp. Gäller detta fortfarande och hur hanterar vi det? Fråga SVAB.

Medverkande i planläggning av uppgradering till 4.0 är:
* @Svempan och redaktörer
* Driften
* SVAB
* @hryd 

Vad man kommer fram till i utvärderingen får visa vilka roller som behövs för själva uppgraderingen, men antagligen är det samma som ovan.

**Comment by hryd** [comment]
Den största skillnaden är gränssnittet. Det nya kör på HTML5/JS och fungerar bra att redigera text och bild. Däremot har de inte lagt in stöd för att ändra i alla portlets utan då måste redaktören växla över till det "klassiska redigeringsläget", men det går ganska smidigt att göra. För att gå direkt till det nya gränssnittet används /edit, medan det klassiska är kvar på /editor. 

I det nya gränssnittet förekommer det skillnader i SiteVisions CSS. Det betyder att det kan förekomma oönskat beteende med Malmö Stads egna styling. Detta kommer märkas i punkt 3 i ovanstående inlägg.

**Comment by olajoh1** [comment]
Som du såg i ett separat mail är nu dev uppdaterad till 4.0.3 så att du har möjlighet att fortsätta.

**Comment by olajoh1** [comment]
Findings från redaktörerna:

1.	Skapa >Ny>Välj mall Ser för många mallar. Alla gamla, (i papperskorg osv)
2.	Headern ligger kvar på alla sidor när man skrollar
3.	Det går inte att navigera i ”Meny”-menyn
4.	Redigera bild fungerar inte i IE11 (bugg i SV4?)
5.	”Lägg till nyhet”-länken funkar inte
6.     Av någon anledning förlorar vissa den gröna handen. Tror att de hamnar utan för https. Det blir    av någon anledning http.


Frågor att diskutera
Hur kopplar man av och på det nya gränssnittet för olika grupper i katalogen?
Är det någon ny funktion vi bör låsa?

**Comment by hryd** [comment]
1. Ändrade rättigheter på mappen Gammalt, Papperskorgen kan dock bara HR se. Vad för behörighet har redaktören som såg Papperskorgen? 
2. Är lite osäker på vad som menas, den fungerar som på malmo.se. Jag har dock noterat att om du är inloggad så är headern förskjuten 30px ned. Detta var en fix för det gamla gränssnittet så att headern inte döljs bakom SiteVisions verktygsmeny. Om fokus för redaktörerna är det nya gränssnittet så tar jag bort dessa 30px? 
3. Den har fel alias, bör gå mot www.dev.malmo.se istället för malmo.se. 
4. Jag har provat i IE11 och det fungerar, kan du utveckla? 
5. Kan du förse med länk? 

>Frågor att diskutera
>Hur kopplar man av och på det nya gränssnittet för olika grupper i katalogen?

Under Huset > Webbplatsinställningar > Säkerhet > Redigeringsläge går det att lägga till grupper som ska få behörighet att använda nya gränssnittet. 

>Är det någon ny funktion vi bör låsa?

Inte vad jag känner till i dagsläget.

**Comment by olajoh1** [comment]
1. Förvaltningsredaktör
2. Om detta är en fix för "classic" gör vi ingenting just nu, då de flesta kommer att arbeta vidare i "Classic" under en övergångsperiod.
3. ok
4. Funkar inte när Sven och andra redaktörer gör det. Sven testar igen.
5. Om man klickar på "lägg till nyhet" i nya läget händer inget. Du kan kolla vilken sida som helst med en nyhetsticker, tex. startsidan
6. Du verkar ha missat denna
7. Du återkommer?

**Comment by hryd** [comment]
Lite uppdateringar. 
1. @olajoh1 ber @Svempan testa om. 
6. Måste ha mer information, jag ringer @Svempan. 
7. SiteVision verkar inte ha stöd för detta förrän SV4.1, jag har ringt Ulrika och de ska återkomma med mer information.

**Comment by Svempan** [comment]
1:an. Fortfarande en massa mallar. Så här ser det ut för en förvaltningsredaktör:
![gamla mallar](https://cloud.githubusercontent.com/assets/7701048/11627804/a4a0ee64-9ced-11e5-8eb6-f87184802874.JPG)

**Comment by hryd** [comment]
1. Jag provade med en testanvändare, den ser mallar som den inte har rättighet till i det nya gränssnittet men inte i det gamla. Jag har mailat SiteVision. 
3. Det finns ingen global asset för dev enligt @martent, så länkarna i menyn kommer att gå till fel sida om vi inte sätter upp en. 
5. SiteVision verkar ha ändrat markupen för funktionaliteten, anpassning krävs. Jag tittar på det. 
6. Sven återkommer med mer information. 
7. Inväntar svar från SiteVision.

**Comment by hryd** [comment]
Uppdatering: 
1. Inväntar svar från SiteVision, de ska kolla på problemet. 
5. Jag har ändrat markupen, @Svempan kan du testa? 
6. Inväntar information från @Svempan. 
7. Arbetar med problemet efter återkoppling från SiteVision.

**Comment by Svempan** [comment]
5. När jag testar i "nya läget" drar javan i gång som det vore klassiskt.
6. Vi släpper denna. Verkar som att redaktörerna navigerat via toppmenyn och då hamnat på www.malmo.se.

**Comment by hryd** [comment]
Uppdatering: 
5. I markupen måste `data-use-new-editor` sättas till `true` eller `false`, båda redigeringsgränssnitten kommer att användas och därav tar vi bort denna till dess att alla går över till det nya gränssnittet. 
7. Pausar denna, checkar in i branch sv4.

**Comment by nikjon76** [comment]
Kontakter hämtas från MS webbapp som kallas för kontaktboken genom ett REST-API. Dokumentation för detta API finns här: 
https://github.com/malmostad/intranet-dashboard/wiki/Contacts-API-v1
 
Efter en uppdatering till Sitevision 4 vänder en metoden på svaret och länken som skapas för att utvisa kontaktrutan läser istället in hela den aktuella HTML sidan.  Istället för att använda dynamisk data i funktioner laddas objektet om vilket har tills nu fungerat bra men får ett alvarligt fel i Sitevision 4.x. 
 
ContactBoxForm
 
<form id="configForm" action="$renderResponse.createActionURL()" method="post">
 
RenderResponse definierar ett objekt för att hjälpa portleten att  skicka ett svar till portalen. Den använder sig av ett PortletResponse gränssnittet att tillhandahålla specifika renderade svars med funktionalitet till portleten. 
Behållaren för portleten skapar ett RenderResponse objekt och skickar svaret som ett argument till portletens render metod. 
 
Workaround skulle kunna vara att manuellt sätta WindowState SOLO om du är PortletMode CONFIG och vill bibehålla "standalone-rendering".
 
Kanske något liknande nedanstående (?):

ContactConfigController

 
if ("config".equalsIgnoreCase(request.getPortletMode())) { // Precaution, ensure CONFIG mode...
  if (request.getParameter("_ok") != null) { 
     ...
  }
  else if (request.getParameter("_addContact") != null) {
    response.setRenderParameter("action", "add");
    response.setWindowState(new WindowState("solo")); // Standalone-rendering
  }
  else if (request.getParameter("_modifyContact") != null) {
    response.setRenderParameter("contact", request.getParameter("contact"));
    response.setRenderParameter("action", "modify");
    response.setWindowState(new WindowState("solo")); // Standalone-rendering
  }
  else if (request.getParameter("_removeContact") != null) {
    ContactKey key = gson.fromJson(request.getParameter("contact"), ContactKey.class);
    contactBox.getContacts().remove(key);
    response.setWindowState(new WindowState("solo")); // Standalone-rendering
  }
  
  if (request.getParameter("_ok") != null || request.getParameter("_cancel") != null) {
    try {
        response.setPortletMode(PortletMode.VIEW);
        response.setWindowState(WindowState.NORMAL); // Ensure default (non-standalone) rendering
    } catch (PortletModeException e) {
        logger.error(e.getMessage(), e);
    }
  }  
}

**Comment by tomasrobertsson** [comment]
Noterat att den orangea ruta som lägger sig i toppen på många sidor är resultat av felet i kontaktportleten. 
Dvs när den är rätta bör den rutan försvinna men vi bör samtidigt se till att error-rutan sköter sig och lägger sig på rätt plats.

**Comment by tomasrobertsson** [comment]
Och som svaret ovan om kontaktrutan säger är resultatet av getActionURL() olika i SV4 och SV3
I SV3 får vi ut en länk i stil med
/4.5d8108001222c393c0080002910.12.228b8e2313f816262746ba.html.portletaction?sv.mode=config

och i SV4
/portletaction/91.12e2278a148980ba13a84f37/12.60a621bc148d4b5e3b89a97

**Comment by tomasrobertsson** [comment]
Kontakrute-portleten är nu uppdaterad att fungera i klassiska redigeringsläget i Sitevision 4. 
Det som står ovan stämmer i princip med det jag ändrat i koden för att få det att fungera.

Att även få upp den i SV4 moderna gränssnitt vet jag inte hur mycket arbete som krävs för. Där får ni bestämma om jag/vi ska gå vidare. Om ni tänker er göra er fria från Java-lösningen inom en snar framtid kanske det inte är värt besväret.

**Comment by magnivar** [comment]
2 år + 1 vecka senare... nu stänger vi ärendet :)
