### ISSUE TITLE
SV:s kopplingar till andra system

### ISSUE THREAD

**Issue by martent** [malmostad/sitevision_assets#327]
I och med att webapps-servrarna migreras till nya servrar och även delas så att de som tidigare legat på samma servrar får egna servrar med egna subdomäner.malmo.se så måste ompekningar från bl.a. Sitevision på malmo.se och Komin göras. Vad berör detta i SV? Skriv ned i denna ticketen vad ni kommer på.

Jag har föreslagit att man under en övergångsfas på kanske ett år ska fånga upp alla anrop till de gamla subdomänerna och peka dem till rätt adress på de nya servrarna, vilket även löser problemet med att äldre social delning, länkar och bokmärken kommer att fungera, men jag har inte fått gehör för det och det finns inte med i projektet.

@Svempan @olajoh1 @hryd

**Comment by martent** [comment]
Kontaktrutans API-anrop mot Kontakboken.

**Comment by martent** [comment]
RSS-flöden på huset

**Comment by martent** [comment]
Nyheter som hämtas externt via nyhetsmodulen på Komin, påverkas de?

**Comment by hryd** [comment]
"Nyheter som hämtas externt via nyhetsmodulen på Komin, påverkas de?" 

De påverkas, jag gjorde ett stickprov på några sidor och många hämtar nyheter från webapps04. Om alla externa RSS-flöden ändras till de nya adresserna på huset så löser det sig.

**Comment by hryd** [comment]
Proxyportlet i sidfot på malmo.se går mot http://evenemang.malmo.se/sv/evenemanget/rss.

**Comment by martent** [comment]
>> Nyheter som hämtas externt via nyhetsmodulen på Komin, påverkas de?

> De påverkas, jag gjorde ett stickprov på några sidor och många hämtar nyheter från webapps04. Om alla externa RSS-flöden ändras till de nya adresserna på huset så löser det sig.

På Komin är det c:a 360 RSS på huset så det tar lång tid och är också risk att 1-5% får någon del av den nya URL:en fel om det görs manuellt. Frågor du @hryd kanske kan eller kan höra med SVAB kring:

1. Går det att scripta detta med search/replace och regexpar?
2. Går det samtidigt att kolla om varje RSS på huset faktiskt används på siten eller om den är orphan och då kan tas bort. Tas t.ex. 25% bort avlastar det SV:s RSS-kö ordentligt.
3. Klarar RSS:hämtningsklienten i SV av att följa 301:or om vi lägger det för de gamla adresserna?

**Comment by magnivar** [comment]
Löst så som föreslagits!
