### ISSUE TITLE
<br> saknas mellan bilder i kontaktrutan på Komin?

### ISSUE THREAD

**Issue by Svempan** [malmostad/sitevision_assets#328]
Henrik, jag tror du förstår problemet i texten från Tove nedan. Du kan också kolla med Mårten om du behöver:

"Jag har frågor om kontaktboken och kontaktmodulens visningsbild på Komin men vet inte i nuläget vart jag vänder mig. I kontaktmodulen tillkom för en tid sedan funktionen att kunna välja visningsbild på person i kontaktrutan. Detta fungerar fint så länge det är en bild eller bilder i rätt format (beskurna till kvadratiskt format likt vinjettbilden som visas i en kontaktlista!) innan de läggs upp i kontaktboken. Vill jag visa flera bilder i kontaktrutan och flera bilder är ”för höga” så störs layouten helt. Detta borde fungera per automatik och korrelera med kontaktboken så att bilder visas på samma sätt oavsett format. Vem vänder jag mig till för att ställa frågor om detta?

Sida där bilder i kontaktboken funkar – men bara för att båda bilderna är kvadratiska: 
https://komin.malmo.se/Forvaltningar/Grundskoleforvaltningen/Stod-och-service-i-grundskoleforvaltningen/Kommunikation-och-marknadsforing/Webbarbete.html 

För övrigt ser det mestadels ut så här när visningsbilder visas, trots litet olika format, på flera personer i kontakt:
https://komin.malmo.se/Forvaltningar/Grundskoleforvaltningen/Var-organisation/Utbildningsomraden/Utbildningsomrade-Oster.html
https://komin.malmo.se/Forvaltningar/Grundskoleforvaltningen/Var-organisation/Utbildningsomraden/Utbildningsomrade-Samordning-och-stod.html "

**Comment by hryd** [comment]
Deployed fix i komin-test, återskapade en av sidorna du länkade, se här http://komin.test.malmo.se/4.2b56f4113ec05ff84f1f5cd.html. 

Testa och återkoppla @Svempan.

**Comment by olajoh1** [comment]
Sven, du måste återkoppla!

**Comment by Svempan** [comment]
Ser bra ut. Kör ut i prod vid tillfälle.

**Comment by hryd** [comment]
Ute i produktion. @olajoh1

**Comment by olajoh1** [comment]
bilderna linjerar ej med texten samt att namn renderas före bild

**Comment by nikjon76** [comment]
För att inte skriva över befintliga klasser i CSS behöver vi uppdatera malmo.css som ligger i Global Assets.

**Comment by Svempan** [comment]
Kan ni göra det?

**Comment by susjon11** [comment]
Mårten tittar på det

**Comment by martent** [comment]
Jag har gjort en ändring i Global Assets för detta.

@nikjon76, följande måste göras i Sitevision och `sitevision_assets` för att formateringen ska bli korrekt där:

* Ta bort den tillfälliga fixen i 158b4182523be15e8a6a4adf374aa4a8b91f9ee3
* Lägg `h2` i vcard-blocket innan `ìmg`.
* Lägg till en override i `sitevision_assets` för att få `h2` i `.vcard` i fetstil (`SiteVision.css` selectorn `a.body, body a, .body a` overridar den till att få normal vikt).

För att se ordningen på markupen, fetstilen och korrekt linjering av bilderna, se prototypen:
http://malmostad.github.io/prototypes/internal/clean/

Olas och Susannes bilder har vita pixlar överst i bilden vilket kan vara lite vilseledande för top-linjeringen, kolla jespers lite längre ned.

**Comment by magnivar** [comment]
Kollar om det fortfarande är aktuellt.

**Comment by tomasrobertsson** [comment]
Jag måste medge att jag här inte vet vad det är ni vill ska ske.
eller rättare sagt jag kan på komin inte se hur det ser ut idag (pga av att jag via VPN inte får några formtmallar alls på den sidan/kan inte ladda några externa resurser) och därmed inte heller se vad det är som ska ändras. 
Testar på test-komin och lägger in formatmallarna och JS direkt där, då får jag format och kod som körs men på motsvarande sida där
http://161.52.13.184/Forvaltningar/Grundskoleforvaltningen/Var-organisation/Utbildningsomraden/Utbildningsomrade-Oster.html
laddas inte data från 
https://webapps06.malmo.se/avatars-test/fahzej/small.jpg 
dvs jag tror sidan saknar den miniatyr som problemet rör.

Dvs jag behöver en ny problembeskrivning, en bild/sida som visar på felet (där ni visar vad som är fel) och då även på hur det ska se ut istället. Eller att ni sätter upp så att er testerver, när jag går via VPN, når er asset-server och även webapps06.

**Comment by martent** [comment]
@magnivar  Be ITS se till så att Thomas når den publika servern assets.malmo.se när han är på VPN.

**Comment by tomasrobertsson** [comment]
Och även webapps06 tror jag bestämt då ni har resurser även där.

**Comment by magnivar** [comment]
Har beställt access nu till båda.

**Comment by magnivar** [comment]
Tomas ska nu ha access till både assets och webapps06

**Comment by tomasrobertsson** [comment]
Tackar, nu flyter sidorna på mycket bättre.

**Comment by tomasrobertsson** [comment]
Denna har jag nog löst men oklart för mig hur jag gör deploy av css i ert system. Vet att vi gick igenom det vid startmötet men bäst att repetera.
Ändringen är i två steg. 
1: Flytta på bildelementet i sv_contacform
2; Lägga till bold till vcard h2 a i CSS. 

men hur deployar jag ny css?

**Comment by martent** [comment]
Du bygger en war-fil och deployar som servlet i SV. Kort + fullständig dokumentation:

https://github.com/malmostad/sitevision_assets/

**Comment by tomasrobertsson** [comment]
Då ligger det uppe på komin test. Som vanligt vid CSS-ändring måste man göra en refresh av sidan för att den ska laddas. 
https://komin.test.malmo.se/Forvaltningar/Grundskoleforvaltningen/Var-organisation/Utbildningsomraden/Utbildningsomrade-Oster.html
exempelvis. 
Ser väl ut som ni önskat?
@magnivar  och @martent 
ber om ursäkt för att jag inte hunnit detta tidigare.

**Comment by martent** [comment]
Ser rätt ut på sidan och i koden. Man borde nog göra ett mer provocerande exempel för att testa av det helt, med flera kontakter med olika format på bilderna typ de som finns på:

http://malmostad.github.io/prototypes/internal/clean/

**Comment by tomasrobertsson** [comment]
Har ni en sida med det så... annars lägg upp en och se hur det blir. Ni är mer bekanta med funktionen/användningen av er webb.
Jag tittar på det på måndag.

**Comment by tomasrobertsson** [comment]
Två dummy-bilder
https://komin.test.malmo.se/4.2b56f4113ec05ff84f1f5cd.html
hittar ingen sida, lyckas inte skapa en sida, där det finns riktiga bilder på test.

**Comment by tomasrobertsson** [comment]
http://komin.test.malmo.se/testarea/kontakt.html

**Comment by tomasrobertsson** [comment]
Tagit bort fixen, 158b418, även. Påverkade inte sidan.

**Comment by magnivar** [comment]
Är lite osäker på om denna är kvar i test eller ute i prod. @tomasrobertsson @Svempan

**Comment by tomasrobertsson** [comment]
denna ligger på komin.malmo.se
Inga ändringar gjorda som ska påverka på externa webben så har inte byggt/publicerat något där.

**Comment by magnivar** [comment]
@elilun14 Kan du bekräfta att detta är löst så kan vi stänga ärendet? äntligen...

**Comment by elilun14** [comment]
Ok att stänga detta. @magnivar

**Comment by magnivar** [comment]
@elilun14 du kunde ju stängt också... ska formulera mig annorlunda nästa gång 💃
