### ISSUE TITLE
Alias följer inte med Påverkansytan

### ISSUE THREAD

**Issue by Svempan** [malmostad/sitevision_assets#329]
Standard i Sitevision är vad jag förstår att om ett alias används till en sida så visas det i adressfältet. Så är det inte nu med Påverkansytan. Där byts url:en till SV:s långa sökväg. Om man klickar på påverkansytan på startsidan på www.test.malmo.se borde man komma till www.test.malmo.se/chatt (i adressfältet) men i stället kommer man till SV:s långa url. Rätt sida men fel adress.

**Comment by Svempan** [comment]
Detta gäller även "Just nu/Viktigt meddelande" där det också är önskvärt att alias följer med i adressfältet.

**Comment by Svempan** [comment]
Gäller även sektionsmeddelnaden (dock prio low)

**Comment by nikjon76** [comment]
Nu är Påverksytan i test justerad och utvisar enkel adress i adressfältet. Dock ser det ut som länken peka på fel sida.

**Comment by Svempan** [comment]
Hm. Ser inte ut att funka. Man ska hamna här: http://www.test.malmo.se/chatt
Inte här: http://www.test.malmo.se/Huvudnyheter/2015-04-10-SMHI-varnar-for-skorbjugg.html
Samma sida men olika URL.

**Comment by nikjon76** [comment]
Testmiljön är nu uppdaterad så att Påverksytan använder alias i länk adressen.

**Comment by Svempan** [comment]
Bra! Kan vi få till samma lösning för "Viktiga meddelanden" (och sektionsmeddelanden)?. Jag har lagt ut ett nu i TEST.

**Comment by Svempan** [comment]
Testade att byta adress för Påverkansytan till "/miljo" men det slår inte igenom?

**Comment by nikjon76** [comment]
Kan nu se att det finns två typer av Alias. Ena alias stöder korta adresser medans den andra inte gör det. Förmodar att detta är ett arv av tidigare versioner av SV då den äldre version stöder korta adresser default medans den nyare där man har valet att kryssa i korta adresser inte får genomslag av denna funktionalitet. Tyvärr går det inte att skapa alias som har stöd för korta adresser men det går att återanvända gamla alias.

**Comment by olajoh1** [comment]
Är det idé att du tar frågan till SV?

**Comment by olajoh1** [comment]
Inväntar uppgradering till 4.1

**Comment by magnivar** [comment]
Uppgradering gjord.. finns felet kvar? @Svempan

**Comment by magnivar** [comment]
30 Augusti 2017 ... är det inte dags att svara @Svempan ?

**Comment by Svempan** [comment]
OK. Funkar i TEST men inte i PROD

**Comment by magnivar** [comment]
@badwiz Kan du läsa in dig på denna och fundera vad som kan göras?

**Comment by badwiz** [comment]
Jag behöver ha liten guidning om vad "Påverkansytan" är för någon yta. Alla alias från startsidan, de som ligger i de båda sidfötterna, fungerar som de ska. Men jag antar att det är något annat som avses. Gärna länk och bild för tydlighetens skull.

**Comment by badwiz** [comment]
Behöver inte guidning längre. Hittade Påverkansytan när vi felsökte dubbla sidfoten

**Comment by badwiz** [comment]
Fixat (inte i mallen ännu), men behöver verifiera detta med hur det är löst på test.malmo.se. Väntar på att min VPN ska hoppa igång.

**Comment by badwiz** [comment]
Detta är fixat på denna sida: https://malmo.se/4.685fbbb5160dbb463c21f4f5.html Påverkansytan som ligger långt ner på sidan.

**Comment by magnivar** [comment]
@Svempan Kan du kolla att det blivit rätt?

**Comment by Svempan** [comment]
Förstår inte. Där ligger tre påverkansytor. Ingen av dem länkar till ett alias. Och de ligger som javascript på sidan?

**Comment by Svempan** [comment]
Ser inte var jag kan verifiera?

**Comment by badwiz** [comment]
@Svempan  https://malmo.se/4.685fbbb5160dbb463c21f4f5.html Detta är en dold sida med funktionen, så Påverkansytan är länkad med ett Alias.

**Comment by Svempan** [comment]
Funkar! :)

**Comment by magnivar** [comment]
Då stänger vi :)
