### ISSUE TITLE
Bilder följer inte med till Facebook

### ISSUE THREAD

**Issue by Svempan** [malmostad/sitevision_assets#331]
Jag har för mig att detta funkat tidigare men minns inte om vi kommit fram till varför det inte gör det längre. Man kan bara få med loggan.
![fbochmalmose](https://cloud.githubusercontent.com/assets/7701048/10508625/80314a40-7328-11e5-99bd-dc32771d5da9.JPG)
Jämför
![fbochvellingese](https://cloud.githubusercontent.com/assets/7701048/10508627/84235ddc-7328-11e5-9ccf-846391af7ac0.JPG)

@martent

**Comment by martent** [comment]
Loggan är det som ni beslöt att använda i SV eftersom det inte finns något sätt att styra urvalet där. Vi arbetade en del med att få rätt beskärning i just FB. Se #175.

I t.ex. bloggen så ges bilden på författaran som förslag till de sociala tjänsterna.

Vi diskuterade också att de flesta tidningar valt att låsa till sin logga för att förhindra olämpliga kombinationer av text och bild som de tidigare fick och som även ni kan få.

**Comment by olajoh1** [comment]
@Svempan Vill du gå vidare med denna eller kan vi stänga?
