### ISSUE TITLE
Funktionallitet i kontaktruta på Komin

### ISSUE THREAD

**Issue by Svempan** [malmostad/sitevision_assets#334]
Det gåt inte att ändra eller ta bort i kontaktrutan på Komin. Knapparna saknas. Se bild från malmo.se:
![saknadeknappar](https://cloud.githubusercontent.com/assets/7701048/11811712/65b22b78-a337-11e5-8125-f12690c9087d.JPG)
Jämför med denna på Komin:
Arbetsfält/verksamheter >  IT Malmö stad >  Mål & styrning >  Processkontoret >  IT Malmö stads processer.
![kontaktruta_komin](https://cloud.githubusercontent.com/assets/7701048/11811812/2c64fc78-a338-11e5-9660-43a79530a91c.JPG)

@olajoh1

**Comment by hryd** [comment]
Fixar på en gång @Svempan.

**Comment by hryd** [comment]
Testa och återkom @Svempan.

**Comment by Svempan** [comment]
Härligt! Ser ut att funka nu!
