### ISSUE TITLE
Webbvideo - inlinespelare

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#335]
Det ska vara möjligt att lägga valfritt antal inlinespelare på en sida. Fungerar inte. Exempel:

https://komin.malmo.se/Forvaltningar/Arbetsmarknads--gymnasie--och-vuxenutbildnings-forvaltningen/Verksamheter/JobbMalmo/Filmer-om-ungas-framtidsplaner.html

**Comment by nikjon76** [comment]
Webbvideo-inline är nu driftsatt i test miljön test.malmo.se.
Har lagt till testmoduler på sidan:
http://www.test.malmo.se/4.51821d07143bab87ba7b6fc.html

**Comment by olajoh1** [comment]
ok att driftsätta på intranät och malmo.se

**Comment by olajoh1** [comment]
Funkar inte i IE  11
http://malmo.se/Kommun--politik/Sa-arbetar-vi-med.../Det-digitala-Malmo.html

**Comment by magnivar** [comment]
Funkar hos mig. Kan du kolla vad som inte funkar?

**Comment by martent** [comment]
BrightCove kastar mängder med WARN från sina Javascript men inte när man klickar på video 2 och 3 som inte startar i IE11 så jag kan inte diagnostisera felet. Kan beror på att samma Javascript inkluderas för varje ny video på sidan men det är en vild gissning.

Det bästa är att låta Mickes konsult kolla vad som är fel. Sen får antagligen Bouvet ändra i SV.

**Comment by magnivar** [comment]
Detta är svaret från vår videoleveratör!


Hi Mikael,

This is a known issue with IE as it uses Flash to load the HLS rendition with the player, if you have more than one player on the page, the flash object will only load for the first one leaving the other players without videos.

To solve this issues, you would need to force the player to use MP4 renditions when loaded on IE, you can create a plugin and add it to the player this would be a JS file hosted in your side. If you need information on how to add the plugin to the player you can follow this document (https://support.brightcove.com/en/video-cloud/docs/configuring-player-plugins).

Here is a JS sample you can copy and host in your side to add it to the player:

http://cs1.brightcodes.net/rvanoni/testpages/forceMP4IE.js

Please let me know if you have any further questions or if there's anything else that I can assist you with. 

Thank you,
- Renato
The Brightcove

**Comment by martent** [comment]
## Tech-talk

Om scriptet ska in, lägg det inte i någon sida eller mall utan i en fil typ: 

https://github.com/malmostad/sitevision_assets/blob/master/src/javascripts/video-hacks.js

och lägg till den i bygg-scriptet runt:

https://github.com/malmostad/sitevision_assets/blob/master/Gruntfile.coffee#L47

Antingen som coffee om den ska ligga i coffee-transpiler-blocket, eller lägg till en concatenering av js-filen så den hamnar sist i application.js

**Comment by tomasrobertsson** [comment]
Det här ser ut att vara väl dokumenterat hur lösningen ska gå till. 
Jag kan avsätta tid att testa den.

**Comment by magnivar** [comment]
Gott, k?r :)

Skickat fr?n min iPhone

24 mars 2017 kl. 14:49 skrev tomasrobertsson <notifications@github.com<mailto:notifications@github.com>>:


Det h?r ser ut att vara v?l dokumenterat hur l?sningen ska g? till.
Jag kan avs?tta tid att testa den.

-

**Comment by tomasrobertsson** [comment]
Siktar på ha testat det inom en till två veckor.

**Comment by tomasrobertsson** [comment]
Testar sidan ni länkar till ovan i IE11 och den fungerar utan att jag gör något speciellt. 

Är detta problem ur världen nu, har brightcove uppdaterat på sin sida? IE använder än flash men det fungerar. Ska sägas att jag sitter med IE11 på Windows 8.

**Comment by tomasrobertsson** [comment]
Har nu även testat på malmo.se
http://malmo.se/Teststruktur/videotest.html
och där fungerar det inte.
Vad som är skillnaden vet jag inte men det får jag undersöka.

**Comment by tomasrobertsson** [comment]
Skillnaden mellan de två, på test och prod, är ytterst liten. Bara en liten ändring i velocity. 

Ändringen bekräftad på prod, manuell ändring i filen. Har bygget en ny version och lagt denna på test, där fungerar än flera inline-filer i IE
http://www.test.malmo.se/4.51821d07143bab87ba7b6fc.html

Säg bara till så puttar jag upp denna även på malmo.se
Har lagt upp ändringen här, i comit.

**Comment by magnivar** [comment]
Var så god att putta upp den. Funkar bra för mig. Vi får kolla den när vi uppgraderat till 4.2.2 på tisdag också

**Comment by tomasrobertsson** [comment]
Jag tycker vi tar en sak i taget, dvs vi uppdaterat först SV och sedan denna.

**Comment by tomasrobertsson** [comment]
Senaste version upplagd på nya malmö, SV4. 
Commit här med tag v1.02

**Comment by magnivar** [comment]
Detta är fixat i InlineVideo-portlet och nu tar vi steget över att ersätta portleten, som måste redigeras i klassiskt läge, med ett Element.
