### ISSUE TITLE
Dekorationen "Box" på Komin till malmo.se

### ISSUE THREAD

**Issue by Svempan** [malmostad/sitevision_assets#337]
Av någon outgrundlig anledning så blev inte dekorationen "Box" införd på malmo.se i höstas. Börja med TEST. Därefter tar vi PROD.
@olajoh1

**Comment by Svempan** [comment]
Här är manual för Intranätet. Tror det klarnar efter du läst den. 
Detta vill vi även ha på malmo.se. Börja med Prod.
[Box.docx](https://github.com/malmostad/sitevision_assets/files/263084/Box.docx)

**Comment by nikjon76** [comment]
Varken i komin-test eller komin kan jag finna Box dekorationen. Ser att funktionen finns då den är applicerad på vissa sidor. När jag följer instruktionerna i Box.docx får jag endast upp dekorationer för: Huvudbild, Sekundärbild, Fokusyta- info, Fokusyta- agera, Tabell, Läs mer, Faktaruta, Old, Old...

Hur kommer jag åt Box dekorationen?

**Comment by Svempan** [comment]
Ser att man bytt namn på layouten. Heter "Fakta" och "Läs mer". Har samma funktion men namnsättningen ska göra det lättare för redaktörerna att förstå. Ska vara samma på malmo.se alltså.

**Comment by magnivar** [comment]
Sven visar Magnus var det finns i komin.

**Comment by tomasrobertsson** [comment]
Vad jag kan hitta när jag nu tittar på detta ärende så finns denna dekoration publicerad på malmö.se redan under namnet Faktaruta och Läs mer. Dvs inget för mig att göra här @magnivar vad jag kan se. 
exempelvis testad här
http://www.malmo.se/Teststruktur/Faktaruta-och-Las-mer.html

**Comment by magnivar** [comment]
Ja men så bra :) kan @Svempan kolla? Finns det andra ställen?

**Comment by Svempan** [comment]
Namnen på dekorationerna verkar finnas men inte funktionaliteten vad jag kan se. Jämför dessa exempel:
http://www.malmo.se/Teststruktur/Sven/Box.html
http://komin.malmo.se/Sven/Fakta.html
@magnivar

**Comment by tomasrobertsson** [comment]
Jag applicerar Rubrik 2 på rubriken på den ena och då får den rätt format. Det formatet läggs väl inte till automatiskt på komin?

**Comment by Svempan** [comment]
Toppen! Det funkar!
