### ISSUE TITLE
Sök på intranätet och malmo.se indexerar meny och sidfot

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#339]
Vår sökmotor indexerar meny och sidfot på intranätet. Vill du kontrollera att förutsättningarna enligt Siteseeker är uppfyllda.

---

Om SiteSeeker inte själv lyckas identifiera sidfoten som navigationsavsnitt så är den bästa och snabbaste lösningen att lägga
sidfoten inom ett  html-kod för sidfot läggs här </--eri-no-index--> blocket

Detta tvingar SiteSeeker att inte indexera upp det markerade innehållet.

**Comment by nikjon76** [comment]
Har nu lagt till skript på komin.test.malmo.se som uppdaterar Menyer och Sidhuvud/sidfot med identifierare för att inte indexeras i SiteSeeker.

**Comment by olajoh1** [comment]
ok

**Comment by nikjon76** [comment]
Nu är komin.se uppdaterad med skript för att ta bort indexering av meny och sidhuvud/sidfot

**Comment by olajoh1** [comment]
Ok, startar omindexering.

**Comment by nikjon76** [comment]
På grund av att Sitevision html element gör förskjutningar i mallarna när ’ ’ inkluderas  och därmed förändrar utformningen av sidorna bör detta äga rum vid tex uppgradering till ny Sitevision version då mallarna måste ses över.
Det går tyvärr inte att läsa in markup kommentarerna via Javascript.  avsnitt måste finnas i den statiska HTML:en och får 
inte renderas med hjälp av JavaScript. Detta pga att SiteSeeker inte exekverar JavaScript kod.

**Comment by olajoh1** [comment]
Mårten, vill du göra en bedömning

**Comment by martent** [comment]
@jesperbylund fördelar alla tickets i nuläget, nya som gamla.

**Comment by magnivar** [comment]
@tomasrobertsson 
Kan du läsa igenom denna och återkomma med en kommentar?

**Comment by olajoh1** [comment]
OBS gäller både malmo.se och intranätet

**Comment by magnivar** [comment]
@EllinorHallett har fått detta och tittar på det.

**Comment by EllinorHallett** [comment]
Detta är inlagt i prod på malmo.se och Komin.

**Comment by olajoh1** [comment]
Fungerar inte. Om du t.ex. sökning på "fackliga" på Komin för du hundratals träffar på flera förvaltningar pga att ordet finns i big foioten.

**Comment by EllinorHallett** [comment]
Vad är det för sök ni använder? Är det SiteVision standard eller har ni ex siteseeker?

**Comment by EllinorHallett** [comment]
Jag har nu ändrat koden till en annan variant. Testa igen och återkom om det löst problemet.

**Comment by EllinorHallett** [comment]
Den har nu gått ner från 600 träffar på ex Möbler på stadsförvaltningen till 66 stycken.
Gissningsvis är de träffar som är kvar av anledningen att  den tar med de sidorna som finns i menyn i WAGen.
För att lösa detta behöver ni lägga in samma kod som jag lagt in i SIteVision, även runt menyn i WAGen.

Denna innan menyn:
< !--eri-no-index-->

Denna efter menyn:
 < !--/eri-no-index-->

(Dock utan mellanrum mellan första taggen och utropstecknet. Fick lägga in detta då den inte ville visa sig i kommentaren annars)

Vem ser till att detta bli gjort?
@olajoh1 @magnivar

**Comment by magnivar** [comment]
@olajoh1 kollar med SIteseeker för eri-no-index finns

**Comment by olajoh1** [comment]
Löst
