### ISSUE TITLE
Uppdatering kontaktformulär 

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#340]
I kontaktformuläret för komin ska epostadress göras obligatoriskt. OBS detta gäller ej externwebben.

**Comment by magnivar** [comment]
Alla formulär på komin borde ha obligatorisk epost.
Var ligger formuläret? (magnus undrar)
exempelsida:
https://komin.malmo.se/Forvaltningar/Stadskontoret/Mal--styrning/Intern-kontroll.html

**Comment by martent** [comment]
Kontaktformuläret finns i portleten för Kontaktrutan:

https://github.com/malmostad/sv-contact-portlet

**Comment by tomasrobertsson** [comment]
![image](https://cloud.githubusercontent.com/assets/15670239/20628466/6075fcca-b326-11e6-8b75-b29ec0f77334.png)
Ett första steg klart, tänkte ni skulle få chans att säga bu eller bä om valet av väg. 
Helt enkelt göra det till en inställning i portleten om epost ska krävas eller ej. 

Andra änden, dvs få ut denna inställning i portleten är kvar att göra.

**Comment by tomasrobertsson** [comment]
Nu ligger det på er test server för komin en version av kontaktportleten med inställningen ovan adderad. Dvs ni kan för varje sida där ni lägger till denna portlet ställa in om epost ska krävas eller ej. 
Samma portlet finns även på produktion varvid jag valde denna väg. 

Jag ser att det idag inte finns någon validering av formuläret på klientsidan. Det ingår inte i detta uppdrag att lägga till det men jag tycker det vore en bra idé att göra det. Standardvalideringen, HTML, fungerarar oftast bra nog och går snabbt att lägga in. 
@magnivar ta gärna en titt på sidan ni länkade in ovan, där har jag satt att epost ska krävas.

**Comment by olajoh1** [comment]
Fältet epost nedan i formuläret ska vara obligatoriskt. Inget annat.

![image](https://cloud.githubusercontent.com/assets/6176181/20714910/ccd5f364-b64d-11e6-9a59-10b46e3f465b.png)

**Comment by tomasrobertsson** [comment]
Bara epost? Idag är namn, meddelande avser  och meddelandet obligatoriskt.

Jag kan göra om så att ni kan ställa in för alla fält om de ska vara krav eller ej, idag är övriga satta i koden att de ska vara obligatoriska. 
Och oj vad fint formuläret är med formatmall, den ser jag inte på test-servern.

**Comment by tomasrobertsson** [comment]
Har lagt på format (css) och script (js) från assets.malmö på komin test så att sidorna ser ut, och fungerar, som de ska även för mig som går in via VPN.

**Comment by tomasrobertsson** [comment]
Behöver ett klargörande av det @olajoh1 skrev ovan.
Jag har förstått det som att epost ska göras obligatoriskt och har lagt in det som ett val i inställningarna. 
Är detta korrekt eller önskar ni något annat/mer?

**Comment by olajoh1** [comment]
Vi är ute efter att det alltid är obligatoriskt, ej valbart.

**Comment by tomasrobertsson** [comment]
Obligatoriskt enbart för malmö interna då. Dvs inga inställningar i portleten men alltid obligatoriskt på malmö interna? 
Då får jag göra om och lägga in det hela på lite annat vis än jag gjort idag.

**Comment by tomasrobertsson** [comment]
Okej, nu har jag en version där inställningen görs i kontaktruta.properties, dvs ni ställer in denna till true för komin och false för externa webben. 

Ingen inställningen vid installation av portlet på sidorna utan bara en vid deploy av portleten.

**Comment by martent** [comment]
Det ser ut som om sv-contact-portlet/config/ i portletkoden tar höjd för individuell konfiguration för intern, extern samt för test och prod. Har du lagt inställningen så att den inte behöver ändras vid varje deploy utan använder miljö-specifik konfiguration?

En hel del i config för portletten är information som inte är hemlig. En variant är att lägga över all den i Git-hanterade filer och lägga lösenord och annat i en kontaktruta_secrets.properties som man sätter gitignore på.

Ovanstående avgör du själv bäst, välj det som är enklast för löpande hantering och deploy och är mest stabilt.

**Comment by tomasrobertsson** [comment]
Jag kan dela upp det som du skriver, i två olika filer och lägga in de data som inte är känsliga i GIT, dvs ur nuvarande ta ut
kontaktruta.contact_us_header=Kontakt
kontaktruta.link_email=true
kontaktruta.link_username=true
kontaktruta.show_avatar=true
kontaktruta.require_email=true
och lägga i fil som vi skickar upp till GIT som du säger. 

Databas-inställningar förstår jag att ni inte vill ha där, de måste än hanteras på annat vis. 
Ifall ni vill kan jag titta på att flytta ut den filen, med databasdata, helt från portleten, att den läggs på annan plats som inte påverkas vid en deploy.

**Comment by martent** [comment]
Du tänker på att lägga den direkt på respektive server? Det stämmer väl överens med hur vi gör med andra system.

**Comment by tomasrobertsson** [comment]
Precis.  Var lägger ni inställningsfiler idag? Ah, det kan jag titta över själv.

**Comment by martent** [comment]
👍

**Comment by tomasrobertsson** [comment]
mmh, hitta själv sade jag... Om du vet kan du alltid berätta så slipper jag leta... kan säga i annat projekt jag jobbar med läggs ALLT i tomcat/bin
Där lägger ivartfall inte ni något.

**Comment by martent** [comment]
@magnivar tar frågan med driften så att den:

1. Ligger i en katalog där den naturligt flyttas med om man ersätter
en server med en annan för samma tjänst/miljö. t.ex. malmo.se-prod med
en ny malmo.se-prod.
2. Att filen **inte** flyttas med när man tar en färsk kopia från
t.ex. malmo.se-prod till malmo.se-test. I det fallet ska configfilen
för malmo.se-test liggar kvar utan att skrivas över.

**Comment by tomasrobertsson** [comment]
Enklast är om den kan läggas inom mappen för Sitevision då den sökvägen kan byggas upp relativt installationsmappen. Exempelvis i mapp om Sitevision/tomcat/webapps/conf borde fungera. Eller ett steg upp i den sökvägen. 
Nu vet jag inte hur ni gör vid flytt/migrering mellan servar, om den mappen berörs.

**Comment by tomasrobertsson** [comment]
Har verifierat att det går att lägga kontaktrutans properties var ni vill på filsystemet. Om ni vill lösa den på det viset går det alltså men det finns ju alltid en risk när man flyttar ut config från projektet, exempelvis svårighet när systemet ska kopieras till nya maskiner. 
Ni säger om ni vill ha med det i denna milestone/denna deploy. 
J

**Comment by tomasrobertsson** [comment]
Jag tittar och verifierar min version av kontakruta mot de olika servrarna. Blir konfunderad när jag går in på Malmo.se för att hämta kontaktruta.properties där.
Den filen saknar de första raderna, de "öppna", dvs
```
kontaktruta.contact_us_header=Kontakt
kontaktruta.link_email=true
kontaktruta.link_username=true
kontaktruta.show_avatar=false
```
Vilken version av kontaktruta ligger där? Den version jag har kod för kraschar om något av dessa fält saknas.  Ser att det där ligger en backup från 2014-10-03, att senast filerna ändrats är 2015-04-14
Den på malmo.se verkar inte vara av senaste version men den version jag skapar ska väl även ut där? 

Jag lägger till fälten ovan, i kontakruta.properties, med samma config som på test.malmo.se

**Comment by martent** [comment]
Den senaste releasen ska vara gjord 11 september 2015:
https://github.com/malmostad/sv-contact-portlet/releases

Det anges inte i release notes men den verkar bara vara gjord för Komin.

Men de configfilerna deployas inte i releasen utan redigeras på plats. Jämför motsvarande config på Komin, de fälten ser ut som de kom till när kontaktrutan anpassades för att både funka på malmo.se och Komin.

**Comment by tomasrobertsson** [comment]
Det är inte sådan skillnad/uppställning i koden att det finns delar av kod enbart för komin respektive externa webben. Själva kodbasen är densamma för de två webbarna, enda skillnaden är i vilken property-fil som används. 
Koden använder idag ett antal fält från kontaktruta.properties. Om dessa fält inte finns kraschar den. Därav är min analys att senaste release bara lagts ut på komin samt test.malmo.se

**Comment by olajoh1** [comment]
Se epostadressen i svarsmailen.

![obl_epost](https://cloud.githubusercontent.com/assets/6176181/21389351/8e79297a-c781-11e6-84a1-c408361bcda9.PNG)

**Comment by magnivar** [comment]
Funkar korrekt här:
![capture_mail](https://cloud.githubusercontent.com/assets/22590738/21389500/62fc2a94-c782-11e6-8fcb-d63002e38ad6.png)

**Comment by olajoh1** [comment]
@magnivar Vi kollar inte på samma sak. Jag tittar på inkommande till mottagaren. Du tittar på kvittensen du får som avsändare.

**Comment by olajoh1** [comment]
Felet uppkom av en slump, men när jag lämnade epost-fältet (med korrekt ifylld adress) för att fortsätta att fylla i andra fält och sedan gick tillbaka för att redigera det på nytt med ett fel. Då accepteras det första korrekt ifyllda epostadressen istället för att göra en indatakontroll på senast inmatade.  

![image](https://cloud.githubusercontent.com/assets/6176181/21389718/55a38396-c783-11e6-853f-6db10e9c9543.png)

**Comment by tomasrobertsson** [comment]
Detta fel du nu ser är orelaterat till ändringen i den mån att jag inte varit inne och ändrat i dessa delar. Validering av epost fanns sedan tidigare, den har bara aktiverats av detta. Men givetvis ska fel i denna hanteras.

**Comment by tomasrobertsson** [comment]
Jag kommer lägga ut kontakformuläret på test.malmo.se under morgondagen. Om den ser bra ut där lägger jag senare, ingen brådska, med klartecken från er även på produktion.

**Comment by tomasrobertsson** [comment]
Lagt upp det på test.malmo.se och kan, som väntat, inte se någon förändring. De ändringar som är gjorda ska inte påverka på malmo.se
Ni får gärna kontrollera det samt säga hur jag ska göra med deploy på malmo.se av denna. När.

**Comment by magnivar** [comment]
@olajoh1 kan du kolla och notera om den är klar för deploy på malmo.se

**Comment by olajoh1** [comment]
kan inte testa. Får "tekniskt fel. Försök senare".

Såg nu att en blankrad saknas. Se bild nedan.

![image](https://cloud.githubusercontent.com/assets/6176181/21454638/60ae4486-c91a-11e6-893c-c7749ede3a2a.png)

**Comment by tomasrobertsson** [comment]
Kan ni titta om inte samma fel, saknad blankrad, finns även på komin? 
Och gärna, när ni rapporterar fel länka till sidan där det syns. Sparar mig många klick.

**Comment by magnivar** [comment]
@olajoh1 kolla status...

**Comment by olajoh1** [comment]
epostfältet är nu obligatoriskt.
