### ISSUE TITLE
Bugg i kontaktrutan

### ISSUE THREAD

**Issue by Svempan** [malmostad/sitevision_assets#342]
En ny bugg har dykt upp i kontaktrutan. I fallet nedan finns inte stadsdelen Innerstaden som val i stadsdelsväljaren.
![innerstaden_saknas](https://cloud.githubusercontent.com/assets/7701048/15423320/3e938dcc-1e7d-11e6-8247-94bbacba0906.jpg)

Denna sida:
http://malmo.se/editor/index.jsp?objectId=4.5d8108001222c393c0080003530

@olajoh1

**Comment by nikjon76** [comment]
Denna del av portlet har inte justerats och alla alternativ finns kval i koden. För tillfället utvisas inga stadsområden via dropdown när tex. Winnie Nilsson adderas till listan. Vad finns det för fler beroenden gällande stadsområden.

**Java portlet**
        this.areas = new LinkedHashMap<String,String>();
        areas.put("", "Välj stadsområde");
        areas.put("NORR", "Norr");
        areas.put("ÖSTER", "Öster");
        areas.put("SÖDER", "Söder");
        areas.put("VÄSTER", "Väster");
        areas.put("INNERSTADEN", "Innerstaden");  

**Markup**
<select name="district" id="district">
        <option selected="selected" value="">Välj stadsområde</option>
 </select>

**SV Metadata**
[{"cn":"Vård \u0026 omsorg, stadsområde Norr","dn":"cn\u003dvård \u0026 omsorg\\, stadsområde norr,ou\u003dfunktionskonton,ou\u003dorganisation och funktion,ou\u003dsitevision,o\u003dmalmo","type":2,"attributes":["mail","telephone","visitingAddress"],"district":"NORR"},{"cn":"Vård \u0026 omsorg, stadsområde Öster","dn":"cn\u003dvård \u0026 omsorg\\, stadsområde öster,ou\u003dfunktionskonton,ou\u003dorganisation och funktion,ou\u003dsitevision,o\u003dmalmo","type":2,"attributes":["mail","telephone","visitingAddress"],"district":"ÖSTER"},{"cn":"Vård \u0026 omsorg, stadsområde Söder","dn":"cn\u003dvård \u0026 omsorg\\, stadsområde söder,ou\u003dfunktionskonton,ou\u003dorganisation och funktion,ou\u003dsitevision,o\u003dmalmo","type":2,"attributes":["mail","telephone","visitingAddress"],"district":"SÖDER"},{"cn":"Vård \u0026 omsorg, stadsområde Innerstaden","dn":"cn\u003dvård \u0026 omsorg\\, stadsområde innerstaden,ou\u003dfunktionskonton,ou\u003dorganisation och funktion,ou\u003dsitevision,o\u003dmalmo","type":2,"attributes":["mail","telephone","visitingAddress"],"district":"INNERSTADEN"},{"cn":"Vård \u0026 omsorg, stadsområde Väster","dn":"cn\u003dvård \u0026 omsorg\\, stadsområde väster,ou\u003dfunktionskonton,ou\u003dorganisation och funktion,ou\u003dsitevision,o\u003dmalmo","type":2,"attributes":["mail","telephone","visitingAddress"],"district":"VÄSTER"}]

**Comment by olajoh1** [comment]
ok
