### ISSUE TITLE
Fritext i kontaktruta ärvs inte

### ISSUE THREAD

**Issue by Svempan** [malmostad/sitevision_assets#343]
Det verkar som att fritexten inte följer med när man väljer "Ärv ovanifrån".
Exempel:
http://malmo.se/Forskola--utbildning/Grundskola/Grundskolor-och-forskoleklass/Att-valja-skola.html Fritext: ” Har du frågor, kontakta oss gärna.
@olajoh1

**Comment by nikjon76** [comment]
Funktionen 'Ärv ovanifrån' ser ut att fungera men den har inget att ärva och därför utvisas inget innehåll.

**Comment by martent** [comment]
@perber14 Kontaktar redaktören på Utbildning och meddelar att funktionaliteten inte ändras.

**Comment by perber14** [comment]
Har varit i kontakt med Carina på Grundskolan. Ej bugg. Information tillagd i wikin.
