### ISSUE TITLE
Wikin-kontaktboken "minns inte" inloggning 

### ISSUE THREAD

**Issue by Svempan** [malmostad/sitevision_assets#345]
Om man från nytt webbläsarfönster går direkt till:
https://webapps09.malmo.se/wiki/Funktionskontakter och där klickar på länken:
"Gå direkt till: https://webapps06.malmo.se/dashboard/group_contacts"
Då får man meddelande "Du saknar behörighet till detta"
Om man däremot går via dashboarden så funkar det dock.

**Comment by martent** [comment]
Beror troligen på att man är inloggad på Min sida med en webbläsare men är i en annan webbläsare när man klickar på länken. Olika webbläsare delar inte session och inloggingar.
