### ISSUE TITLE
Kontaktrutan på Komin funkar inte för funktionskontakter

### ISSUE THREAD

**Issue by Svempan** [malmostad/sitevision_assets#346]
Det verkar som att personliga kontakter med Förnamn Efternamn funkar att klicka på och skickar besökaren till rätt sida i kontaktboken. Detta funkar dock inte med funktionskontakter - då får man en 404-sida.
@elilun14

**Comment by martent** [comment]
Eventuellt relaterad till #338

**Comment by magnivar** [comment]
Dubblett till #338
