### ISSUE TITLE
Testning av menyn på menysidor

### ISSUE THREAD

**Issue by martent** [malmostad/sitevision_assets#347]
@tomasrobertsson på Bouvet har ändrat i scriptmodulen för menyn på menysidor (startsidor) så att den inte genererar så mycket felmeddelande.

Den är utlagd i test och ska testas av innan de lägger den i prod. @magnivar ser till att den blir testad och låter @Svempan verifiera, även hantering av metadata för den så att de fungerar som det ska (eller andra administrationsgrepp). Produktionssättning får synkas så att @magnivar och @Svempan kan kolla av när @tomasrobertsson lägger ut i produktion.

Aktiviteten ingår som en del i den hälsocheck Bouvet nu gör.

**Comment by Svempan** [comment]
Har testat i TEST  lite snabbt och hittar inga konstigheter

**Comment by magnivar** [comment]
Charlotta kom tillbaka får sjukfrånvaro och har problem med header. Den syns inte alls. Vet inte om det är lokalt på just den datorn och hon kan inte starta om då en annan användare är inloggad på den.
Skärmdump
![fel pa menyn](https://cloud.githubusercontent.com/assets/22590738/20130911/5048ebb0-a65a-11e6-830c-2f7875b5910f.png)
@tomasrobertsson @martent

**Comment by tomasrobertsson** [comment]
Detta borde inte vara relaterat till den ändring jag gjorde igår.
Nu ska ni veta att jag vet inte riktigt hur det ska se ut på den sidan men det ser ut som att sidmallar inte laddats som de ska. Dvs troligen att resurser från assets.malmo.se inte har laddats.

**Comment by martent** [comment]
Det har inget med @tomasrobertsson release att göra.

Detta beror, som jag skrev i mitt mailsvar, på att webbläsaren inte fått css:er och javascript (Global Assets) från assets.malmo.se.

Och det i sig beror antingen på:

1. En nätmässig omständighet/tillfällighet; att nätet blockats eller inte fungerat mellan hennes uppkoppling och asset-servern. Vi har tidigare sett att DNS:er för vissa typer av uppkopplingar har fallerat under en stund eller att åtkomst till vissa servrar, även om denna är publik, inte fungerat från plattformsdatorer.

2. Att assets.malmo.se-servern har varit överbelastad. Jag diskuterade risken för detta med Magnus och Johnny igår.

@magnivar Tar du lead på att undersöka och också skapa dig en uppfattning om hur många runt er som drabbats. Är det en? Eller finns det fler på er avdelning som drabbats av det. Och vilka uppkopplingar och enheter har det drabbat. Kalla in mig till Stadskontoret om det är upprepningsbart på flera datorer.

**Comment by magnivar** [comment]
Klar, testat och ligger i PROD
