### ISSUE TITLE
Fellänkade start-banners

### ISSUE THREAD

**Issue by martent** [malmostad/sitevision_assets#348]
I den hälsocheck som Bouvet gör av malmo.se har @tomasrobertsson upptäkt att en del startbanners är fellänkade, länken som ligger i metadata. Han kollar om SV:s länkkontroll rapporterar detta så att det går att fixa redaktionell utifrån en länkkontroll. Lägg in dina slutsatser i en kommentar i denna ticketen, @tomasrobertsson.

@Svempan och kanske @olajoh1  måste involveras kring hur länkkontroller görs och hur man kan använda den för sökning av fellänkade banners. Eventuellt används en annan länkkontroll än SV:s egen?

Detta verkar inte vara ett engångproblem utan något som måste tillhöra den dagliga hanteringen av banners.

@magnivar samordnar aktiviteten.

Aktiviteten ingår som en del i den hälsocheck Bouvet nu gör.

**Comment by martent** [comment]
@Svempan Ber redaktörer att inte spara gamla bannerlänkar i inställningarna. Och tar bort dem som ligger där.

@tomasrobertsson Ändra bannerlösningen så att ett kontrollerat felmeddelande loggas i stället för att hela felet kastas i loggen.

**Comment by tomasrobertsson** [comment]
Jag har en lösning nu som gör så att inga fel kastas. Istället renderas bannern som den ska men länken kommer eventuellt vara trasig. 
För övrigt har ni i min lokala kopia cirka 3000 trasiga länkar. Jag ska försöka sätta ihop det i en vettig rapport till er.

**Comment by tomasrobertsson** [comment]
Har uppdaterat Menu och även Banner på er testserver för malmö extern
Uppdatering av Menu enbart omstuvning av kod, tog bort element inte ska fungera i Sitevision 4. Ingen garanti från mig att scriptet felfritt fungerar i SV4 men chansen har ökat med denna ändring.

Banner uppdaterad så att den inte kastar fel, istället kommer länken från bannern gå till (standard) 404.

**Comment by Svempan** [comment]
Metadata på startbanner (och bildnyheter) kopplade till avpublicerade sidor borttaget

**Comment by tomasrobertsson** [comment]
@Svempan är det en kommentar på min ändring ovan heller har ni gjort något i systemet? 
Ändringen jag gjort använder metadata men kastar inte fel om länken är fel.

**Comment by tomasrobertsson** [comment]
Jag tog en titt på loggarna efter att jag lagt upp ändringarna ovan på produktion. 
Resultatet av dessa ändringar var att "felet", för menyn, flyttades från Error (med Java-exception) till Warn med en rad varning om trasig länk. 
Dvs problemet i grunden är de data som traverseras av menyn, kanske att det kan gå att putsa lite mer på scriptet att ta bort även varningen men den är nog inte fel att ha kvar. 
Logfilen har prel. minskat i storlek med cirka 200 MB av denna lilla ändring och kan minskas mer.

**Comment by magnivar** [comment]
Magnus kör en länkkontroll måndag kväll och skickar listan till toomasrobertsson, svempan och ola

**Comment by magnivar** [comment]
länkkontrollen gav 1450 fel och tog 2h10m att genomföra. Magnus ser om det går att sortera listan för att kunna skicka relevanta delar till förvaltningsredaktörer.

**Comment by tomasrobertsson** [comment]
Är det något kvar i denna som jag ska göra? Eller ska jag betrakta denna som färdig från Bouvets håll?

**Comment by magnivar** [comment]
vill du ha länkfels listorna? Hjälper det dig att avgöra om det är de länkfelen som hamnar i loggen?

**Comment by tomasrobertsson** [comment]
Vet inte vad jag ska göra med dem egentligen. Det är mer ett arbete för redaktörerna att städa i webben. Just den portlet vi har i detta ärende är nog fixad så bra det går, dvs felen hanteras bättre nu än innan jag kom in i projektet.

**Comment by perber14** [comment]
Fixad i samband med hälsochecken tidigare i höstas.
