### ISSUE TITLE
Proxymoduler, anpassa meddelande

### ISSUE THREAD

**Issue by martent** [malmostad/sitevision_assets#349]
Gå igenom proxyportlets och lägg in ett humant felmeddelande istället för det tekniska som kommer om källtjänsten inte går att nå.

@tomasrobertsson ger ett förslag på text som @Svempan godkänner/justerar.

@magnivar håller i aktiviteten.

Aktiviteten ingår som en del i den hälsocheck Bouvet nu gör.

**Comment by magnivar** [comment]
Alla proxymoduler skall ha den nya texten.

**Comment by tomasrobertsson** [comment]
Jag tittar på denna senare under veckan.

**Comment by tomasrobertsson** [comment]
Titt senare i veckan blev idag. 
Vilka olika fel är det ni vill hantera specifikt? Ska användarna får en generell text eller ska vi ge mer detaljerade fel. 
För proxyportlet kan man, som ni vet,  ställa in ett generella fel eller specificera på olika, 401, 404, 500 osv. 
Vid granulitet önskas? Jag kan sätta upp möjlighet att skapa olika för alla olika nivåer, generellt meddelande på alla, så kan ni/vi senare sätta upp exakt den text som passar.

**Comment by martent** [comment]
Tar du denna @magnivar?

**Comment by magnivar** [comment]
Förslag: (eller vad säger @Svempan)
401 - Du har inte behörighet att besöka sidan.
404 - Sidan du försöker nå hittas inte.
500 - Det är ett tekniskt fel på sidan du vill besöka och kan inte visas.
Övriga: Det går inte att visa sidan.

**Comment by martent** [comment]
För proxy-modulerna handlar det inte om "sidan" utan en mer eller mindre stor ruta på en sida, t.ex. *Händer idag*. Så meddelandet får bli på temat "informationen kunde tyvärr inte hämtas" eller liknande.

**Comment by tomasrobertsson** [comment]
Korta koncisa meddelanden som är ganska lika för kunden men som ni/vi som ska felsöka kan säga vad som går fel. 
Jag implementerar detta på test för externa webben under dagen.

**Comment by tomasrobertsson** [comment]
Ett test
http://www.test.malmo.se/Teststruktur/Proxy-test.html
där texten kommer från del på denna sida
http://www.test.malmo.se/Redaktorer/Felsida-rss.html
 Ger 404-fel eftersom adressen i portleten är medvetet fel.

**Comment by perber14** [comment]
Jag tycker att texterna borde vara:

401 - Nu blev del fel! Du har inte behörighet att visa informationen.
404 - Nu blev det fel! Det går inte att hitta informationen.
505 - Nu blev det fel! Det går inte att visa informationen.
Övriga fel - Nu blev det fel! Det går inte att visa informationen.

Tydlig fel-info och lite mer aktivt språk, som ju är bra för läsförståelsen.

OK, @Svempan?

**Comment by Svempan** [comment]
OK! @perber14

**Comment by tomasrobertsson** [comment]
Jag uppdaterar med dessa strängar i mitt testexempel.

**Comment by tomasrobertsson** [comment]
![image](https://cloud.githubusercontent.com/assets/15670239/21357078/36aad462-c6d4-11e6-9618-16db9bcf5167.png)
det är enkelt att ändra när vi väl implementerat det. Det "jobbiga" är att ställa in alla proxymodeller, peka dem på dessa fält.

**Comment by tomasrobertsson** [comment]
Publicerade på malmo.se och komin.malmo.se

**Comment by tomasrobertsson** [comment]
Har hittat en till proxy-portlet som ligger i en mall (för startsidan). Testar lite på test-miljön och fixar även denna.

**Comment by tomasrobertsson** [comment]
Uppdaterat och jag tog mig rätten att publicera det direkt på produktion. Hoppas ni inte går i taket för det. 

Dvs den lösning som finns nu är:
1: För proxyportlets på sidor finns det en sida med felmeddelanden som dessa kan använda. 
2: För proxyportlets i mallar finns det en annan MALL med samma felmeddelande som för sidor men enbart användbar för portlets i mallar. Den portlet som använder dessa är den som hämtar bloggar på startsidan.. 

För båda dessa gäller att ni kan enkelt ändra existerande fel, nya fel läggs till på sidan/mallen samt länkas dit i de portlets som ska hantera dessa fel.

**Comment by magnivar** [comment]
Klart 2016
