### ISSUE TITLE
Scriptning i SV - filer

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#350]
Vilka möjligheter finns det att scripta bort ej upplänkade filer i SV?

**Comment by tomasrobertsson** [comment]
Det är något ni får ta med Sitevision. De kan eventuellt ta fram en rapport över vilka filer som inte används. Det är inget som vi på Bouvet kan hjälpa er med.
Sitevision ger er INTE några verktyg för att radera resurser då, som de säger, det garanterat kommer gå fel i något fall.

**Comment by olajoh1** [comment]
Tack. Vi behöver en rapport för resp . web som visar vilka filer och bilder som ej är upplänkade. Rappporterna ska sorteras på url:er.

**Comment by tomasrobertsson** [comment]
Önskar ni att jag tar kontakt med Sitevision för att se vad de kan erbjuda? Som sagt kan de eventuellt hjälpa er med detta, säkert kan jag inte veta utan att prata med dem.

**Comment by magnivar** [comment]
Magnus beställer script av Sitevision för att se hur långt man kommer med detta (enligt samtal idag med Anders Hurtig)

**Comment by magnivar** [comment]
Vi inväntar SV4.x för detta

**Comment by magnivar** [comment]
Går det att verifiera nu när vi uppgraderat genom export?
