### ISSUE TITLE
Kan ej söka på Komin utanför Malmö stads nätverk

### ISSUE THREAD

**Issue by elilun14** [malmostad/sitevision_assets#351]
När man sitter på Malmö stads enheter men inte på nätverket, och försöker söka på Komin, så funkar det inte. Inifrån funkar söken.

**Comment by martent** [comment]
Kommer du i huvudaget fram till https://s2.malmo.se/ utifrån med en plattformsdator som inte har VPN?

Inget svar, eller får du något felmeddelande? Når man inte servern så är det nätkonfiguration kopplad till plattformsdatorernas åtkomst och ska anmälas till IT-support.

@magnivar, kan du se om du får samma resultat så att vi vet om det är ett generellt konfigurationsproblem eller gäller vissa enheter?

Det var problem med servern tidigare men det åtgärdades 18/10, så det bör inte vara det som spökar här. Se malmostad/sitesearch/issues/8

cc: @olajoh1

**Comment by martent** [comment]
Servern s2.malmo.se är angligen inte upplagd via Nexus HAG. Det måste den vara om man ska kunna Komin-söka när man loggat in via sso.malmo.se.

@magnivar diskuterar detta med David Ravenna eller IT-support för att diskutera detta.

**Comment by magnivar** [comment]
Kan inte återskapa felet så vi anser det som löst.
