### ISSUE TITLE
Uppmärkning av citat

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#354]
Enligt PTS webbriktlinje nr 103 bör vi märka upp citat i koden (egen formatmall).

https://webbriktlinjer.se/r/103-markera-citat-i-koden/ 

Gäller såväl malmo.se och komin som SV och WP.

@perber14

**Comment by olajoh1** [comment]
Mårten, vill du lämna ett förslag på hur vi bäst kan uppfylla kraven i riktlinje 103.

**Comment by martent** [comment]
## Wordpress

I Wordpress skapar man fristående citat genom att klicka på ikonen med citationstecken. Markupen blir korrekt med `<blockquote> ... </blockquote>`. Stilsättningen blir nu ett traditionellt indrag för det eller de textstycken som finns i citatet. Vi kan även enkelt förändra stilstättningen i efterhand. Denna hantering av fristående citat verkar många av redaktörerna kunna hantera om man tittar på inlägg.

Citat som ligger direkt i en mening i texten, och alltså är kortare till sin natur, stöds inte rakt av i WP men det finns sätt vi kan etablera det.

1. Den som kan lite HTML-kod kan redan nu tillfälligt skifta till det skrivläget och skriva `<q>solen gick ned</q>, sa Arvid Falk`. Då ska man inte skriva ut citationstecken eftersom webbläsaren själv ska skriva ut dem som en del av stilsättningen.
2. En liknande lösning är att vi definierar upp en s.k. shortcode i Wordpress. Shortcodes är en vanlig del av Wordpresskrivande och det är det vi använder för att infoga Brightcovevideos i ett inlägg. Författaren skriver då i vanligt textläge och använder shortcodes som vi bestämmer, t.ex. `[q]solen gick ned<[/q], sa Arvid Falk`. Fördelen jämfört med (1) är att författaren slipper se all annan HTML-kod utan stannar i textläget.
3. Vi kan lägga till en custom-knapp för detta i verktygsfältet och skapa en funktion som lägger till markupen, på samma sätt som ikonen *I* lägger till taggen för emfas `<em>`.
4. Skriva vanliga citationstecken. Det blir ingen speciell markup med en screen-reader gör det tydligt för lyssnaren att det är ett citat.

**Comment by martent** [comment]
## Ange källa

För att ange källa för ett citat korrekt använder man koden `<cite>`. Det kräver dels en del redaktionell erfarenhet för hur man anger källa, och det kan bli rätt komplex kodstruktur som man får ha en plugin för. Se [exempel 12–19](https://w3c.github.io/html/grouping-content.html#example-54bcdf6d) i HTML-specen för olika redaktionell struktur för detta. Den kan med andra ord variera kraftigt efter kontexten. Håll ögonen efter `<blockquote>` `<footer>` och `<cite>` i koden för att se strukturen på den uppmärkta texten. Ambitionsnivån för att etablera detta, och en konsekvent redaktionell användning av det för olika scenarier, ligger nog mer åt publicerad facklitteratur.

**Comment by martent** [comment]
## Sitevision

Sitevision 4 har knappar både för inline- och block-citat:
https://help.sitevision.se/SiteVision_4_0/12701835.html

Verkar även finnas i SV 3 fast det ser lite annorlunda ut.

**Comment by perber14** [comment]
Vi vill att de visuella förändringarna som kommer default från SiteVision, när man märker upp text med <q> eller <quoteblock> ska tas bort, så att vi utan påverkan på presentationen kan använda citat-uppmärkning.

**Comment by magnivar** [comment]
@perber14 är det här nåt för @EllinorHallett

**Comment by perber14** [comment]
@magnivar Ja, det tycker jag.

**Comment by badwiz** [comment]
Jag vill bara ställa en kort förtydligande fråga

@perber14 Ni vill att citatet ska visas som vanlig text alltså? Vi ska göra en override på SiteVisions CSS som ändrar utseende?

**Comment by perber14** [comment]
@badwiz Yes! Så kika gärna på det!

**Comment by perber14** [comment]
Det gäller alltså blockcitat.

**Comment by badwiz** [comment]
Gör detta på testservern och verifiera hur det ser ut.

**Comment by israelsson** [comment]
Vanlig quote har inte någon speciell style utan får browser style. Har tagit bort specifika stylen från blockquote och lagt till så att det blir samma som för vanlig quote.

Blockquote får sin style från //assets.malmo.se/external/v4/malmo.css vilket vi inte kommer åt att redigera. Har därför gjort en Overrides.css som läggs till sist i head för att skriva över viss style.

Finns att se på test.malmo.se genom att skapa ett blockquote eller ett vanligt quote.

**Comment by magnivar** [comment]
@olajoh1 @Svempan @perber14 
Är denna lösning ok - override av malmo.css?
Kan ni testa?

**Comment by perber14** [comment]
Vi har kikat på det nu. 

Såhär vill ha det:

Kort citat: Ingen uppmärkning för besökarna, alltså inga fnuttar - vare sig stora eller små. Däremot bibehållen uppmärkning i koden (som det är nu).

Blockcitat: Uppmärkt med små fnuttar, som ligger som de som nu finns på "Kort citat" för besökarna:
![image](https://user-images.githubusercontent.com/22030097/35088809-2f4f9490-fc35-11e7-9bb5-cf81b1f7f3d9.png)

Och som nu uppmärkt med "blockquote" i koden.

**Comment by israelsson** [comment]
Hej!

Jag har fixat detta på testservern. Vill ni kontrollera och återkomma.


Mvh
Anders

**Comment by magnivar** [comment]
@perber14 kan du kolla ?

**Comment by perber14** [comment]
OK! Prodsätt.

**Comment by israelsson** [comment]
Fixat!
