### ISSUE TITLE
Ta bort datum från nyhetslistningen på startsidan

### ISSUE THREAD

**Issue by perber14** [malmostad/sitevision_assets#356]
![image](https://cloud.githubusercontent.com/assets/22030097/20000619/b48d9912-a278-11e6-8d8c-9e9f9f146776.png)

Det är alltså den lilla datumvisningen i listningen längst till höger av de fyra som ska tas bort.

**Comment by tomasrobertsson** [comment]
@magnivar nu ligger det på er test-server en uppdaterade version av det JS-script (i filarkivet) som genererar nyhetslistningen. 
Uppdateringen är en ändring i filen news.js under mappen lib. 
Ett spännande arbete att lista ut var något sker och i slutändan är själva lösningen att ta bort denna rad:
itemHtml += "<span>(" + pubDate + ")</span>"; (rad 670  i filen)

**Comment by magnivar** [comment]
@perber14 Kan du kolla att det ser ut som det ska.

**Comment by perber14** [comment]
Japp, det ser bra ut!

När sätts det i produktion? Vilka andra tickets ligger i samma deploy?

**Comment by tomasrobertsson** [comment]
Det får ni bestämma, vi sade allt i allt svep men om ni är nöjda med denna kan jag putta upp det på prod på fem minuter.

**Comment by tomasrobertsson** [comment]
Hur detta är implementerat skiljer sig i skarpa och testmiljön. 

I test har resursen, news.js, flyttats till filarkivet och tre, fyra olika portlets/vyer delar på denna fil. I produktion ligger denna js-kod istället i varje enskild vy/portlet. 
Det vore nog bra att göra något liknande som i testmiljön på produktion, att flytta ut till en fil, en resurs. Alltid dumt att ha kopior av kod på flera ställen.

**Comment by perber14** [comment]
@magnivar Jag tycker det vore bra att få det ensat. Vad säger du, Magnus?

**Comment by magnivar** [comment]
Jag håller med. Ska vi låta det vara kvar att göra i denna ticket/issue och stänga när det är gjort?

**Comment by tomasrobertsson** [comment]
För referens, såhär ser det ut på test:
```
/* BROKE AFTER MOVING TEST */
var utils = request.getAttribute('sitevision.utils');
var resourceLocatorUtil = utils.resourceLocatorUtil;
var fileRepo = resourceLocatorUtil.getFileRepository();
var lib = fileRepo.getNode('lib');
var news = lib.getNode('news.js');
var newsUrl = news.getProperty('URL').value;

// 

function getjs(){
   importPackage(java.net);
   importPackage(Packages.org.apache.commons.io);
   var url = new URL(newsUrl);
   //var url = new URL("http", "localhost", 80, "/test.js");
   var inputStream = null;
   try {
      var connection = url.openConnection();
      inputStream = connection.getInputStream();
      
      var body = IOUtils.toString(inputStream, 'UTF-8');
      return body;
   } finally {
      IOUtils.closeQuietly(inputStream);
   }
}

eval(String(getjs()))


var linkList = utils.metadataUtil.getRelatedMetadataPropertyValues(currentPage,"m_link_to_news_archive");

if(linkList.size() > 0){   
   NewsTicker.init(linkList);
}
```
En notering att det gick sönder vid en flytt någon gång.
I sig inget konstigt ovan, använder Sitevision API för att hämta en namngiven fil SV filsystem, denna läses in och sedan körs en given rutin i filen. 
Jag testar detta på produktion, på en inte publicerad sida, och verifierar att det fungerar även där. Borde inte vara något problem då referensen är till en given fil och inte av SV uppbyggd länk.
