### ISSUE TITLE
Script för Hotjar

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#357]
Vi behöver hjälp med att aktivera vårt script för verktyget Hotjar. Scriptet ska placeras på samtliga SV-sidor på malmo.se under ca en vecka. Jag vill dock först att vi testar det på ett urval av sidor. 

Angelägen om att ärendet får viss prio. 

Jag skickar nödvändiga inloggningsuppgifter via mail.

**Comment by tomasrobertsson** [comment]
Ok, skicka så tar jag en titt om det fungerar rakt av utan extra ändringar.

**Comment by olajoh1** [comment]
@tomasrobertsson  Vad har du för mailadress?

**Comment by tomasrobertsson** [comment]
tomas.robertsson@bouvet.se

**Comment by tomasrobertsson** [comment]
Detta ska nu vara implementerat på produktion. Verifiera och stäng

**Comment by martent** [comment]
Vet inte om denna ska ligga konstant. I så fall, för er information, den laddar in ~300kb javascript som webbläsaren får exekvera på varje sida. Gzippat är det ~60kb att hämta hem i två requests.

**Comment by olajoh1** [comment]
@martent 
Det är inget som ska ligga konstant. 

Vi har behov av att få ut det på Komin också. Har du ett förslag på lösning som gör att vi kan lägga ut det på min sida utan att lägga ut scriptet i asset?

**Comment by martent** [comment]
Vi lägger det lokalt på Min sida, och i SV-komin om det ska användas där. Gärna efter pågående serverflytt av Min sida.

**Comment by olajoh1** [comment]
Säg till när du är redo.

**Comment by magnivar** [comment]
Infört på SV komin
