### ISSUE TITLE
Byte av endpoint för API:et mot Kontaktboken

### ISSUE THREAD

**Issue by martent** [malmostad/sitevision_assets#358]
# I korthet
*Kontaktboken* kommer att byta adress. Portleten *Kontaktrutan* i SV för malmo.se och Komin som får sin data från *Kontaktboken* måste styras om till den nya adressen, det kan göras redan nu för test och görs i prod när den nya adressen produktionssätts. Det är endast en konfigurationsparameter i portleten som måste ändras.

@magnivar:
1. Kommer överens med @tomasrobertsson och testare om när ändringen ska göras och verifieras i testmiljöerna och avgör när ändringen är verifierad i test.
1. Kompletterar med datum och tid för produktionssättning 

Testare bör vara personer som kan Kontaktrutan och kan ändra uppgifter för t.ex. funktionskontakter i Kontaktboken.

# Utförlig information
I samband med att *Kontaktboken* får en ny adress i projektet NSF så måste Sitevision-portleten *Kontaktrutans* anrop till *Kontaktboken* ändras. Nuvarande end-points för test och prod:

https://webapps06.malmo.se/dashboard-test/api/v1/
https://webapps06.malmo.se/dashboard/api/v1/

kommer att ändras till:
https://minsidatest.malmo.se/api/v1/
https://minsida.malmo.se/api/v1/

Kontaktrutan ska ställas om till den nya adressen i samband med produktionssättningen av nya *Min sida*.  Kontaktrutan i SV cachar data med Javas Ehcache, konfigurerbart, tror det är satt till sex timmar. Ehcache måste rensas när en ny version av Kontaktrutan med den nya API-adressen deployas.

Anrop till den den gamla adressen kommer efter produktionssättning under en tid att returnera en HTTP response status code 301, Moved Permanently, till den nya adressen. Vi förlitar oss dock inte på detta för Kontaktrutans portlet.

## Aktiviteter
Fyll på nedan med andra aktiviter som behövs eller ska formuleras om.

### Testmiljöerna
1. Redan nu kan Kontakrutan i SV-test för malmo.se och Komin ställas om och testas mot den nya test-adressen.
1. Testning bör innehålla moment där information i Kontaktbokens test-miljö ändras. Dessa ska slå igenom inom max-tiden för Kontaktrutans cachning.
1. Forcera en rensning av cachen för en förekomst av Kontakrutan genom att öppna en Kontaktruta i adminläge och spara om den. Uppgifterna ska ändras direkt.
1. Testa att lägga upp en ny kontaktruta och se att all information visas som den ska.

### Produktionsmiljöerna
1. Verifiera redan nu att de nya adresserna går att nå från de två prod-servrarna. Det handlar dels om nätåtkomst och dels om att namnuppslagen fungerar från Sitevisionservrarna. Se till att inte förfrågningarna hamnar i den yttre åtkomsttjänsten sso.malmo.se utan i den faktiska tjänsten för Kontakboken.
2. Se till att autentiseringen mot Kontaktboken prod för malmo.se respektive Komins prodmiljöer fungerar. Detta kan göras med t.ex. curl. Förfrågningarna autentiseras med anropens IP-nummer, `app_token` och `app_secret`. Uppgifterna är olika för malmo.se och Komin och olika för test och prod. se dokumentationen för API:et[¹](#footnote-1).
3. Produktionssättning och testning.

## Ordförklaringar
*Kontaktrutan* – en portlet i SV för malmo.se och Komin som visar kontaktinformation på sidor. Informationen hämtas från Kontaktboken.

*Kontaktboken* – en tjänst som innehåller information om anställda och funktionskontakter. Tekniskt sett en del av Min sida (Intranet Dashboard) idag.

## Noter
<a name="footnote-1">1</a>. Kontaktbokens API finns i sin helhet beskrivet (med sin nuvarande (gamla) API-end-point som kommer att uppdateras) på:
https://github.com/malmostad/intranet-dashboard/wiki/Contacts-API-v1

**Comment by tomasrobertsson** [comment]
Hej
Detta är satt med hög prio, dvs ni vill att jag ska ta mig an detta snart. Alltid enklare att jobba under press, säg ett datum som det ska vara klart till, för att testas, så prioriterar jag upp det. 
Att byta adress är en enkel sak rent tekniskt.

**Comment by magnivar** [comment]
Vi kommer att börja gå över till de nya servrarna successivt med start gissningsvis efter 25:e januari misstänker jag. Kan det fungera för dig av ha det klart på TEST den 24/1?

**Comment by tomasrobertsson** [comment]
Då siktar jag på att testa detta under torsdagen så att vi har några dagars marginal. 
På normala test, inte på er Sv4 test.

**Comment by tomasrobertsson** [comment]
Test på komin test fallerar. Sidan https://minsidatest.malmo.se/api/v1/ kan ej nås från servern.


Samma på extern test, kan ej nå nya kontaktboken.
Det blir mycket snack i loggen så jag återställer. 
Om ni vill lägga in de nya igen kopiera bara in kontaktruta.war_new som kontakruta.war.

**Comment by magnivar** [comment]
@tomasrobertsson ... visst är detta löst i och med serverflyttar och nya kontaktruteportlets?

**Comment by tomasrobertsson** [comment]
Det ska vara löst. Många nycklar att hålla reda på men det ska fungera på båda prod och test-servrarna nu.

**Comment by magnivar** [comment]
Toppen! Då stänger vi :)
