### ISSUE TITLE
Visa när sidorna är senast uppdaterade

### ISSUE THREAD

**Issue by perber14** [malmostad/sitevision_assets#361]

**Comment by magnivar** [comment]
Är det bara att "slå på" eller krävs det styling och scriptning? @EllinorHallett

**Comment by perber14** [comment]
Det är ett färdigt metadata. Värdet finns alltså redan på alla sidor, men visas inte. Styling/design blir det ju tal om, vad gäller plats, position och exakt utseende.

**Comment by EllinorHallett** [comment]
Detta finns nu på www.test.malmo.se. @perber14 kan du kontrollera detta och säga till om jag ska lägga ut det på malmo.se

**Comment by perber14** [comment]
Gött att det är på gång! Dock vill vi ha en konsekvent lösning - där informationen alltid ligger i botten (Magnus berättade problemen med om Kontakt oss är rätt eller fel inlagt). Kan du hitta någon bra lösning på det? Behövs det några extra timmar för t ex styling eller så för att få det bra är det värt det. @EllinorHallett

**Comment by EllinorHallett** [comment]
Den är tyvärr svårare. En användare kan ju rent teoretiskt lägga in kontaktrutan hur som helst i mittenspalten (fel), behöver ju itne vara längst ner istället för att lägga upp det på det korrekta viset där den hamnar utanför mittenspalten. Jag kan omöjligt gissa var användarna lagt in denna och jag kan heller inte trycka in en kodbit i mittenspalten då denna är editerbar så SiteVision tillåter inte detta rakt av. Eventuellt att man kan skapa ett skript som på något sätt kan hitta denna och klämma in texten i mittenspalten vid behov men då krävs det ju ett skript som ligger och tickar på alla sidorna vilket leder till längre laddtider. Kan även bli problem om användaren inte har JS i sin webbläsare, nu är ju inte detta så vanligt med det brukar påpekas när man gör en valideringskrontroll av sidan. 
Detta är ytterligare en anledning till att bygga om siten från grunden. Då kan vi få bort de som är inlagt fel och låsa det så användarna inte kan göra fel från början.

**Comment by perber14** [comment]
Går det alltså inte att mallmässigt få in "visa metadatan allra längst ner på sidan", under kontaktuppgifter som även är korrekt inlagda? Alltid LÄNGST NER (på redigt, ja, förutom sidfoten).

**Comment by EllinorHallett** [comment]
Jo, vi ska nog kunna lägga den allra lägst ner, under kontakta oss rutan, tänkte bara att det var lite osammanhängande med texten att lägga den lägst ner. 
Ska jag testa att flytta den och lägga in den där? @perber14

**Comment by perber14** [comment]
Ja, testa det! Det ger ett mindre rörigt intryck än att det hamnar på olika platser (dessutom med ett annat, avvikande, utseende). @EllinorHallett

**Comment by EllinorHallett** [comment]
Fixat. Jag fick lägga en layout som bryter float ovanför textmodulen för annars flög datumet iväg till högersidan av någon anledning. Måste finnas en float någonstans i Css:en som stör ut för enligt SV- standard så ska allt lägga sig till vänster.  @perber14

**Comment by perber14** [comment]
Topp! Nu tycker jag att det är OK. Kolla ni också @olajoh1 och @magnivar!

**Comment by olajoh1** [comment]
Nu funkar det oavsett hur kontaktrutan är lagd på sidan. @magnivar styr hur vi implementar

**Comment by perber14** [comment]
Denna ska in som "kort och viktig" imorgon på redaktörsmötet!

**Comment by magnivar** [comment]
Redo för Deploy när C+J är stand by.

**Comment by EllinorHallett** [comment]
Återkom när de är på stand-by så löser jag detta.

**Comment by EllinorHallett** [comment]
Detta ligger nu live.

**Comment by olajoh1** [comment]
ok
