### ISSUE TITLE
Fix kopplad till nyhetslistningen på malmo.se

### ISSUE THREAD

**Issue by perber14** [malmostad/sitevision_assets#363]
https://github.com/malmostad/sitevision_assets/issues/356

I sidfoten som används på vanliga innehållssidor listas datum fortfarande, och inte på något bra sätt:

![image](https://cloud.githubusercontent.com/assets/22030097/25897563/ac5d5284-3588-11e7-9702-5dca99929ae1.png)

Ska bort även härifrån.

**Comment by badwiz** [comment]
Provar bara att lägga en kommentar för att se att det fungerar...

**Comment by badwiz** [comment]
Nu är detta fixat på test.malmo.se
