### ISSUE TITLE
Påverkansytan/bannern går inte att länka till externa webbsidor

### ISSUE THREAD

**Issue by Svempan** [malmostad/sitevision_assets#364]
Om man länkar bannern till en extern webbsida så hamnar man på malmo.se:s startsida.
Se även: #329

**Comment by magnivar** [comment]
Hur löser man detta @EllinorHallett ?

**Comment by EllinorHallett** [comment]
Börjar titta på detta under dagen och återkommer med vad som hittats.

**Comment by EllinorHallett** [comment]
Detta ska nu vara löst.

**Comment by magnivar** [comment]
@Svempan kan du kolla och stänga om det är klart?

**Comment by magnivar** [comment]
@Svempan kan du kolla och stänga om det är klart?
