### ISSUE TITLE
Implementera Fäll ut/Fäll in på komin

### ISSUE THREAD

**Issue by magnivar** [malmostad/sitevision_assets#366]
Ta Fäll ut/Fäll in funktionaliteten från Gymnasiewebbarna och impemetera på komin.
Först i TEST och sedan förbereda redaktörer för rätt användande.

**Comment by EllinorHallett** [comment]
Tyvärr verkar jag inte kunna logga in på test för komin med de inloggningsuppgifterna jag fick av dig @magnivar

**Comment by tomasrobertsson** [comment]
Efter senaste flytt av komin, från produktion till test  ändrades inte lösenordet utan det är samma på prod som test.

**Comment by EllinorHallett** [comment]
Nu ligger funktionaliteten på plats bortsätt från att det saknas ett klassnamn i SiteVision som sedan ska pekas ut på ytan "Center & Dropdownklass" samt att koppla dekorationsmallen. Detta på grund av en bugg i SiteVision som inte tillåter mig att skapa dessa under webbplatsinställningar > Dekorationer. @magnivar vem tar kontakten med SiteVision för att rappotera denna buggen och få dem att åtgärda detta?

**Comment by magnivar** [comment]
@EllinorHallett jag ser gärna att du förklarar för dem för att de snabbare förstår vad som måste göras.

**Comment by EllinorHallett** [comment]
Jag har skickat ett mail till supporten och bett dem skicka svar till mig med dig, @magnivar som CC.

**Comment by magnivar** [comment]
Jag har inte fått någon respons från SV om dettta men det kanske är @badwiz som tar bollen vidare?

**Comment by badwiz** [comment]
@bjornhutter Kan du se om du skulle kunna göra denna insats på Komin-test? Alltså se till att menyn fungerar som på Gymnasiewebbarna? Men om det inte fungerar (enligt Ellinor) så återkoppla så tar jag det med SiteVision.

**Comment by badwiz** [comment]
Vi har kollat runt på detta och ser att vi kan få till en liknande meny på 16 timmar på Komin.

**Comment by badwiz** [comment]
Vi gör detta på test-webben innan det hamnar på Komin.

**Comment by badwiz** [comment]
Anders Israelsson kommer att kika lite på detta om det finns tid när han håller på med Förvaltningssidorna. Annars lägger vi tid på detta efter Förvaltningssidorna.

**Comment by badwiz** [comment]
http://latinskolan.malmo.se/utbildningar/estetiska-programmet.html
Exempel på Fäll ut / Fäll in, accordion-funktion på innehållet.

**Comment by henrikekelof** [comment]
Hej @magnivar + @badwiz !
Det här var inte en SiteVisionbugg, det här handlade om att det låg ett par CSS-regler med felaktiga class-namn. Jag har fixat så att den här funkar på test nu:
http://161.52.13.184/edit/4.79ff2ce11606aebb8172a3f3

**Comment by henrikekelof** [comment]
@magnivar Fråga: Vill du att jag stänger ett sådant här ärende när det är fixat, eller vill du kolla först och själv stänga sen?

**Comment by magnivar** [comment]
@henrikekelof Assigna det på oss (mig) när du är klar så kollar vi och godkänner för produktionssättning och sen test av oss igen för acceptans... Det känns mest rätt eller har @badwiz någon annan tanke?

**Comment by badwiz** [comment]
@magnivar @henrikekelof Håller med Magnus. Vi gör klart och sedan lägger vi över ärendet på Malmö (Magnus eller någon annan om vi vet vem det är).

**Comment by magnivar** [comment]
Ser det ut så här hos er också?
![image](https://user-images.githubusercontent.com/22590738/34203601-192e13be-e57c-11e7-9a8d-75bb51cef956.png)

**Comment by henrikekelof** [comment]
Ja, ungefär. Jag tänkte att det inte tillhörde det här ärendet att snygga till den, men jag kan se till att den ser lite bättre ut :)

**Comment by henrikekelof** [comment]
Nu ska den se lite finare ut också! Kolla om det här känns mer OK:
![screen shot 2017-12-20 at 15 43 06](https://user-images.githubusercontent.com/186166/34212439-8d562838-e59c-11e7-9a94-3ca0a3ab3c18.png)

**Comment by magnivar** [comment]
@elilun14 @fredrikwittbjer 
Kan ni kolla sidan och ge feedback?
https://komin.test.malmo.se/4.79ff2ce11606aebb8172a3f3.html

**Comment by olajoh1** [comment]
Designen följer inte WAG

**Comment by elilun14** [comment]
Funktionen i sig fungerar, men färg, typsnitt och storlek på texten i rubriken behöver anpassas till vad som gäller för Komin (vilket bör finnas dokumenterat här på Github någonstans...?).

**Comment by henrikekelof** [comment]
Inga problem! Jag uppfattade det som att den såg rätt ut och att det bara var problem med att den inte fungerade. Men jag kan göra om utseendet enligt WAG som jag hittat här: https://malmostad.github.io/wag-intranet-v3/

**Comment by henrikekelof** [comment]
Testsidan är uppdaterad med ny funktion/utseende.

Jag gjorde så att fäll ut-/in-funktionalitet är inaktiverad i redigeringsläget så att det blir lättare för redaktören att se texten och redigera den.

https://komin.test.malmo.se/4.79ff2ce11606aebb8172a3f3.html

![screen shot 2018-01-12 at 15 27 58](https://user-images.githubusercontent.com/186166/34879377-4f2b11fe-f7ad-11e7-84d6-f29143370ea7.png)

Ping: @olajoh1 @elilun14 @fredrikwittbjer

**Comment by elilun14** [comment]
Det behöver vara ett plus istället för den lilla pilen, för att man ska förstå att det går att klicka och att det finns något "under". (Det må vara att pilen finns i den tidigare komindokumentationen men vi vet att den inte förstås, så använd ett plus.)

**Comment by henrikekelof** [comment]
@elilun14 Har nu ändrat till ett plus som blir ett kryss för att stänga. Testa igen och kolla om det ser  OK ut.

**Comment by elilun14** [comment]
@henrikekelof  Bra. Dock ska "fäll ihop" illustreras som ett minustecken och inte ett X. (Kryss är lika med "ta bort")

**Comment by fredrikwittbjer** [comment]
@henrikekelof Rubriken måste göras tydligare för att öka call-to-action-värdet. Kan vi feta texten (till exempel via att använda H3)?

**Comment by henrikekelof** [comment]
@fredrikwittbjer OK, vill ni då att vi avviker från er WAG här? Jag hittar inte någon box där med fet stil https://malmostad.github.io/wag-v4/typography_and_articles/#article-boxes

@elilun14 Håller inte med om att kryss betyder ta bort, men jag ändrar :)

**Comment by fredrikwittbjer** [comment]
[Testa att använda denna](https://malmostad.github.io/wag-intranet-v3/boxes/), där bakgrundsfärgen ändras. Då kanske inte texten behöver fetas, men man kan ändå urskilja att det är en call to action. :)

![image](https://user-images.githubusercontent.com/31471269/34950038-39415b0c-fa12-11e7-9131-1de00c029422.png)

**Comment by henrikekelof** [comment]
Status just nu > Har gjort fet stil i rubrik och +/-. 
![screen shot 2018-01-15 at 16 56 51](https://user-images.githubusercontent.com/186166/34951055-4b0cb1ee-fa15-11e7-88de-84d0edacf2d4.png)

**Comment by henrikekelof** [comment]
@fredrikwittbjer @elilun14 Är det OK med senaste utseendet eller vill ni göra ytterligare ändringar?

**Comment by magnivar** [comment]
@fredrikwittbjer @elilun14 Är det OK med senaste utseendet eller vill ni göra ytterligare ändringar? :)

**Comment by elilun14** [comment]
Hej! Den ser märklig ut på test, eller har jag inte senaste länken? https://komin.test.malmo.se/4.79ff2ce11606aebb8172a3f3.html

**Comment by henrikekelof** [comment]
@elilun14 Nej, sorry. Det var en miss av mig. Kolla igen :)

**Comment by elilun14** [comment]
Tack @henrikekelof - jag tycker det ser bra ut nu. @magnivar @fredrikwittbjer

**Comment by fredrikwittbjer** [comment]
Håller med! @magnivar @elilun14 @henrikekelof

**Comment by henrikekelof** [comment]
Fint! Ska jag flytta över det här till komin Prod då @magnivar ?

**Comment by magnivar** [comment]
Jag gör ett nytt issue för malmo.se så kan @perber14 först komma med sina grafiska (färger) val.
Lägg detta på PROD och bolla över till mig så verifierar vi och stänger denna.

**Comment by perber14** [comment]
@elilun14 @fredrikwittbjer Varför har ni inte samma färg på plattan som de här har? Kommer synas mycket bättre?
![image](https://user-images.githubusercontent.com/22030097/35097211-7cd2b8c2-fc4f-11e7-94e4-497641512d82.png)

**Comment by henrikekelof** [comment]
Jag valde bort den mörka plattan p.g.a det som står i WAG: "This type of box must not be used in article content" https://malmostad.github.io/wag-v4/other_page_elements/#boxes-for-application-views

För den ljusa boxen står det "A box suitable for related content":
https://malmostad.github.io/wag-v4/typography_and_articles/#article-boxes

Det är fullt möjligt att jag har tolkat avsikten fel, men det är anledningen. Vem tar beslutet kring mörk eller ljus?

**Comment by elilun14** [comment]
@henrikekelof Helt rätt med den ljusa för Komin, så vi kör på den. (@perber14 Säger intranätansvarig :-).)

**Comment by perber14** [comment]
o7

**Comment by henrikekelof** [comment]
Nu finns rutan i prod för Komin. Testsida: https://komin.malmo.se/4.132262a160fdc3380f9bd69.html

**Comment by magnivar** [comment]
@fredrikwittbjer verifierar :)

**Comment by fredrikwittbjer** [comment]
Ser bra ut! En liten grej bara @henrikekelof: rubriken fetas i redaktörsläget. Går det att fixa?

**Comment by henrikekelof** [comment]
@fredrikwittbjer Ah, bugg! Tanken är att den ska vara fet i båda lägena enligt det vi pratade om häromdagen.

**Comment by henrikekelof** [comment]
Nu fixat så inte fet stil faller bort.

**Comment by fredrikwittbjer** [comment]
hej igen @henrikekelof, förlåt men det måste blivit ett missförstånd. Vi skulle gärna se att den inte har en fetad text. Annars är vi mycket nöjda och anser att så fort texten är tillbaks i regular så blir det slutversionen :)

![image](https://user-images.githubusercontent.com/31471269/35099373-11ce4d80-fc58-11e7-947d-0ae085dbef09.png)

**Comment by henrikekelof** [comment]
Testa igen nu. Sorry. Jag hängde inte med i alla turerna.

**Comment by elilun14** [comment]
Tack, helt rätt så @henrikekelof - slutversion!

**Comment by fredrikwittbjer** [comment]
:100:

**Comment by magnivar** [comment]
Toppen! Bra jobbat allihopa.. nu stänger vi 💃

**Comment by magnivar** [comment]
@fredrikwittbjer hade nåt att tillägga

**Comment by fredrikwittbjer** [comment]
Ja, precis så! Nu när jag har haft möjlighet att använda dekorationen på en sida med många frågor och svar  såg det ut som följer:

![image](https://user-images.githubusercontent.com/31471269/35910509-0d50630c-0bf7-11e8-8e6f-e9de1f4a2d40.png)

Dessutom hade jag också en fundering kring muspekaren, det är svårt att förstå att dragspelet är klickbart när det kommer upp en markeringssymbol (kommer inte på vad den heter eller hittar någon bra bild) över plusset istället för en "vanlig" länksymbol (dvs en pekande hand)

**Comment by henrikekelof** [comment]
@fredrikwittbjer Har du möjlighet att lägga en länk till den sidan?

**Comment by fredrikwittbjer** [comment]
https://komin.malmo.se/4.95dba5115e8f5b3c5eefa51.html @henrikekelof

**Comment by henrikekelof** [comment]
Tackar! Kollar på den i eftermiddag.

**Comment by henrikekelof** [comment]
Hej @fredrikwittbjer ! Jag kan inte återskapa det felet. Vad är du i för webbläsare? Du har inte zoomat in eller ut (testa CTRL + 0)?

**Comment by fredrikwittbjer** [comment]
Hej @henrikekelof ! "Ramroblemet" verkar uppkomma när jag använder Chrome, men funkar på IE och Edge. 

Vad gäller "muspekarproblemet" gäller det för alla webbläsare.

**Comment by fredrikwittbjer** [comment]
@henrikekelof nu funkade det dock när jag zoomade ut! Skönt!

**Comment by henrikekelof** [comment]
Härligt :)

Du har fått en hand som muspekare nu också.

**Comment by Svempan** [comment]
Där är en liten men irriterande pixel i innehållsytan när den är markerad. @henrikekelof 
![pixel](https://user-images.githubusercontent.com/7701048/35923543-d710f714-0c20-11e8-9a6c-650f9b66b833.png)

**Comment by henrikekelof** [comment]
@Svempan - Testa att sätta lite padding på en vanlig textmodul så kommer du se den där också. Jag vet inte exakt var den kommer ifrån, men den är inte specifik för den här funktionen. Vill ni att vi undersöker den saken så är det bra om ni skapar en egen issue för den, men jag är halvskeptisk till att vi kan göra något åt den. Den andra bilden är från Falkenbergs kommun, och dom har exakt samma sak.

![screen shot 2018-02-07 at 16 15 45](https://user-images.githubusercontent.com/186166/35924109-688e050a-0c22-11e8-8d4c-28593dcc6d03.png)

![screen shot 2018-02-07 at 16 23 19](https://user-images.githubusercontent.com/186166/35924426-55193de0-0c23-11e8-8033-9faa36e6bdcf.png)

**Comment by perber14** [comment]
Mer diskussion om några sista detaljer behövs mellan @fredrikwittbjer, @Svempan & @elilun14.

**Comment by fredrikwittbjer** [comment]
Ja, precis så! Först och främst undrar vi ifall vi kan indexera dekorationen som en H4:a? @henrikekelof

**Comment by henrikekelof** [comment]
@fredrikwittbjer Ja, det är inga problem. Kommer det fler önskemål eller var det bara det?

**Comment by Svempan** [comment]
Vi vill att dragspelet på Komin är identiskt med malmo.se. Dvs samma linjer och gråa nyans i bakgrunden. Rubriken ska inte trunkera utan få den plats den behöver. 
https://www.test.malmo.se/4.719e72ae160e0f98c258aeea.html @elilun14 
Fråga: kan vi tagga rubriken som en H4? @henrikekelof

**Comment by henrikekelof** [comment]
👆

Beroende på skillnad i style kan det behöva justeras lite i CSS, men det är lätt ordnat.

**Comment by Svempan** [comment]
Toppen! Då kör vi på det och kör ut allt i prod @henrikekelof

**Comment by henrikekelof** [comment]
Yes, jag tar det i morgon och meddelar här när det är klart.

**Comment by henrikekelof** [comment]
Denna finns nu i produktion med samma utseende som malmo.se, fast med H4 istället för H2. Testsida:  https://komin.malmo.se/4.132262a160fdc3380f9bd69.html

**Comment by magnivar** [comment]
Detta är klart :)
