### ISSUE TITLE
Bilder i påverkansytan

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#367]
Tillagda alt-texter får ej genomslag. Vi kan inte se att de läggs till i html-koden.

**Comment by badwiz** [comment]
Lägg gärna till en länk i beskrivningen till en sida som saknar detta så blir det enklare att felsöka och hitta en åtgärd.

**Comment by olajoh1** [comment]
Du kan titta på vilken startsida som helst. Påverkansytan är namnet på bannern

**Comment by perber14** [comment]
Har du kollat detta, @badwiz ?

**Comment by badwiz** [comment]
Ja @perber14 , vi gjorde en fix för detta igår. Kolla på https://malmo.se/4.685fbbb5160dbb463c21f4f5.html
Ej publik sida, så du måste logga in för att se denna. Vi har även fixat Alias-hanteringen och det gäller Påverkansytan långt ner på sidan, för att inte påverka mallen i detta läget.

**Comment by olajoh1** [comment]
ok, klart för prod

**Comment by badwiz** [comment]
Finns i PROD nu. Klart att stängas efter verifiering.

**Comment by olajoh1** [comment]
ok
