### ISSUE TITLE
GZIP-komprimering för prestandaökning?

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#368]
Information hämtad från Siteimprove. Magnus undersöker tillsammans med BOuvet och Jonny/Christan.

Om detta problem
GZIP-komprimering är ett sätt att komprimera filer så att de överförs snabbare. Servern skickar den komprimerade filen till användarens webbläsare som sedan laddar ned och packar upp den. Komprimeringen minskar filstorleken med upp till 90 % så att sidorna kan läsas in snabbare och dataförbrukningen blir mindre. Detta ger också en bättre användarupplevelse och högre rankning hos sökmotorerna.
Hur det åtgärdas
Hur det går till att använda GZIP-komprimering beror på vilken typ av server som du använder. En av de vanligaste lösningarna är att lägga till kod i .htaccess-filen på servern. Den filen kommer du åt med filhanteraren.  Du kan hitta mallar för GZIP-konfigurationer till populära servrar här.

**Comment by badwiz** [comment]
Enligt SiteVision är alla resurser som skickas från server till webbläsare redan gzippade per default.

**Comment by olajoh1** [comment]
Går det på ett enkelt bekräfta att det fungerar som avsett i SV?

**Comment by henrikekelof** [comment]
Man ser det i Response Headers, Content-Encoding:gzip (bild 1). Man kan också köra Google PageSpeed Insights och se om man får anmärkningar: 
https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fmalmo.se%2F 

Det finns en fil som inte blir gzippad, och det är den CSS-fil som byggs i detta projekt, http://malmo.se/local-assets-v4/application.css (bild 2).

Finns det någon tanke kring att lyfta ur JS och CSS från det här projektet och låta dom ligga direkt i SiteVision? Det är lite märkligt och onödigt komplicerat att man ska bygga statiska filer och göra release på dom genom att lägga en war-fil på servern. Det vore mycket smidigare att de låg i SiteVisions filarkiv och att man gjorde ändringar manuellt där. Då skulle CSS:en också bli gzippad :)

Bild 1:
![screen shot 2018-01-22 at 10 47 36](https://user-images.githubusercontent.com/186166/35214510-b1f5a644-ff61-11e7-89ab-44916d10648b.png)

Bild 2:
![screen shot 2018-01-22 at 10 46 40](https://user-images.githubusercontent.com/186166/35214485-9921a820-ff61-11e7-8e97-5e8bb00dc3b4.png)

**Comment by magnivar** [comment]
Inte görbart så länge vi importerar WAG externt
