### ISSUE TITLE
Samma sida har två url:er

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#369]
För att få våra sidor att ranka så högt som möjligt i sökmotorer bör vi använda canonical länkar på rätt sätt. Just nu är SV inställd på att url:erna ska skrivas ut både med versaler och gemener.  Siteimprove signalerar att vi bör ändra så att vi enbart skriver ut url:erna på ett sätt för att få sidorna att fungera bättre i sökmotorer.  Vilka konsekvenser får det om vi ändrar till att skriva ut url:erna enbart med gemener?

**Comment by badwiz** [comment]
Google har indexerat er sajt enligt det som finns i menyerna, alltså "http://malmo.se/Bo-bygga--miljo/Bygga-nytt---bygga-till.html" (sentence case). Tar man någon annan form av url så finns Canonical för att visa sentence case som originalet.

För Google spelar det ingen roll rankingmässigt hur man har sina url:ar, det är varken sämre eller bättre med något alternativ.

Om ni skulle byta till endast gemener så måste Google indexera om alla sidorna för att uppdatera sina träffar och användares sparade url:ar skulle inte fungera längre.

**Comment by olajoh1** [comment]
ok
