### ISSUE TITLE
Brödsmulan för Komin

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#370]
Brödsmulan för Komin skrivs ut fel.

Exempel:
Vår kommun>Förvaltningar>Stadskontoret

Ska vara:
Komin > Förvaltningar>Stadskontoret

Exempel:
Komin>Mål&styrning

Ska vara:
Komin>Vår kommun>Mål&styrning

**Comment by badwiz** [comment]
Första exemplet är klockrent, detta ska fixas.

Det andra exemplet kan vara lite konstigt, då brödsmulan listar alla navigerbara element i sökvägen. Om den inte finns i strukturen som en sida så kan man inte navigera till. Men vi har inte kikat på detta ännu.

**Comment by israelsson** [comment]
Hej!

Har gjort en lösning för detta nu. Den finns bara på komin.test.malmo.se än så länge så ni får kontrollera först.

Nu ligger det två brödsmulor så ni kan jämföra. Den nya är den undre och den är även blå för att den ska synas tydligt.

Kontrollera om det verkar OK så kan vi lägga över det på den skarpa servern.


Mvh
Anders Israelsson

**Comment by olajoh1** [comment]
Ser korrekt ut på de 15 sidor jag har kollat.

**Comment by badwiz** [comment]
@magnivar ska vi tolka detta som att vi flyttar över till PROD?

**Comment by magnivar** [comment]
Ja, flytta till PROD och meddela oss.

**Comment by israelsson** [comment]
Nu har jag lagt in det på PROD. Kolla av så att det stämmer.

**Comment by magnivar** [comment]
Ser bra ut med de exempel som givits. @olajoh1 kan du också kolla och stänga ärendet om det är bra?

**Comment by olajoh1** [comment]
ok
