### ISSUE TITLE
Senast ändrad ligger fel i mallen

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#372]
Uppgiften Senast ändrad visas plötsligt felaktigt under högermenyn. Ska visas i huvudspalten.

**Comment by israelsson** [comment]
Det ligger inline style på en layout i mallen, inline stylen tog inte av någon anledning. Ni har en fördefinierad clearfix-class. Jag la på den på layouten, då fick man den inline style som låg genom classen istället. Ni ser på bilden vart jag ändrade.

<img width="448" alt="skarmavbild 2017-12-05 kl 08 54 49" src="https://user-images.githubusercontent.com/6682316/33595964-4fb60812-d99a-11e7-9cce-72607529a18d.png">

**Comment by olajoh1** [comment]
ok
