### ISSUE TITLE
Webbvideo-portlet sparar inte ändringar

### ISSUE THREAD

**Issue by magnivar** [malmostad/sitevision_assets#373]
Webbvideomodulen (PRE SV 4) verkar inte vilja spara ändringar som görs av val av spellista från Brighcove.

Denna portlet kan fortfarande bara redigeras i klassiskt läge (IE11) och har bara en redigeringsmöjlighet.

Den sida vi kollar på just nu är: http://www.malmo.se/Kommun--politik/Malmo-en-hallbar-stad---socialt-ekonomiskt-och-ekologiskt.html och vi försöker ändra till spellista/kategori "Globala målen"

Går det att porta den portleten till SV4? eller måste vi skriva om den och t.ex. göra ett element?

**Comment by badwiz** [comment]
Vi har kikat på att "laga" portleten men inte lyckats fixa allt. Dessutom är det samma fel i kontaktportleten, men vi har använt videoportleten som grund för felsökning. Jag tror att det är element som gäller för denna portlet, tyvärr har kontaktportleten väldigt mycket logik inbyggt så där kan det vara klurigare att skriva ett element av denna.

**Comment by badwiz** [comment]
Nu finns det en ny modul, Element, som hanterar era filmer på komin och externt. Denna modul kommer att ersätta er nuvarande modul och fungera i SV4.

**Comment by magnivar** [comment]
Denna är ersatt av https://github.com/malmostad/sv-webbvideo/issues/9
