### ISSUE TITLE
Google indexerar våra test-servrar

### ISSUE THREAD

**Issue by magnivar** [malmostad/sitevision_assets#374]
robots.txt bör modifieras så att test-servrarna inte indexeras av google.

**Comment by magnivar** [comment]
Har bett vår IT att ta bort portöppningarna för extern trafik.

**Comment by badwiz** [comment]
Uppdatera robots.txt på servern.

**Comment by badwiz** [comment]
Blockera hela webbplatsen från alla sökmotorer:

User-agent: *
Disallow: /

**Comment by perber14** [comment]
Har ni gjort det? Annars är det bara att köra!

**Comment by badwiz** [comment]
Nej, jag har tänkt att göra detta. Men min VPN vill inte fungera. Har anmält detta till @magnivar som drar det till IST. Här måste vi ju komma åt filerna, inte bara SiteVision.

**Comment by perber14** [comment]
Gott! Då är den på rull (Magnus jiddrar ju med att fixa VPN-problemet).

**Comment by badwiz** [comment]
Har inte glömt denna. Mitt VPN fungerar nu, men vi har inget fungerande konto på servrarna för att komma in. @magnivar håller på att leta reda på någon som kan ordna ett konto med SUDO.

**Comment by badwiz** [comment]
Nu är testserverns robots.txt uppdaterad med att inte tillåta indexering.

**Comment by perber14** [comment]
Känner inte att denna är min, så herrar @magnivar och @olajoh1. Ni tar denna. :)

**Comment by olajoh1** [comment]
@magnivar DUNS :-)

**Comment by magnivar** [comment]
Bra! Vad tycker ni? Skall vi öppna brandväggen så man kommer åt test utifrån igen? @perber14 @olajoh1

**Comment by perber14** [comment]
Ja, det tycker jag väl att vi kan göra. Har vi någon anledning att inte göra det?

**Comment by magnivar** [comment]
Ja, det skulle väl vara att ingen utomstående har anledning att besöka test... men det hade underlättat för våra utvecklare att slippa gå via VPN om vi öppnar brandväggen.

**Comment by olajoh1** [comment]
ja

**Comment by magnivar** [comment]
Nej, vi öppnar inte :)
