### ISSUE TITLE
Sidfotsmenyn renderar olika

### ISSUE THREAD

**Issue by magnivar** [malmostad/sitevision_assets#376]
I sidfoten (SV's sidfot) så verkar det finnas ett instabilitetsproblem.
Det gäller länken till Anslagstavla som syns ibland och ibland inte. När den inte syns finns en extra A-Ö länk nederst.
För mig fungerar det i Win10-Chrome och IE11 men inte i Edge samt på en iPad så syns den varken i Safari eller Chrome.
Sven säger att den syns i Edge, Firefox, IE11 och Chrome på hans dator så det är svårt att hitta gemensam nämnare. Se bilder:
![image](https://user-images.githubusercontent.com/22590738/34564141-d03961fa-f155-11e7-8ee0-bf77b816ca5a.png)
![image](https://user-images.githubusercontent.com/22590738/34564147-d61ceb3c-f155-11e7-8cea-4f84e58117b6.png)
Sidfotens länkar genereras av skript i Sidmallarna "/Delmallar/Sidhuvud & sidfot"

**Comment by badwiz** [comment]
Ser samma sak i Chrome för Android, Anslagstavla saknas och A-Ö finns två gånger.

**Comment by badwiz** [comment]
Kan det vara så att Google tag-manager är inblandat och "letar" efter länken Anslagstavla? Det är ju nytt för i år antar jag.

**Comment by magnivar** [comment]
Anlagstavlan är ny sedan november december. Hur kan GTM påverkar hur en meny i SV visas?

**Comment by badwiz** [comment]
Vi märkte att det var något javascript som påverkade länken Anslagstavla. Stängde man av javascript fungerade allt som det skulle nämligen.

Nu ser vi dessutom att allt fungerar som det ska igen. Har ni gjort någon förändring någonstans? Våra "fel" är nämligen borta nu ser vi.

**Comment by magnivar** [comment]
@Svempan @perber14 @Emmlin4 Kan ni återskapa felet som varit?

**Comment by Svempan** [comment]
Jag har aldrig upplevt det själv. Känns lite som månlandningen. Man vet inte vad man ska tro..

**Comment by magnivar** [comment]
Ser ut hos de jag kollat med att det fungerar som det ska nu!
