### ISSUE TITLE
En sida har dubbla sidfötter från WAGen

### ISSUE THREAD

**Issue by magnivar** [malmostad/sitevision_assets#377]
Vi förstår inte hur det kan går och vi hittar inte nåt i SV som orsakar det.
Se bild! Vad har vi missat:
![image](https://user-images.githubusercontent.com/22590738/34781325-d7bd199c-f625-11e7-86ac-3523ce820b76.png)

**Comment by badwiz** [comment]
Har något med javascript att göra. Det är via javascript som sidfoten laddas och den verkar köras dubbla gånger.

**Comment by badwiz** [comment]
För att utesluta nätverksproblematik skulle vi kunna testa att gå med "localhost" när man befinner sig på servern fysiskt (eller remote). Om sidan renderas rätt då så är det något med nätverket som påverkar javascript/html.

**Comment by henrikekelof** [comment]
Problemet löst. Tog bort detta ur Tillägg i HEAD från gamla gränssnittet:

    ## 
    ## $Rev: x
    ## $Date: x
    ## GitHub repository: https://github.com/malmostad/sitevision_assets
    ##
    <script type="text/javascript">var runSurvey = true;</script>
    #set($assetUrl = "//assets.malmo.se/external/v4") ## no trailing slash
    <meta content='width=device-width, initial-scale=1.0' name='viewport'/>
    
    
    <link href='$assetUrl/malmo.css' media='all' rel='stylesheet' type='text/css'/>
    <link rel="stylesheet" href="/local-assets-v4/application.css">
    <script src="$assetUrl/malmo.js"></script>
    <script src='/local-assets-v4/application.js'></script>
    
    <noscript><link href="$assetUrl/icons.fallback.css" rel="stylesheet"></noscript>
    <link rel='icon' type='image/x-icon' href='$assetUrl/favicon.ico'/>

Och:

    <script src="//cdn.optimizely.com/js/3683524469.js"></script>
