### ISSUE TITLE
Bildbeskrivningen syns inte på nyhetslistning

### ISSUE THREAD

**Issue by magnivar** [malmostad/sitevision_assets#378]
Nyhetslistningen på t.ex. förstasidan (finns på fler sidor) visar inte ALT-texten som tillhör bilden.
![image](https://user-images.githubusercontent.com/22590738/35091262-5c5c995e-fc3c-11e7-88d3-78b12fa723fd.png)

Det finns oftast en ALT-text på bilden i nyheten. (När man klickar)

I ett vidare perspektiv, går det att tvinga att man skriver bildbeskrivning när man laddar upp en bild?

**Comment by badwiz** [comment]
Lösningen är via skript och där har inte alt-texten hämtats (saknas kod för detta alltså). Vi fixar till detta.

**Comment by israelsson** [comment]
Hej!
Nu ska detta vara fixat i prod. Man måste bara sätta en alt-text på bilden i artikeln så ska den skrivas ut i html-koden.


Mvh
Anders Israelsson, Bouvet

**Comment by magnivar** [comment]
@Svempan Verifiera och stäng ärendet om det är klart!

**Comment by Svempan** [comment]
Hur kontrollerar man det? I koden bara, eller?

**Comment by badwiz** [comment]
Ja, lite beroende på webbläsare, men kolla i koden så ser man att det alltid skrivs ut en alt-tagg för bilderna i Nyhetslistningen nu. Men om inte bilden har en alt-text i sin artikel kommer alt-taggen vara tom.

**Comment by magnivar** [comment]
Klart med bug i redaktörsläget som inte visar bilderna korrekt
