### ISSUE TITLE
Implementera Fäll ut/Fäll in på malmo.se

### ISSUE THREAD

**Issue by magnivar** [malmostad/sitevision_assets#379]
Samma funktion av Fäll ut/Fäll in som på komin (https://github.com/malmostad/sitevision_assets/issues/366) men kanske med andra färgval.
@perber14 anger preferenser

**Comment by perber14** [comment]
Vi börjar med:

Ljusblå bakgrundsplatta och kantlinje (den ljusblå vi har i topplisten på malmo.se)
Svart rubrik för boxen
Svart plus/minus
Ljusgrå bakgrund i själva boxen när den fälls ut

Detta är förlagan:

![image](https://user-images.githubusercontent.com/22030097/35097118-27be6e3a-fc4f-11e7-85b5-8a95a11ef921.png)

Skillnaden blir alltså att vi vill ha en ljust grå bakgrund på malmo.se, eftersom att övriga bakgrunden är vit (vill skillnad från på gymnasiesajterna där det är tvärtom).

URL: http://universitetsholmensgymnasium.malmo.se/utbildningar/el--och-energiprogrammet.html

@magnivar OK som ingångsspec?

**Comment by magnivar** [comment]
Med andra ord som på http://pauliskolan.malmo.se/utbildningar/samhallsvetenskapsprogrammet.html?

**Comment by perber14** [comment]
Japp, med undantag för bakgrundsfärgen då!

**Comment by magnivar** [comment]
Idé på ljusgrå?

**Comment by perber14** [comment]
Nej, inte hex-mässigt. Men ljust grå. Läsbarheten måste ju vara bra med den svarta texten.

**Comment by magnivar** [comment]
Då kör vi på det och skickar detta till Bouvet

**Comment by henrikekelof** [comment]
@perber14 Ett par frågor: 
- Ska boxen ha samma utseende som komin förutom färgvalen (runda hörn, tunna kantlinjer etc) eller ska den vara kantig och fetare som den bild du postade?
- Blå topp och kantlinje är inte enl. WAG. Är det OK att avvika i detta fall?

**Comment by henrikekelof** [comment]
Min tolkning finns på https://www.test.malmo.se/4.719e72ae160e0f98c258aeea.html:
![screen shot 2018-01-18 at 14 26 45](https://user-images.githubusercontent.com/186166/35100306-aa8440c2-fc5b-11e7-89f1-1207d5634a39.png)

**Comment by perber14** [comment]
Vi provar att utgå från den du nu har i bilden ovan och ersätt det blå med hex #e8e8e8. Samt gör bakgrunden i boxen vit.

**Comment by henrikekelof** [comment]
![screen shot 2018-01-18 at 14 47 38](https://user-images.githubusercontent.com/186166/35101104-8f8be45c-fc5e-11e7-82df-78b4c18c51f2.png)

**Comment by perber14** [comment]
Topp!

Prova att sätt kantlinjen i hex #757575!

**Comment by henrikekelof** [comment]
![screen shot 2018-01-18 at 15 33 51](https://user-images.githubusercontent.com/186166/35103035-0887e8aa-fc65-11e7-8782-8abf5f677dcd.png)

**Comment by perber14** [comment]
@henrikekelof Designmässigt OK! Men vi vill att den kan ha en rubrik som är längre än en rad. Som här:

![image](https://user-images.githubusercontent.com/22030097/35140446-8f08bd40-fcf7-11e7-82f4-eff816a9604d.png)

Plus/minus centreras vertikalt. Se http://srvsusesvprod05.malmo.se/4.638cf67815fc0dc45db4178.html (Magnus trodde att du kommer åt den?).

**Comment by henrikekelof** [comment]
@perber14 Inga problem:
![screen shot 2018-01-19 at 10 14 51](https://user-images.githubusercontent.com/186166/35143381-a32ed192-fd01-11e7-96f5-6bb8f649d562.png)

**Comment by henrikekelof** [comment]
@perber14 Du assignar mig igen om du är nöjd och vill att jag flyttar detta till prod va?

**Comment by perber14** [comment]
@henrikekelof Japp! Vi är snart redo! Men vi vill ha in den linje som finns på gywebbarna, som lite ringar in plus/minus. Det hänger för mycket i luften annars (framförallt när rubrikplattan är två rader tjock). 

Kan du kika på det?

**Comment by henrikekelof** [comment]
@perber14 Yes, jag tar det inom de närmsta timmarna. Tänker du en vit eller svart linje? Om det ska vara svart linje bör man nog dra en svart linje i botten av rubriken också för att rama in. Vit linje går nog bra att bara lägga dit som det är.

**Comment by perber14** [comment]
@henrikekelof Prova med en vit först så ser vi hur det känns. Blir det för mesigt provar vi svart.

**Comment by henrikekelof** [comment]
![screen shot 2018-01-22 at 10 08 05](https://user-images.githubusercontent.com/186166/35212936-2bbf7a5a-ff5c-11e7-973d-813b502a6b67.png)

@perber14

**Comment by perber14** [comment]
@henrikekelof Ser bra ut! Men fixa den här lillskiten:

![image](https://user-images.githubusercontent.com/22030097/35264856-96b44094-001e-11e8-86f8-4721076d9cbc.png)

**Comment by henrikekelof** [comment]
@perber14 Vilken webbläsare har du där? Jag kan inte återskapa i Firefox, Safari eller Chrome i alla fall. Har du IE/Edge?

**Comment by henrikekelof** [comment]
@perber14 Nu har jag återskapat det i IE11, om jag zoomar till 125%, 150%, 225%, 250%, och i Chrome med zoom 250% etc. Så, jag vill nog hävda att det är bra som det är. Kan inte specialhantera en massa olika zoomnivåer i olika webbläsare.

**Comment by perber14** [comment]
@henrikekelof Dåså! Tack. Vi betraktar den som klar.

Invänta vår signal för överföring till prod (vi ska reda ut en redaktionell fråga innan dekorationen sjösätts).

**Comment by henrikekelof** [comment]
Absolut. Bara assigna ärendet så fixar jag.

**Comment by Svempan** [comment]
Klar för prod :-)

**Comment by henrikekelof** [comment]
Nu finns den här i produktion. Testsida: http://malmo.se/4.693435e1616fea8abd180f1.html

**Comment by perber14** [comment]
Rubriken på boxen ska tjäna som H4 på malmo.se, inte H2 som den nu är!

**Comment by henrikekelof** [comment]
OK. Fixat!

**Comment by perber14** [comment]
Topp! Då stänger vi den här nu (och så får vi se om det håller...).
