### ISSUE TITLE
Avstängda moduler

### ISSUE THREAD

**Issue by magnivar** [malmostad/sitevision_assets#380]
Vi har fått mail:
Skickat: den 22 januari 2018 17:24 från servern
![image](https://user-images.githubusercontent.com/22590738/35275048-b668bac6-003e-11e8-9841-a0775015195e.png)

http://www.malmo.se/4.4ecfe75e1245d91676080004890.html

Vad innebär detta?
Skapar detta massa loggrader?

**Comment by badwiz** [comment]
Har inte sett detta förut, men om man kikar på sidan och modulen "Länkad modul" så har länkningen gått sönder. Den pekar inte på något just nu. Om detta ändras så kommer länkarna att visas och felemeddelandet försvinna. Detta är nog något som har varit fel länge och som CMS:et har kraschat. Sidan har inte ändrats sedan 2010...

**Comment by badwiz** [comment]
Fixat! Översedd av @magnivar @Svempan
