### ISSUE TITLE
Lägga SpellisteVideoModulen på komin PROD

### ISSUE THREAD

**Issue by magnivar** [malmostad/sitevision_assets#381]
Lägg SpellisteVideoModulen på komin PROD

**Comment by magnivar** [comment]
Assigna @fredrikwittbjer när det är gjort så verifierar han och stänger ärendet :)

**Comment by henrikekelof** [comment]
Klart. Testsida: http://komin.malmo.se/edit/4.135ada9214bfedef74c36b4b

OBS! De gamla modulerna för video är INTE ersatta på webbplatsen, men möjligheten att göra det finns alltså nu.

**Comment by magnivar** [comment]
@henrikekelof vi hittar inte sidan att kolla på

**Comment by henrikekelof** [comment]
@magnivar - Det var konstigt. Kan det vara att jag använde http i länken månne? Prova igen med https <https://komin.malmo.se/edit/4.135ada9214bfedef74c36b4b>

Annars ligger sidan här (se bild) och det går att hitta elementet/modulen under Bild och media / Videospelare spellista
![screen shot 2018-02-01 at 08 39 15](https://user-images.githubusercontent.com/186166/35666819-c2c44c92-072b-11e8-81cf-e7f6f477c516.png)

**Comment by magnivar** [comment]
Ser kanon ut :) Tack!
