### ISSUE TITLE
Lägg till "Publicerad" för nyheterna

### ISSUE THREAD

**Issue by perber14** [malmostad/sitevision_assets#384]
Vi vill visa både "Publicerad" och "Senast uppdaterad" för våra nyheter:

![image](https://user-images.githubusercontent.com/22030097/35500868-448262a6-04d8-11e8-8800-7161bbc702e0.png)

Samma design och så vidare. På raden ovanför "Senast uppdaterad".

@magnivar Sätter den till dig så att du kan introducera Bouvet till den när det blir läge.

**Comment by israelsson** [comment]
Har fixat detta på test.malmo.se och mallen "Nyhetsmall". Kontrollera så att det blev som tänkt så kan vi lägga in det på prod om ni är nöjda.

**Comment by perber14** [comment]
@israelsson Vi var otydliga. Det är värdet "Skapad" som ska visas efter rubriken "Publicerad". Det ska alltså vara två olika värden som resultat:

"Publicerad" = metadata fältet "Skapad"
"Senast uppdaterad = metadatafältet "Senast publicerad"

**Comment by israelsson** [comment]
Ok, då har jag ändrat det nu.

**Comment by perber14** [comment]
@israelsson Topp! 

Två saker: Minska utrymmet mellan de olika metadatafälten och korrigera så att det är kolon vid båda tidsangivelserna (istället för som nu punkt där uppe och kolon där nere):

![image](https://user-images.githubusercontent.com/22030097/35728713-bf6632b8-080c-11e8-9f7b-0a5ae77ea39d.png)

**Comment by israelsson** [comment]
Fixat!

**Comment by perber14** [comment]
Topp! Prodsätt, tack!

**Comment by israelsson** [comment]
Fixat!
