### ISSUE TITLE
Byta ut 404-sidan mot en enklare sida

### ISSUE THREAD

**Issue by badwiz** [malmostad/sitevision_assets#390]
Det  finns problem i mallen som gör att varje gång en besökare kommer till 404-sidan så rasslar det till med en massa felmeddelanden i loggen. Detta beror på SiteVisions 404-funktion tillsammans med funktionen för Fakta och Läs mer som hanteras genom metadata på sidor.

Funktionen fungerar bra att lämna helt tom på alla andra sidor men inte på 404-sidan när man redirectas dit genom SVs inbyggda funktion.

Förslaget är att byta ut mallen på 404-sidan och ha en sida utan Fakta och Läs mer som ändå inte används. All funktionallitet kommer att finnas kvar som vanligt, men en ny mall behöver skapas för detta ändamål.

**Comment by magnivar** [comment]
Ja, det verkar som en lösning. Kör på det.

**Comment by israelsson** [comment]
Har fixat detta nu på prod. Fixade en mall som ser likadan ut som mallen "Normalsida" men rensade bort det som inte behövs för 404-sidan.

**Comment by badwiz** [comment]
En koll i loggen visar att problemet inte finns längre :)

**Comment by magnivar** [comment]
Toppen då stänger vi
