### ISSUE TITLE
Formulärelementen har inte grupperats

### ISSUE THREAD

**Issue by olajoh1** [malmostad/sitevision_assets#392]
Formulärelementen   har inte grupperats | Saknar fieldset på ett formulär | Fixas i Synpunkts-modulen | Bouvet åtgärdar.
-- | -- | -- | --

@badwiz Något estimat eller du bara fixar?

**Comment by badwiz** [comment]
Lägger 0,5 - 1 h på fix. Ping @henrikekelof

**Comment by olajoh1** [comment]
ok

**Comment by henrikekelof** [comment]
Jag har testat och kollat på den här nu. Problemet rörde den gamla lösningen för synpunktshantering som jag tog bort igår, där det var radioknappar som inte var grupperade. Min nya lösning använder inte radioknappar och behöver därför inte grupperas med ett fieldset, så den nya synpunktshanteringen är inte berörd av det här felet. Felen kommer att försvinna av sig självt i Siteimprove nu när formuläret är utbytt.
